// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

package graph

import (
	"fmt"
	"unique"

	"github.com/korrel8r/korrel8r/internal/pkg/cache"
	"github.com/korrel8r/korrel8r/pkg/korrel8r"
	"gonum.org/v1/gonum/graph"
	"gonum.org/v1/gonum/graph/multi"
)

// Line is a graph object for a topology line: one rule connecting a specific pair of
// class nodes. Its ID is assigned by Data, independent of its pointer identity.
// Searches and mutable Graphs own Lines and their Queries; View uses only IDs.
// Different rules (or repeated input rules) may connect the same pair of nodes.
type Line struct {
	multi.Line
	Attrs
	Rule    korrel8r.Rule
	Queries Queries // Queries generated by this rule for this pair of classes.
}

func (l *Line) String() string { return lineString(l) }

var lineString = cache.FuncWeakKey(func(l *Line) string {
	return unique.Make(fmt.Sprintf("%v(%v->%v)", l.Rule.Name(), l.Start().Class, l.Goal().Class)).Value()
})

// Copy preserves line identity and rule, binds the supplied endpoints, and
// initializes fresh, empty mutable state. Queries and attributes are not copied.
func (l *Line) Copy(from, to *Node) *Line {
	return &Line{
		Line: multi.Line{F: from, T: to, UID: l.UID}, Rule: l.Rule,
		Attrs: Attrs{}, Queries: Queries{},
	}
}

func (l *Line) DOTID() string { return l.Rule.Name() }
func (l *Line) Start() *Node  { return l.From().(*Node) }
func (l *Line) Goal() *Node   { return l.To().(*Node) }

// Edge groups all parallel Lines between a pair of nodes in a Gonum Graph.
// It is an algorithm/iteration view, not a separate topology record.
type Edge struct{ multi.Edge }

func EdgeFor(e graph.Edge) Edge { return Edge{e.(multi.Edge)} }
func (e Edge) Start() *Node     { return e.F.(*Node) }
func (e Edge) Goal() *Node      { return e.T.(*Node) }

// EachLine consumes this Edge's iterator. For independent concurrent iteration,
// use Graph.EachLineBetween instead.
func (e Edge) EachLine(visit func(*Line)) {
	lines := e.Lines
	for lines.Next() {
		visit(lines.Line().(*Line))
	}
}
