=  Korrel8r as an AI tool
:link-openapi-mcp: https://github.com/janwilmake/openapi-mcp-server
:link-mcp: https://modelcontextprotocol.io/
:link-korrel8r: https://korrel8r.github.io/korrel8r/
:toc: left

link:{link-mcp}[Model Context Protocol] (MCP) allows LLMs to use external tools.
This is an experiment in using link:{link-korrel8r}[Korrel8r] as an MCP tool.

CAUTION: This is an experiment in progress. Everything is subject to change without notice.

== Run Korrel8r

This example clones the korrel8r repository and runs korrel8r locally for easy experimentation.
A more realistic example would run an MCP server in the cluster alongside korrel8r.

[,terminal]
----
git clone https://github.com/korrel8r/korrel8r
cd korrel8r
oc login <my-cluster>  <1>
go run ./cmd/korrel8r web -c etc/korrel8r/openshift-route.yaml <2>
----

<1> You need to be logged in to the cluster to get an access token.
<2> Run korrel8r on port 8080 (default) using the current log-in token (default),
    with the `openshift-route.yaml` configuration which connects to the current cluster.

[TIP]
====
You can connect the MCP server directly a Korrel8r instance  as installed by the COO in the cluster.
To print the URL:
[,terminal]
----
oc get routes/korrel8r -n openshift-cluster-observability-operator -o template='https://{{.spec.host}}'
----
====


== Run Korrel8r

The Cluster Observability Operator (COO) deploys korrel8r for you in the cluster.
To use the COO korrel8r instance, set its URL in your environment:

  export KORREL8R_URL=$(oc get routes/korrel8r -n openshift-cluster-observability-operator -o template='https://{{.spec.host}}')

You can also run korrel8r locally, using routes to connect to stores in the cluster.

  korrel8r web --http :8080 --config ../etc/korrel8r/openshift-route.yaml
  export KORREL8R_URL=http://localhost:8080

== Generating an MCP server from the REST API

=== Install openapi-mcp

link:{link-openapi-mcp}:[openapi-mcp] is a tool that creates an MCP server from an OpenAPI spec.
Korrel8r has a REST API with an OpenAPI spec, so we can create an MCP proxy for korrel8r.
The MCP server exposes the API description, including documentation and examples,
so that models can read it and learn how to use the tool.

[,terminal]
----
go install github.com/jedisct1/openapi-mcp/cmd/openapi-mcp@latest
----

The MCP server can run in two modes:
- as a "stdio" server, intended to be run directly by a local AI tool, such as Claude Desktop.
- as a stand-alone HTTP proxy, receiving MCP requests and forwarding REST calls to korrel8r.

=== Shell script to run the MCP server

.Copy this script to file `korrel8r-mcp` and put it somewhere in your PATH
[,bash]
----
#!/bin/bash
export BASE_URL=http://localhost:8080/api/v1alpha1
export BASE-URL=$(oc whoami -t)
exec openapi-mcp doc/korrel8r-openapi.yaml
----

This shell script runs openapi-mcp as a `stdio` server that can be run directly by the Claude-desktop.
It uses the OpenAPI description in file `doc/korrel-openapi.yaml` to translate the korrel8r API to MCP.
It uses the current cluster login token given by `--bearer-token=$(oc whoami -t)`

== Claude Desktop

The first experiment was with Claude desktop, because it provides a straightforward way to connect to MCP servers running locally.

=== Installing on Fedora 42

Claude-desktop is not officially packaged for Linux, it is not too hard to get it working.
There is an unofficial fedora package. Clone the repository and follow README to build & install.

[,terminal]
----
    git clone https://github.com/sneered/claude-desktop-fedora.git
----

This didn't immediately work, there were errors about GT 3/4 version clashes.
Installing an *older* version of electron (the portable runtime that Claude uses) fixed the problem.

[,terminal]
----
    sudo npm remove -g electron
    sudo npm install -g electron@v35.5.1
----

=== Connect to Korrel8r

On Linux the Claude configuration file is at `~/.config/Claude/claude_desktop_config.json`

Edit it to look like this:
----
{
  "mcpServers": {
    "korrel8r": {
      "command": "</abs/path/to/>korrel8r-mcp.sh"
    }
  }
}
----

This allows claude-desktop to run the MCP server as a command in `stdio` mode.

IMPORTANT: If you change the Claude configuration or restart the MCP server,
you must restart Claude desktop completely via `File:Exit`, not just `File:Close`.


=== Results

*Ask Claude:* Show me a korrel8r graph.

.Results
- Claude does query the MCP info and try to use each of the API endpoints.
- Successfully lists domains, and describes them sensibly.
- Did not make any successful queries. The korrel8r query syntax is not widely discussed on the internet.
- Hit usage restrictions of free Claude very quickly, it is not a practical tool for further experiments.

=== Next steps

- Improve documentation and examples of the query format available via MCP `info` - i.e. the REST API `description` and `example` elements.
- Add more HTTP links to the korrel8r website in the API doc, so models can follow those links and use the doc there.
- Use Red Hat light-speed to drive the experiment instead of public models.
- Write a dedicated MCP server rather than generating from REST. Reasons:
  - Restrict operations that the model can call.
  - Provide "you are a blah, you must do blah" type of prompts and descriptions, which would be unsuitable in REST docs.
  - Use features of the MCP protocol that are not available in a REST mapping - resources, prompts.
  - Allow exposing new/different MCP tools or data structures that may not make sense for the REST API.

== Debugging tricks

The following command install and runs an interactive browser-based tool that can connect to any MCP server.
It will show metadata, let you call tools interactively and examine the responses.

   npx @modelcontextprotocol/inspector
