=  Korrel8r as an AI tool
:link-openapi-mcp: shttps://github.com/jedisct1/openapi-mcp
:link-mcp: https://modelcontextprotocol.io/
:link-korrel8r: https://korrel8r.github.io/korrel8r/
:toc: left

Large Language Models using link:{link-korrel8r}[Korrel8r] via the link:{link-mcp}[Model Context Protocol].

CAUTION: This is an experiment in progress. Everything is subject to change without notice.

IMPORTANT: You must `oc login` to an Openshift cluster.

== Running korrel8r as MCP server

The `korrel8r mcp` command runs an MCP stdio server.

The `korrel8r web` command serves 3 endpoints:

- `/api/v1alpha1` - REST API
- `/mcp` - MCP streaming protocol
- `/sse` - MCP Server-Sent Events protocol

You can connect to a korrel8r service in the cluster like this:

  oc create route reencrypt --service=korrel8r
  export KORREL8R_URL=$(oc get routes/korrel8r -n openshift-cluster-observability-operator -o template='https://{{.spec.host}}')

You can run korrel8r locally, using routes to connect to stores in the cluster.
  korrel8r web --http :8080 --config ../etc/korrel8r/openshift-route.yaml
  export KORREL8R_URL=http://localhost:8080

== Claude Desktop

Claude desktop was the first experiment because it is easy to register a local MCP server.

=== Installing on Fedora 42

Claude-desktop is not officially packaged for Linux, but there is an unofficial fedora package.
Clone the repository and follow README to build & install.

  git clone https://github.com/sneered/claude-desktop-fedora.git

This didn't immediately work, there were errors about GT 3/4 version clashes.
Installing an *older* version of electron (the portable runtime that Claude uses) fixed the problem.

  sudo npm remove -g electron
  sudo npm install -g electron@v35.5.1

=== Configure and Run

Copy the configuration file (or edit the Claude configuration file) as follows:

s  claude/config.sh
  claude-desktop

IMPORTANT: If you modify korrel8r or its configuration file,
exit Claude desktop with *File > Exit* (not *File > Close*) and re-start.


==== Korrel8r built-in MCP interface

First attempt
https://claude.ai/share/b36a14f5-8bf9-41e4-82f4-ccf648ce2cbf
Gets everything correct except pod query "name:korrel8r" - doesn't include class

== Openshift Lightspeed

Openshift Lightspeed integrates a chatbot into the Openshift console. Install as follows:

. From Operatorhub, install the 'OpenShift Lightspeed Operator'
. Configure lightspeed and a secret with your OpenAI API token.
+
----
SECRET=<your-token-string> envsubst < credentials.yaml | oc apply -f -  -f olsconfig.yaml
----
. Scale down the operator so you can manally edit the configmap. +
  `kubectl scale --replicas=0 -n openshift-lightspeed deployment/lightspeed-operator-controller-manager`
. Edit the config file and add this section under `ols_config`
+
----
include::olsconfig-cm-patch.yaml[]
----

[WARNING]
====
Incomplete, had problems with access quotas to OpenAI. To be continued.

  oc logs -n openshift-lightspeed deployment/lightspeed-app-server

  2025-07-22 18:19:03,002 [ols.app.endpoints.health:health.py:59] ERROR: LLM connection check failed with - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
====

== Next steps

- Improve documentation and examples of the query format available via MCP `info` - i.e. the REST API `description` and `example` elements
- Add more HTTP links to the korrel8r website in the API doc, so models can follow those links and use the doc there.
- Use Red Hat light-speed to drive the experiment instead of public models.
- Write a dedicated MCP server rather than generating from REST. Reasons:
- Enable interaction between console, korrel8r & AI.
  - Let AI change the console page (Troubleshooting-Panel? Korrel8r? Both?)
  - Use Korrel8r as an entry point for AI to query all back-end stores.
  - Provide a way for LLMs to refer to resources/signals/console pages - korrel8r query format?
  - Inject console context into chat context.

== Debugging tricks

A browser-based tool that can connect to any MCP server.
It will show metadata and allow you to experiment with calling tools.
[,terminal]
----
npx @modelcontextprotocol/inspector
----

IMPORTANT: Open the URL marked "Open inspector with token pre-filled:" in your browser.

== Next steps

- Use Red Hat light-speed to drive the experiment instead of Claude.
- Improve prompting and descriptions from MCP server.
- Enable interaction between console, korrel8r & AI.
  - Let AI change the console page (Troubleshooting-Panel? Korrel8r? Both?)
  - Use Korrel8r as an entry point for AI to query all back-end stores?
  - Provide a way for LLMs to refer to resources/signals/console pages - korrel8r query format?
  - Inject console context into chat context.

= Old experiments

For the record, here are some earlier experiments that were tried.

== Generating an MCP server from the REST API

link:{link-openapi-mcp}[openapi-mcp] is a tool that converts MCP to REST based on an OpenAPI spec.
The MCP server exposes the API descriptions from the spec and forwards MCP calls as REST calls.

.Installing
[,terminal]
----
go install github.com/jedisct1/openapi-mcp/cmd/openapi-mcp@latest
----

This shell script runs an MCP stdio server:

.korrel8r-mcp-proxy.sh
[,bash]
----
include::korrel8r-mcp-proxy.sh[]
----

The results were encouraging, but required deploying a separate proxy and did not give
full access to MCP protocol features (prompts, instructions, resource etc.)
This motivated the built-in MCP server in korrel8r to avoid these limitations.

- Finds the korrel8r tool and is able to read and report the available endpoints.
- Successfully calls `listDomains` (no parameters) and describes the available domains.
- Tries very hard to make queries
  - tries each endpoint available, many formats.
  - cannot format korrel8r queries correctly
- Halucinates a graph out of nothing

.Results
- Claude does query the MCP info and try to use each of the API endpoints.
- Successfully lists domains, and describes them sensibly.
- Did not make any successful queries. The korrel8r query syntax is not widely discussed on the internet.
- Hit usage restrictions of free Claude very quickly, it is not a practical tool for further experiments.
