// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/korrel8r/korrel8r/pkg/korrel8r"
	"github.com/oapi-codegen/runtime"
)

// Class Names a class of objects with the same schema or structure. It has 2 parts DOMAIN:CLASS DOMAIN: name of a domain. CLASS: name of a class in the domain.
type Class = string

// Console Describes the data displayed in the users console.
type Console struct {
	// Search Search parameters for the correlation search displayed in the console troubleshooting panel. Exactly one of goals, neighbors should be set.
	Search *Search `json:"search,omitempty"`

	// View Represents a request to retrieve data for a particular Class. It has 3 parts DOMAIN:CLASS:SELECTOR DOMAIN: name of a domain. CLASS: name of a class in the domain. SELECTOR: domain-specific query string to retrieve selected objects.
	View Query `json:"view,omitempty"`
}

// Constraint Constrains the objects that will be included in search results.
type Constraint = korrel8r.Constraint

// Domain Domain configuration information.
type Domain struct {
	// Description Brief description of the domain.
	Description string `json:"description,omitempty"`

	// Name Name of the domain.
	Name string `json:"name"`

	// Stores Stores configured for the domain.
	Stores []Store `json:"stores,omitempty"`
}

// Duration The duration string is a sequence of decimal numbers, each with optional fraction and a unit suffix. Valid time units are: ns, us (or µs), ms, s, m, h.
type Duration = time.Duration

// Edge Directed edge in the result graph, from Start to Goal classes.
type Edge struct {
	// Goal Class name of the goal node.
	Goal Class `json:"goal"`

	// Rules Set of rules followed along this edge.
	Rules []Rule `json:"rules,omitempty"`

	// Start Class name of the start node.
	Start Class `json:"start"`
}

// Error Error result containing an error message.
type Error struct {
	// Error Error message.
	Error string `json:"error"`
}

// Goals Starting point for a goals search.
type Goals struct {
	// Goals Goal classes for correlation.
	Goals []Class `json:"goals"`

	// Start Start identifies a set of starting objects for correlation.
	Start Start `json:"start"`
}

// Graph Graph resulting from a correlation search.
type Graph struct {
	// Edges List of graph edges.
	Edges []Edge `json:"edges,omitempty"`

	// Nodes List of graph nodes.
	Nodes []Node `json:"nodes,omitempty"`
}

// Neighbors Starting point for a neighbors search.
type Neighbors struct {
	// Depth Max depth of neighbors graph.
	Depth int `json:"depth"`

	// Start Start identifies a set of starting objects for correlation.
	Start Start `json:"start"`
}

// Node Node in the result graph, contains results for a single class.
type Node struct {
	// Class Full class name
	Class string `json:"class"`

	// Count Number of results for this class, after de-duplication.
	Count *int `json:"count,omitempty"`

	// Queries Queries yielding results for this class.
	Queries []QueryCount `json:"queries,omitempty"`

	// Result Serialized result contents, may be large.
	Result []Object `json:"result,omitempty"`
}

// Object Data object serialized as JSON.
type Object = json.RawMessage

// Query Represents a request to retrieve data for a particular Class. It has 3 parts DOMAIN:CLASS:SELECTOR DOMAIN: name of a domain. CLASS: name of a class in the domain. SELECTOR: domain-specific query string to retrieve selected objects.
type Query = string

// QueryCount Query with number of results.
type QueryCount struct {
	// Count Number of results, omitted if the query was not executed.
	Count *int `json:"count,omitempty"`

	// Query Query for correlation data.
	Query Query `json:"query"`
}

// Rule Rule is a correlation rule with a list of queries and results counts found during navigation.
type Rule struct {
	// Name Name is an optional descriptive name.
	Name string `json:"name"`

	// Queries Queries generated while following this rule.
	Queries []QueryCount `json:"queries,omitempty"`
}

// Search Search parameters for the correlation search displayed in the console troubleshooting panel. Exactly one of goals, neighbors should be set.
type Search struct {
	// Goals Starting point for a goals search.
	Goals *Goals `json:"goals,omitempty"`

	// Neighbors Starting point for a neighbors search.
	Neighbors *Neighbors `json:"neighbors,omitempty"`
}

// Start Start identifies a set of starting objects for correlation.
type Start struct {
	// Class Class of starting objects and queries.
	Class Class `json:"class,omitempty"`

	// Constraint Constrain the objects that will be returned.
	Constraint *Constraint `json:"constraint,omitempty"`

	// Objects Start objects serialized as JSON.
	Objects []Object `json:"objects,omitempty"`

	// Queries Queries for starting objects
	Queries []Query `json:"queries,omitempty"`
}

// Store Store is a map string keys and values used to connect to a store.
type Store map[string]string

// GraphOptions defines model for GraphOptions.
type GraphOptions struct {
	// Errors if true include non-fatal error messages.
	Errors *bool `json:"errors,omitempty"`

	// Results If true include full JSON results with each Query.
	Results *bool `json:"results,omitempty"`

	// Rules If true include rule names in graph edges.
	Rules *bool `json:"rules,omitempty"`
}

// SetConfigParams defines parameters for SetConfig.
type SetConfigParams struct {
	// Verbose Verbose level for logging.
	Verbose *int `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// GraphGoalsParams defines parameters for GraphGoals.
type GraphGoalsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighborsParams defines parameters for GraphNeighbors.
type GraphNeighborsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighboursParams defines parameters for GraphNeighbours.
type GraphNeighboursParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// ObjectsParams defines parameters for Objects.
type ObjectsParams struct {
	// Query Query string.
	Query Query `form:"query" json:"query"`
}

// GraphGoalsJSONRequestBody defines body for GraphGoals for application/json ContentType.
type GraphGoalsJSONRequestBody = Goals

// GraphNeighborsJSONRequestBody defines body for GraphNeighbors for application/json ContentType.
type GraphNeighborsJSONRequestBody = Neighbors

// GraphNeighboursJSONRequestBody defines body for GraphNeighbours for application/json ContentType.
type GraphNeighboursJSONRequestBody = Neighbors

// ListGoalsJSONRequestBody defines body for ListGoals for application/json ContentType.
type ListGoalsJSONRequestBody = Goals

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Change configuration settings at runtime.
	// (PUT /config)
	SetConfig(c *gin.Context, params SetConfigParams)
	// Make console state available to an agent.
	// (PUT /console)
	SetConsole(c *gin.Context)
	// Updates for the console display from an agent.
	// (GET /console/updates)
	ConsoleUpdates(c *gin.Context)
	// Get the list of classes for a domain.
	// (GET /domain/{domain}/classes)
	ListDomainClasses(c *gin.Context, domain string)
	// Get the list of correlation domains.
	// (GET /domains)
	ListDomains(c *gin.Context)
	// Create a correlation graph from start objects to goal queries.
	// (POST /graphs/goals)
	GraphGoals(c *gin.Context, params GraphGoalsParams)
	// Create a neighborhood graph around a start object to a given depth.
	// (POST /graphs/neighbors)
	GraphNeighbors(c *gin.Context, params GraphNeighborsParams)
	// Create a neighborhood graph around a start object to a given depth.
	// (POST /graphs/neighbours)
	GraphNeighbours(c *gin.Context, params GraphNeighboursParams)
	// Create a list of goal nodes related to a starting point.
	// (POST /lists/goals)
	ListGoals(c *gin.Context)
	// Execute a query, returns a list of JSON objects.
	// (GET /objects)
	Objects(c *gin.Context, params ObjectsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SetConfig operation middleware
func (siw *ServerInterfaceWrapper) SetConfig(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SetConfigParams

	// ------------- Optional query parameter "verbose" -------------

	err = runtime.BindQueryParameter("form", true, false, "verbose", c.Request.URL.Query(), &params.Verbose)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter verbose: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetConfig(c, params)
}

// SetConsole operation middleware
func (siw *ServerInterfaceWrapper) SetConsole(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetConsole(c)
}

// ConsoleUpdates operation middleware
func (siw *ServerInterfaceWrapper) ConsoleUpdates(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConsoleUpdates(c)
}

// ListDomainClasses operation middleware
func (siw *ServerInterfaceWrapper) ListDomainClasses(c *gin.Context) {

	var err error

	// ------------- Path parameter "domain" -------------
	var domain string

	err = runtime.BindStyledParameterWithOptions("simple", "domain", c.Param("domain"), &domain, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter domain: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDomainClasses(c, domain)
}

// ListDomains operation middleware
func (siw *ServerInterfaceWrapper) ListDomains(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDomains(c)
}

// GraphGoals operation middleware
func (siw *ServerInterfaceWrapper) GraphGoals(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GraphGoalsParams

	// ------------- Optional query parameter "options" -------------

	err = runtime.BindQueryParameter("form", true, false, "options", c.Request.URL.Query(), &params.Options)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter options: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GraphGoals(c, params)
}

// GraphNeighbors operation middleware
func (siw *ServerInterfaceWrapper) GraphNeighbors(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GraphNeighborsParams

	// ------------- Optional query parameter "options" -------------

	err = runtime.BindQueryParameter("form", true, false, "options", c.Request.URL.Query(), &params.Options)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter options: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GraphNeighbors(c, params)
}

// GraphNeighbours operation middleware
func (siw *ServerInterfaceWrapper) GraphNeighbours(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GraphNeighboursParams

	// ------------- Optional query parameter "options" -------------

	err = runtime.BindQueryParameter("form", true, false, "options", c.Request.URL.Query(), &params.Options)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter options: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GraphNeighbours(c, params)
}

// ListGoals operation middleware
func (siw *ServerInterfaceWrapper) ListGoals(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGoals(c)
}

// Objects operation middleware
func (siw *ServerInterfaceWrapper) Objects(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ObjectsParams

	// ------------- Required query parameter "query" -------------

	if paramValue := c.Query("query"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument query is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", c.Request.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter query: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Objects(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.PUT(options.BaseURL+"/config", wrapper.SetConfig)
	router.PUT(options.BaseURL+"/console", wrapper.SetConsole)
	router.GET(options.BaseURL+"/console/updates", wrapper.ConsoleUpdates)
	router.GET(options.BaseURL+"/domain/:domain/classes", wrapper.ListDomainClasses)
	router.GET(options.BaseURL+"/domains", wrapper.ListDomains)
	router.POST(options.BaseURL+"/graphs/goals", wrapper.GraphGoals)
	router.POST(options.BaseURL+"/graphs/neighbors", wrapper.GraphNeighbors)
	router.POST(options.BaseURL+"/graphs/neighbours", wrapper.GraphNeighbours)
	router.POST(options.BaseURL+"/lists/goals", wrapper.ListGoals)
	router.GET(options.BaseURL+"/objects", wrapper.Objects)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbXPbuPH/Khj+/zOXTCnJdtK5G73L2W7GvTz4ouReNHVnIHJF4QICDADKVjP+WP0C",
	"/WSdXYAURUKynPhyN23e3EUguVjs42934U9JpstKK1DOJtNPScUNL8GBoV/PDa+WrysntKLfOdjMCPqd",
	"TJPwgGVaOaOlFKpgbglsoU3J9IL+bcDVRkHOCiQ1TtIEbiqpc0imztSQJgIpfazBrJM0UbyEZJrosGOa",
	"2GwJJSfGjK7AOAHECBijTYQlsWBIlgmVyToHprQaLbjjktEXrARreQEWGXHrCjebay2Bq+Q2TQzYWroI",
	"2Yse2UUtJfvr7PUrFj5h18ItGfBsyX7Gs+ygX0s4gDq+xlAUlgnlBccg38H1bbuk579C5nAf69YSV1AR",
	"9IYXI219KrmN8PCKtuMsw8eoPE8tHAw1aXkJzBNi2jDrTJ252sCYXTi25JadsIobZ9nZ65fPLl5NT188",
	"m82aH3QcJMtZrksu1JjR8+4Dv7VQtFt46++KLIaXFR3IGZ7B1FYclyvuHBhk/v0/pld/mtJ/NxKyzghV",
	"JGlyMyr0CBdH9oOoRt64uBxVWigHxhvibZqcamU1btOXzRn9moP1nHHHWS5sJfka8obf2oIhT0ASqKdt",
	"e7XATbbEf/2/gUUyTf5vsvG7SVDPZObfuk2TlYDru94mQ4sbAB7FGS6UG56mfeaP0+jZLblj10JKNm8t",
	"kU7nWW8MfXg0UHnEpAulDfSMSJRgHS8ry/jCgWFuKSwDldOT8ZaiT46Ovx8dfT86OX57/P30ycn05Ifx",
	"8ZOnxydPjv+WpGTY3CXTJOcORvj5QO+3aSJFKSICeIHLzGmMCqou52C69l6BYR97Lox2UoDxrsWNu/d5",
	"57DAx3RgotAe+bCT4LquaV8u5etFMn2/3zbOasOJtdurtG/N55dvzk+fvT0/Y9YhVxmX0jJO/1IZSAn5",
	"xusNfKzBunHEzjqelUyTD9oYkD+Yccf2btPkjPw44lO0jg6zEEVglgnlxSG0GtrZ1vd9cj8aAQvWWWvy",
	"T4gjXxAWfE6Kxcu79iBz0SYW8me03h4fckyaPWLCQWnvDBlIKNnohhvD1wefjnLex1oYyJPpe3/Uq0g8",
	"ac1pcJC3yHKjP39uJjCRWDQclZGQcshE2XqbTX2iJBtrGGMLwzMiwlXOOKuVcMzWi4W4GbNfuBQ+StA6",
	"GeuUKZuy2rJH2rB//8s+TllpU2ZTVqZs2U8cJ8unfy633K050R7DwISDbrpxpjQ5z4tYhhAGMgc5pekm",
	"JfiI6fN3yhZGl2zmfV+z55pLn/AgElILzeXhvu4z+tDRab3Nr8gR0mVK5zDeg0Zm4PB9esoWWkp9DTnj",
	"UhO6w4idF3Cwfb6p5WebJ76mS9ymcuvWH9sI/NDS8YE5iKfnGX7T1Gsm5iHnCC+HwqTlxhIQJ3Oh0EW4",
	"2gakkbS6j2Dnq17I6fHtqcQYRguMBiZuHHJImqCoxMlubAACcWuNUOqaONHJKEO00b11zvfJhx/s9FLn",
	"yOdBRhV0+plBr2NC+yMrvtQXqD9sQyIqWPT3iDgIxntLQPlSPOBdoewUMGH/GI6x5Km9AuEgCVIY+3wB",
	"opPcyRG9dDBHr7Am/II8NtDDKxDFch6tEqNGrpr3d+ohh8pFNPuS3zB6hEffUGkL3j0g8v7253nYZ38k",
	"yCFe0fmOxBSikm1LWS8OK1QhwTvwUBRZvIr8C9bFWRtZY4go03WsKnnVAvEuG5RviF4aaoYcRnldSZG1",
	"cWQoXoTvMdCY/OwfsLUAmaP+43sdbLNUgZ3SgT7flzwPsTxsBJfin5B38wfun7KSr7FMk9zcIxW/bk3k",
	"IbCit4CYAYZ9MEPnufC0LjvW41N7D0BhUe1JMLs5OLfUZemoOVp7/Gq1Gr/h1y99WkQmfHE8EOobqAxY",
	"FAvjTW2DeMyAMwJWobr3HlBhkMhqyQ2jhNM2Op5EGh3T2fmL89O3r998aceDNYSmYWVkK8jEQmS+LG1A",
	"dpdpC9LDz1B/9tFvyK/TT9RUqngGU7bQOiVWpmzOTcokn4O0U/aJ8Smbs9uULdBLaCWbspzd3u7quXxx",
	"56XjR1GfXftaQfVjRCQuHRhdUobAEkUmPPjzsr3mlintGNxAVjvId8eX9eEINPRpBgjUn6yHjMgAh/jT",
	"bxnzNgLYQzuvJfg6rEubGoskSs5kyNUhWFLZ1YRDkiJGxVrlWN2hvSm+EsWO0nxPiYw8qE2V176x8h3O",
	"aNF8Z/wuQIHhqL3rpZAQqhTRFCh4zK8Zww+tomdtE7Af6anDtmm9t82AITocdh5Dz5E5o+u5BLvU2mMb",
	"rkCO2fkNz5xcM60o6BB+TbtgZ6lrmWM2seD2gPt9MvS1BOLCLubai/baF6PYbRbvsvnyWeSgnFiQ0SLT",
	"eCzbILqmAxcpOHYgmIcoI2McoEMFSx7fIxZmW63bA5nrtNyGHDYPd7d7myENtQXCG7uk3xCIZ+mvAUQO",
	"CBALGlBsK+ReAeFBKxHfo9uJhz4NI2CkWeijecmrBgB8gLU3shWXNVhWW8gRFWRaKYRRTqN74KdD+HSL",
	"fMINpnIuz3QWEeVPoZ/L3lkw7HktcoTztZHJNFk6V9npZNL2fAvhlvV8LHS7NMFjCLXQPisrxz0kDBO+",
	"S6MJ6zW7DEgHipkuNySbfwwl9DwkBF/TUFCjdNCJAJbNwV0DKMxyujZZyHl6bsGs+FxI4dbMikJxSZgM",
	"4VltHRgUnxQZKAudEzyreLYEdjI+uhfvk7nU8wniusmLi9PzV7Nz3993BNRaob85n71lzy4vkjRZgbH+",
	"lKtjLqslPyYvrUDxSiTT5Mn4aHzsodmS9DjxXWUamtaRKPpS52Kx3oDG7R68BYdeY9kjGBdjJnXBVmDm",
	"2gq3fsw0ysXUippYKDiRgUebaM9E4SL3TcRTz0W6NVJ+32fmF6INTMIKJPmt1EUhVEHRJDIb9szA1my4",
	"5DeirMtkenyUJqVQ/sfRELthdDRgK62s97yTo6PIXPsnPzSty5Ij0EtOl1wVsEtQ3KFEmoGO44Wl+qhp",
	"7SdXSGySbaaLUa1c1s6n89oYUA7Dl2tbk02Ot5oJxzKuQtQm+J+z+RpBFi/wu5Xg9MnL00s0oN3KIW48",
	"cgHrftT5unFV8LnHwY2bYGlFA8xW2HclIiRL8aV3viG6qaucBwOk0wVoM066eGpTJd+htdNtKi11W2cZ",
	"WLuopaSw/tR/3Dkor9qGwj3P67u+kdMKtaKZRcf2t03qJf/QUSvpmq+4kHyOUE63+uyZFEn3CpNRpnMo",
	"QI2C/kZzna9HwUfCWtI1vImXhwd1EDHAdxbYbHbOHqFbgxlhlcxghed9jBxZUHkQahegbquOvW31imVE",
	"CaHP2VhnbZtLInvsM2jyXWA4rvy+oRKnI+sM8BIXMdfPvtRoZ0QOvTCLWpcd99T6br98tqUR1S3pzFf+",
	"k0/+/7eT0Ebfqbs3BOBsp6zbNOE2zIRGAuRbtyu2Zf9CWOdns6dhzzsC+HAQisZCbHSa//12RBPcMWlt",
	"Yrv/fuD+3VDfH3dc3Wkd+727M4W41HmCRRoltSRNzqCSel0ime5gYucY6RFW1rp2jRgqAwtx8zg6z/8s",
	"aDkwT0xUv2NAw62f/vZbB3Eq7XxHoudyz8Enzi3Lh6aN3ZnNB08LrZSOn93Hr1qEFj4lDOmnh7GJPg26",
	"D/G2A8LcftEeVNuE2xjfLPB+W4f++8EW2G3nee3uMkBfr0zaLkulbazvQYF73Wt3NIVtigV408bDwndT",
	"mW/eoEsVRTuSHbONaftpXXc4LSWjaoJJ4HlnWNnd1teXRNEvxOybhp7Pw8i0l0Zimti8Mtm6eurD/C6g",
	"+vkaD42rSOL3zTY6t20ubRS9SxsHgdSH4ZNmyt/8L+5/pwYIP285nrfqjgLbzldQZKc3twFh/vv7Quzg",
	"xVvdz9/Wk/28uQF2zcZLrfNmej1wcL3oODYNAcLQ2jAJ1l/r6Xn8FnM7/XvTy/1D+ni31XyAn6NMW0V+",
	"8/I/oJdvWbu3bW5oVBXNUGIFypv6w7t6/T/q6/U3Z//m7P/9zo6A/ncG501Nge7cIJjubV7f56FpXtsW",
	"5tkSy88hZt9VgjYI/atCbHsXxH5wd/wK9xC/efNeb26sub2Ibpl3zLwZV3YvZj6EC3em2dEOz7m/6bO5",
	"8Ng2eL6jOv27cDEG/XGryB86sj/6mJ1p8LeIKjD0p5BcrbdKE/+HDtEk+7qdVe9tuv7cuQm2a1DW/Nzd",
	"Sz3kj8uuHsrn9t0FHEzMvznfwznfxsLJItJgzN3kQn/J2kC/WKcKCdJUyBujH3dPeCUmm5n0VfvdzqsE",
	"mKF45jAlcjY3Ii+gncpz9vzdRTsvoZSo2LOLMCmhuVIzQgLbeul3thkkYQDJhc30Cgy7xnwobPSylLYS",
	"fM5thloKrv29T6fDXGdIwHPQsEc8IL1mutYO7Km/UBm9EnTfuv17NsbnujfhDbRbXniWQeU2IzZMjK49",
	"ttMs82NomrSEeRuFkODwzQjp9ur2PwEAAP//VHw3u9Y9AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
