version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
    groups:
      tools-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/pkg/api"
    schedule:
      interval: "daily"
    groups:
      api-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/pkg/mcp"
    schedule:
      interval: "daily"
    groups:
      mcp-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/doc"
    schedule:
      interval: "daily"
    groups:
      doc-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-dependencies:
        patterns:
          - "*"
