# Make fragment for building the doc/ hierarchy
FRONT=./hack/front-matter.sh

doc/content: doc/content/reference/domains doc/content/reference/rest doc/content/reference/cmd
	@touch $@

doc/public: $(shell find doc | grep -v doc/public)
	go tool hugo --source doc --quiet
	@touch $@

.PHONY: preview
preview: doc/content  ## Run local preview server for documentation.
	go tool hugo server --source doc --baseURL http://localhost:1313 --bind 0.0.0.0  --quiet

.PHONY: check-links
check-links: doc/public ## Check for broken internal links in the generated site.
	hack/check-links.sh doc/public "^/client/"

doc/content/reference/domains: $(foreach D,$(DOMAINS), doc/content/reference/domains/$(D).md)
doc/content/reference/domains/%.md: pkg/domains/%/doc.md $(GENERATED) $(MAKEFILE_LIST)
	@mkdir -p $(dir $@)
	@cp $< $@
	@sed -i '1i # $(basename $(notdir $@))' $@
	@$(FRONT) $@ 'title: $(basename $(notdir $@))' "description: $$(sed -n '/^[^#]/{/./p;q}' $@)"

doc/content/reference/rest: doc/content/reference/rest/index.md
doc/content/reference/rest/index.md:  $(OPENAPI_SPEC)  $(MAKEFILE_LIST)
	@mkdir -p $(dir $@)
	go tool openapi-markdown -o $@ -title "" -description "" $<
	@$(FRONT) $@ 'title: REST API' 'description: HTTP API reference'

doc/content/reference/cmd: doc/content/reference/cmd/index.md
doc/content/reference/cmd/index.md: $(GENERATED) $(shell find cmd pkg) $(MAKEFILE_LIST)
	@mkdir -p $(dir $@)
	unset KORREL8R_CONFIG; go run ./cmd/korrel8r doc markdown $(dir $@)
	@mv $(dir $@)korrel8r.md $@
	@$(FRONT) $@ 'title: Commands' 'description: Command-line interface'
	@sed -i '/###### Auto generated by/d' $@
