= Korrel8r: Signal correlation for Kubernetes
:toc: left
:pages: https://korrel8r.github.io/korrel8r
include::doc/attributes.adoc[]

[abstract]
Korrel8r is a correlation engine for observability signals and observable resources. +
It can correlate multiple domains, diverse signals, inconsistent labeling, and varied data stores.

CAUTION: Korrel8r is still in early development. There are no compatibility guarantees between versions.


The goals of this project include:

* Encode domain knowledge from SREs and other experts as re-usable _rules_.
* Automate navigation from symptoms to data that helps diagnose causes.
* Connect data from diverse types of store, with different schema.
* Reduce multiple-step manual procedures to fewer clicks or queries.
* Help tools that gather and analyze diagnostic data to focus on relevant information.

There is a short link:demos/openshift-console-browser/video.mov[demo video]

== Getting Started

To try the {rh-ocp} preview features, do the following:

. link:{pages}#installing-korrel8r-ocp[Install the operator.]
. link:{pages}#using-ocp-console[Try it out!]

== Documentation

- {pages}[Korrel8r User guide and Reference] for more about what Korrel8r is and how to use it.
- link:https://pkg.go.dev/github.com/korrel8r/korrel8r[Go package documentation] for embedding Korrel8r in your own code.
- link:./doc/HACKING.adoc[Hackers guide] for experimenting and contributing to the code.
