// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// Class Full name of a class of data, format is DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain.
type Class = string

// Classes List of class names for a domain.
type Classes = []string

// Console State of the user's graphical console display (e.g. OpenShift web console).
type Console struct {
	// Search The troubleshooting panel displays the results of this correlation search.
	Search *Search `json:"search,omitempty" jsonschema:"The troubleshooting panel displays the results of this correlation search."`

	// View The main console view displays the results of this query.
	View Query `json:"view,omitempty" jsonschema:"Query for the main console view, in DOMAIN:CLASS:SELECTOR format."`
}

// Constraint Constrains the objects that will be included in search results.
type Constraint struct {
	// End Ignore objects with timestamps after this end time. Default: now.
	End *time.Time `json:"end,omitempty" jsonschema:"Ignore objects with timestamps after this end time. Default: now."`

	// Limit Limit total number of objects per query. Default: 100.
	Limit *int `json:"limit,omitempty" jsonschema:"Limit total number of objects per query. Default: 100."`

	// QueryLimit Limit total number of queries per class during traversal. Default: 10.
	QueryLimit *int `json:"queryLimit,omitempty" jsonschema:"Limit total number of queries per class during traversal. Default: 10."`

	// Start Ignore objects with timestamps before this start time. Default: 1 hour before end.
	Start *time.Time `json:"start,omitempty" jsonschema:"Ignore objects with timestamps before this start time. Default: 1 hour before end."`
}

// Domain Domain configuration information.
type Domain struct {
	// Description Brief description of the domain.
	Description string `json:"description,omitempty"`

	// Name Name of the domain.
	Name string `json:"name"`

	// Stores Stores configured for the domain.
	Stores []Store `json:"stores,omitempty"`
}

// Domains List of Korrel8r domains and configured stores.
type Domains = []Domain

// Edge Directed edge in the result graph, from Start to Goal classes.
type Edge struct {
	// Goal Class name of the goal node.
	Goal Class `json:"goal" jsonschema:"Class name of the goal node, in DOMAIN:CLASS format."`

	// Rules Set of rules followed along this edge.
	Rules []Rule `json:"rules,omitempty" jsonschema:"Set of rules followed along this edge."`

	// Start Class name of the start node.
	Start Class `json:"start" jsonschema:"Class name of the start node, in DOMAIN:CLASS format."`
}

// Empty Empty JSON object.
type Empty = map[string]interface{}

// Error Error result containing an error message.
type Error struct {
	// Error Error message.
	Error string `json:"error"`
}

// Goals Parameters for a goal-directed correlation search. Finds paths from start objects to goal classes.
type Goals struct {
	// Goals Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert
	Goals []Class `json:"goals" jsonschema:"Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Graph Graph resulting from a correlation search.
type Graph struct {
	// Edges List of graph edges.
	Edges []Edge `json:"edges,omitempty" jsonschema:"List of graph edges."`

	// Nodes List of graph nodes.
	Nodes []Node `json:"nodes,omitempty" jsonschema:"List of graph nodes."`
}

// Help Domain help documentation including query syntax and examples.
type Help struct {
	// Documentation Full documentation text for one or more domains.
	Documentation string `json:"documentation"`
}

// Neighbors Parameters for a neighborhood correlation search. Finds all objects reachable from the start by following correlation rules up to the maximum depth.
type Neighbors struct {
	// Depth Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only.
	Depth int `json:"depth" jsonschema:"Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Node Node in the result graph, contains results for a single class.
type Node struct {
	// Class Full class name.
	Class string `json:"class" jsonschema:"Full class name in DOMAIN:CLASS format."`

	// Count Number of results for this class, after de-duplication.
	Count *int `json:"count,omitempty" jsonschema:"Number of results for this class, after de-duplication."`

	// Queries Queries yielding results for this class.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries yielding results for this class."`

	// Result Serialized result contents, may be large.
	Result []Object `json:"result,omitempty" jsonschema:"Serialized result contents, may be large."`
}

// Nodes List of result nodes.
type Nodes = []Node

// Object Data object serialized as JSON.
type Object = json.RawMessage

// Objects List of data objects serialized as JSON.
type Objects = []Object

// Query Query for data objects, format is DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string.
type Query = string

// QueryCount Query with number of results.
type QueryCount struct {
	// Count Number of results, omitted if the query was not executed.
	Count *int `json:"count,omitempty" jsonschema:"Number of results, omitted if the query was not executed."`

	// Query Query for correlation data.
	Query Query `json:"query" jsonschema:"Query for correlation data in DOMAIN:CLASS:SELECTOR format."`

	// Statuses Statuses found on data objects for this query.
	Statuses []StatusCount `json:"statuses,omitempty"`
}

// Rule Rule is a correlation rule with a list of queries and results counts found during navigation.
type Rule struct {
	// Name Name is an optional descriptive name.
	Name string `json:"name" jsonschema:"Name is an optional descriptive name."`

	// Queries Queries generated while following this rule.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries generated while following this rule."`
}

// Search Correlation search parameters. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
type Search struct {
	// Goals Parameters for a goal-directed correlation search.
	Goals *Goals `json:"goals,omitempty" jsonschema:"Parameters for a goal-directed correlation search."`

	// Neighbors Parameters for a neighborhood correlation search.
	Neighbors *Neighbors `json:"neighbors,omitempty" jsonschema:"Parameters for a neighborhood correlation search."`
}

// Start Starting point for a correlation search. It usually specifies queries to get the starting objects, but can include serialized objects as well as/instead of queries.
type Start struct {
	// Class Class of starting objects. Required when using 'objects' to provide serialized objects. If queries are included, they must all be of this class.
	Class Class `json:"class,omitempty" jsonschema:"Class of starting objects in DOMAIN:CLASS format. Required when using objects. If queries are included, they must all be of this class."`

	// Constraint Constrains the objects that will be included in search results.
	Constraint *Constraint `json:"constraint,omitempty" jsonschema:"Constrains the objects that will be included in search results."`

	// Objects Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
	Objects []Object `json:"objects,omitempty" jsonschema:"Start objects serialized as JSON. Requires class to identify the object type."`

	// Queries Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point.
	Queries []Query `json:"queries,omitempty" jsonschema:"Queries for starting objects in DOMAIN:CLASS:SELECTOR format."`
}

// StatusCount Status with number of instances found.
type StatusCount struct {
	// Count Number of instances found, omitted if none.
	Count *int `json:"count,omitempty"`

	// Status Status for correlation data.
	Status string `json:"status"`
}

// Store Store is a map string keys and values used to connect to a store.
type Store map[string]string

// GraphOptions Options controlling the form of the returned graph.
type GraphOptions struct {
	// Errors If true include non-fatal error messages.
	Errors *bool `json:"errors,omitempty" jsonschema:"If true include non-fatal error messages."`

	// Results If true include full JSON results with each Query.
	Results *bool `json:"results,omitempty" jsonschema:"If true include full JSON results with each Query."`

	// Rules If true include rule names in graph edges.
	Rules *bool `json:"rules,omitempty" jsonschema:"If true include rule names in graph edges."`
}

// SetConfigParams defines parameters for SetConfig.
type SetConfigParams struct {
	// Verbose Verbose level for logging.
	Verbose *int `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// GraphGoalsParams defines parameters for GraphGoals.
type GraphGoalsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighborsParams defines parameters for GraphNeighbors.
type GraphNeighborsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighboursParams defines parameters for GraphNeighbours.
type GraphNeighboursParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// ObjectsParams defines parameters for Objects.
type ObjectsParams struct {
	// Query Query string.
	Query Query `form:"query" json:"query"`

	// Constraint Constrains the objects that will be included in results.
	Constraint *Constraint `form:"constraint,omitempty" json:"constraint,omitempty"`
}

// SetConsoleJSONRequestBody defines body for SetConsole for application/json ContentType.
type SetConsoleJSONRequestBody = Console

// ShowInConsoleJSONRequestBody defines body for ShowInConsole for application/json ContentType.
type ShowInConsoleJSONRequestBody = Console

// GraphGoalsJSONRequestBody defines body for GraphGoals for application/json ContentType.
type GraphGoalsJSONRequestBody = Goals

// GraphNeighborsJSONRequestBody defines body for GraphNeighbors for application/json ContentType.
type GraphNeighborsJSONRequestBody = Neighbors

// GraphNeighboursJSONRequestBody defines body for GraphNeighbours for application/json ContentType.
type GraphNeighboursJSONRequestBody = Neighbors

// ListGoalsJSONRequestBody defines body for ListGoals for application/json ContentType.
type ListGoalsJSONRequestBody = Goals

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dxrcxs3kn8FNXdVsuqGpOTsVVL85shary9+aE3nPpzl2wJnmiRWIDABMKS4Lv33q25gHhyC9OgZX+Iv",
	"iUXONLob/X7wS5LpZaEVKGeT8Zek4IYvwYGhv14ZXizeF05oRX/nYDMj6O9knIQvWKaVM1pKoebMLYDN",
	"tFkyPaN/G3ClUZCzOYIaJmkC14XUOSRjZ0pIE4GQfivBbJI0UXwJyTjR4cQ0sdkClvyhji6MLsA4AUQM",
	"GKNNhKzXM4aoMaEyWebAlFaDGXdcMnqDLcFaPgeLEN2mQISnWkvgKkmT64HmhRhkOoc5qAFcO8MHjs/p",
	"nH9arSqKbnHMzU2aGLCldD2wnZVSsv+avH/HwitsLdyCAc8W7O/I5gdGu8d5hH8poQf2+BhDKbBMKH9x",
	"DPKHZ/aBc24Q3XCUnv4TMpfcpIl1G4mfoIARQR40nXQmuY3Q9lfkDJ6BAslZhk/hP3PueEqSyh0Tlr18",
	"//bF63fjszcvJpNh9VfrxVwvuVDsGQznQ3b1k02Z1POULcEZkaWMSzAuZc7wDFKmwM2kXh8PGcELcPBK",
	"hCKt8NCGl4pUkS8LJOtTcvWTHV/oPEnpXy+hkHqzBOWGvChQEaWej3lRSJFxIi9N/Plj/78kTQiPMf0X",
	"NdnjMVbg1tpcJZ/TpODOgUHOfPrf8ef/GNN/m2u1zgg1p1ud6wF+OLBXohh4Y8DloNBCOTDecNyknu0x",
	"oXojrEPWeY77W55pU7NyuE26J3sCZiUySNKkIR6xFg6WkTPOatjsGXJXl666qMLATFwf71DWiBU3hm9u",
	"Q6lWViOyXSwmjjuo7F1pwRxZL8wi4xKNI77GcmELyTdBgt4XoCYLMXNsDdPqmWMvENsG0gI32QL/xaV8",
	"P0vGn74k/25gloyTfxs1bmMUVGE08c/ffE47aH5cAHNGl1MJdqG1Q2tdcAWyQs0Gg+0NCNEj0LgbA5Lk",
	"jXlchrdS+gc8FjV+JWDdnxlk+/bwgsSkuh0Eexih3yqz3Z90Op2E3sXOS9Hqte3OeHL+5vzs4/sPwS7t",
	"M4Moic5woVxEJarvPBX+Jfw3d2wtpGTT2v7meL7nbUVtxD+rPOIw5kqbBjj5GieWYB1fFpbxmQPjuQYq",
	"p2+G7CXMeCndmCm97hi+5PnJ6Y+Dkx8Hz08/nv44/uH5+PlPw9Mf/nL6/IfT/0nSxHMjGSc5dzBAcFGD",
	"1dsN3Rd7EkQpliLwn75KxqcnJ+mOEVwKx5zGgEKVyykYlKfq5AJMEKsG/unJiedOoA9t0BzMrQi826lE",
	"FX3xJkJaP8rwdQH+DG/489JQWGj4CozlcuvQR6L0tlj4UMJx424t6lOY4dckLQShKy+nbKFLUz0HKvc0",
	"P61I3wHLPabnJXnXXTb5z9G8zcS8NN5uC+XJFFrtGpat97vgfjYCZqz1WeVem9jhrgGLz266B74Lgd6h",
	"M0hItIkFOxP6vCYf8trqN8DqGOag90ZAdw5SKEX5rRQGcoypiNTPe2/xQND2C3nfn0xA3zKu8jZ1ng+9",
	"qQpSc/fY6zyfRy7tpTCQOcgpaWAhtPaezAdgKZsZvWQTL/KavdIYkPmIdVci55rL/qGFzzd2Q4tWTBrk",
	"CeEypXO4XfRwANBO5NAKGPZmeROgq6Vv2UxLqdeQMy41Ze3o7fI59L7SD6W8s5zehgs9sb4hmEtEvXCb",
	"Wm5qo/7Qd+qt6ENcagPp0K12NNvTlXqRjWn4uWdDVwboY18o8M+2rFzrZWO0ibxMFZGgX5lWjguFXpWr",
	"7WLJniLPPoCttzr2tkO0hxKjFvU6IvEXdRktZJ7IrkFeWY1IisH+KlRuWcHdwnrb4a+nDqO1V8LKhkTy",
	"tXkcl7bp2XPPKaPUsJPkh9qCz+n3Fwy2CwGfe2pxEPjHV+OHIb8TqfVMiOnxXaWmzykbRaJqh32XHPcr",
	"oHbU18tIRUlUotF9RaSIamReBfE8ElG+J0fv6GA+P1Sm6VT5ekkPeeUnEJ4ojshTtJpfpYke6k3TO53/",
	"DjQFHOMx999AFnsj7gXIguU6K5egXBV2Y3qP4kHZHLMb5fg1hXDBdESCny0Qe8qo28c4uPairhUwtOOY",
	"OoR48e4BekdTttGKaco7EPPFNNpD2LH/Kjy70PqQ+edS1hbfAM8WfCrB61rjsaebEI4go9uwfKhSFugs",
	"fN3nWizLJcuhcIuYx6AvdrF/G95r8totjB0U5I88Eh3sMLUr3IKdhv6LZd7rtUFYppXc3DsFfyI0/yCW",
	"39/1IctPBmg3P9X5ngwnBGK2Llh6UbdCzSV4l7ur7dmBZklTsB/eqybRAXYwZcl0GStmvqtlqk2crw8j",
	"4DQU63IY5GUdMgzvJ9B3PbQqn8XqG1QKFmDZRoAk0xyH3dtNUWn5jLj2BM6qN/ZNkzSWfxrBpfgX5O0c",
	"AqlK2ZJv2BSY5OYWKej7WmcePwnti/qOwntN26foB4KXcNDTRS83aRI4igY2z4V/6KJlODzfOnEIdzx4",
	"S2YbPnFLaeZuftnCJhkTm4cf+PqtTwKTGokDnMmbE+2eI59Afm5S39+J67pv+7Qx3ddsrps+j9R1brW9",
	"t5rPAeiFzlO2lW91gNuCK4K91ubqeMgqdMcBzsAWkImZyKpokzxFiHNizeZ7t5xbtm8P76n+rbp2POIG",
	"e7qdlOmlcA5yJnzRxpO65pYp7RhcQ1Y6yB/a8fQ+tu7c3L8z2ghvO4xDQb5r77MLp0/XkwIkV9p4rd1/",
	"w2a6VDmroFYGoXZJdcO2Z+Edod7Lo3ZNv7+RmOmn4ukOYfgpWge+k054geZMBgtYNbgwpatcMclyxZTQ",
	"71J8JeZ7+i8H+iCIg2IVkU0bZgUPEBb2O6FXMDUHBYajfqwXAjO0Oh8jAUDOfeMBVS8Kbnr3dSb1rEh3",
	"KKCb6rJmxHDIJoDGhGdObnwyP2NHVKI6Ys8cxjWIYHjPaVYb/FDPO8bs/6jKrfElXSD5Koec0aBh6Ac6",
	"jS4NM6Djg5XTfhbMF313Ldjtq763kt87gKdSVbtM0Y/AprLRg8ivlTbuR+NXoccrV5N4Tz2SNEdrmOy1",
	"Y6UtuZSbSujA1sbPaTYH1xQTEGAda01LxzKu6lHDVphYOQpu2RqkZNyOhLIOeN4yrTH5rJPmh2gm6dkO",
	"1kP2ISg5Wy9AsRJzeHYUvj1CggujVyJKzpC9bvkF0wz5pMihDVuW1lFhawrNjBUlbZfqMSzcXir31QGi",
	"xN+buFBdaM9L9by95p3IFd57yOoWjLznWcgAvS+lmmx1tyK5VHUrlh0RQ0kKRQ7KidmmhRBD2RmyFxLj",
	"fU6O3Gl2FO7syN/pRpeMSwM837AFx0cagrwYfmt5f3/2+AzrEHP6xTRoDGMqc5n4dGtMB40tSMicNpdJ",
	"rT8fUeqFl5Klto5lernUiq35pvHaG8Yb8MSXfUPI4y+XFGjYgmdwmYwvq2mwyyT139CHy82g0PllctO7",
	"5xgyj6cLsvax9C6jl+00YU9m0s0+0blwlVUJyx2y0A6ErbRQaQWRvLPOoPZiuS/FO9yDD0CjwSeNLu2t",
	"HX3ZnaaKzFD5/GfJi1BHYFew8XnOissSLCst5CjOmVaKVEuTRGsDkVEGxB6uySTJlzqLMKMedPrVgmGv",
	"SpFDkialkck4WThX2PFodBWeGc6FW5TTodD1RyMkQ6iZ9veoHPfls7BCc2E06X91yg7oADHTywZk9Y9d",
	"DtXIVvcGlumpBbPiUyGF2zAr5orLOjHUpcl8v52zX8opGAWObFVpHRiKrwIfrU+iqT2Ti9kMDChXT389",
	"k3puq8qQDaUhGwpPNm3Drk89/lqHzGk2LYXMMYSmJigVPiRlQ41TaGg2QARzZgGTF4dRkLUID0WZVl1K",
	"vMSQK5dK/FYC+9vHjxfsRekW2oh/+eMXwHOk/mxrWDFbcDVHYqoRbRR1SImVJF8Vq6gnRUGI1R7bAkyF",
	"i/cIYMMQpi4dJrqx85ldIJC6UxOsaw2IzLIUGSgLLZF6UfBsAez58ORWwjSaSj0d4W2O3rw+O383OScL",
	"LBzNX9dM/nA++cheXLxO0mQFxnqxW51yWSz4KdnoCuCg+f5keHo6/E+Eh3kfL0QyTn4YngxPfQVwQWo3",
	"8tODtN1WRqzdW52jd/J+DfLOJKkFh9bbhqKl1HO2AjPVVrjNMdMo36ZUNI1k/QqJ5x+aH4LwOvezZP7O",
	"CbFmxe5TF5n/JtjAJKxAknhJPZ8LNadyQmRXziMDW7tyoe/rh6eXQvk/TnZNNcaXBmyhVah3PT85qewJ",
	"hJi1KdCO0MfRYkh90sEZDRoEI0vYWd77xdfZyuWSmw0GmqQA+xjPHXKYxobRzpK//ZTUI6HJZwQ2ypod",
	"mTlEbvlDaPNijJKVhozMlr7hgWg4OJsavbY0wC3wqZXg7OLXj6w6YsjOFZ+iHeFzJBjNSS5spldoAjA4",
	"rrZx0KVIra9oVM3F5OIVyQUh/og3UR2x5y7S5C8nf3m4a6dZuchRSncYzldcSORkRxxegYtfUef+iabP",
	"N2lcrSeV5WxfsUabSNdGOTomBEz4K357dsGc1hJT+3/UV/1xAfRNkAVK9+oEwvJl4wqexUztMcbr+CiZ",
	"Nw9kv32o5YDs+M863zyFCHRKLiS8Rc6DKWxvkA2TdkgWeiJPbz/OOnttFba2zDKwdlZKufFSffL4Ui3U",
	"ikuRt6qaHWl+y69gn+BTDBkEMirc6PeqfCOIxWCq880gWP/wWdI2gSNYVdvcUUv4K7HLBxLOiPkcDORo",
	"+TwfmanCCArJarWwC73+h1BPrhrhts89UV+VNwfXznNgYJ0BvnwQHZlMzpkHx9YLMOCDPjrmqApgBci8",
	"mYnhlKYPQOH15ayS2TD7fKk6UoIHELjqGJpmisl5uJeDYrPPJl6UdkEFzxjgamqsi4q/6fCMsCwHKVYk",
	"M+GFjr8MwSrkZFZfnTeeM0hm3IHS9BV554Cdd6uEYF33p1QxZj8Xev1a/W4m9GwvQy0t8m3x6Ruxot4M",
	"IILu27GcTx+K1NLaVUi8OL5HRSobeG+T7dPc0Rf//5tR1uy0H4xim4Zsd8mdjG/oWORb2/7bGvNGWOcH",
	"eas9+q9kJrt7asgNQqOarp9ps7Vce/WTrbIWzMaapMW/v6MH7RymWwx6zEyl4sCB+PiPrQ/hPpV2vs4X",
	"Ccjx2rdkLvKjCpUuhPGDloTfRqKjG4C+1xZbdSRP3EfO7WOmWNURf1oRqocGe4pQu/7bmtyPSBCV6Oyo",
	"7tEX2sbSvabJ4Pf2ttanUgw2qzaeNpEupi+38daS1ZA1sunLhO3NMynDrpYEnrcWYtrH+hIxQWzivp0S",
	"AIJ+FdZyOhY4dhPNI6Otn2fyFvLhw54w7BCJiX27r7Wr1t1Re9JAx+8tfde/uP6dUQ27M+zgpfrAsmE1",
	"krAV54QGwC0jnaDFW8Moj6vJNO5Tx0RbcyTVlEdXwfWspdhUzfdAtGESrN/47Wj8FnJ79bsZqPkmdbw1",
	"79NHz5Gn9UV+1/JvUMu3pN3LNjc0nxn1UGIFKmyJPbiql11dLwxk3DUx/59G+8vv6v9d/f/46r8IS8MH",
	"073Z7lYvZZNSxlKDtLVZ3Cp4pFtrxun2nnFEGWmd+RGlk+D3aXhiNkTr03xKfXrixcEkCJ+uy0R35m7d",
	"8Sc4D8jVl1VB5w4lpHnFjP+v5aND1/7tFHDa8tYqqB8s3mC2/jtn3lXBoL0Z3/5RojD9uOC+ozsFvzcP",
	"eSwh31cgqtLvP3P+7JdCv7vWr7jWSh7rX8Sy9ehYGAjcGnF9AH/aGqGOGv1zv4zXWPe6gEpD0JujMJOH",
	"GrVVg4tsJvg5UfZSg1/0K8DQT2pztdnyy9wPo8X0qVqi/Yov+Ht7ZXPPbFP1534z32Pa9ya97w+Vtobn",
	"e/x4eWvkP71FZ7Ga+O/+1PRjOq7qqr4rfVzpG82iO07r3wppzEDrB83isRsCBLOqlMDPTY54IUb1cCPe",
	"cXhvz2wiqLlQ3QG52EDicEsOw4DcrgZ45fM9d7m7MD7squAuhFdhfXC3nmi3cKhM3i6En43I58Cm4NYA",
	"inH26tfXdVf22YfzycdjHxgo9uJ1mNl69vbs4nhb1agj//nm/wIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
