// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// Class Full name of a class of data, format is DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain.
type Class = string

// Classes List of class names for a domain.
type Classes = []string

// Console State of the user's graphical console display (e.g. OpenShift web console).
type Console struct {
	// Search The troubleshooting panel displays the results of this correlation search.
	Search *Search `json:"search,omitempty" jsonschema:"The troubleshooting panel displays the results of this correlation search."`

	// View The main console view displays the results of this query.
	View Query `json:"view,omitempty" jsonschema:"Query for the main console view, in DOMAIN:CLASS:SELECTOR format."`
}

// Constraint Constrains the objects that will be included in search results.
type Constraint struct {
	// End Ignore objects with timestamps after this end time.
	End *time.Time `json:"end,omitempty" jsonschema:"Ignore objects with timestamps after this end time."`

	// Limit Limit total number of objects per query.
	Limit *int `json:"limit,omitempty" jsonschema:"Limit total number of objects per query."`

	// Start Ignore objects with timestamps before this start time.
	Start *time.Time `json:"start,omitempty" jsonschema:"Ignore objects with timestamps before this start time."`
}

// Domain Domain configuration information.
type Domain struct {
	// Description Brief description of the domain.
	Description string `json:"description,omitempty"`

	// Name Name of the domain.
	Name string `json:"name"`

	// Stores Stores configured for the domain.
	Stores []Store `json:"stores,omitempty"`
}

// Domains List of Korrel8r domains and configured stores.
type Domains = []Domain

// Edge Directed edge in the result graph, from Start to Goal classes.
type Edge struct {
	// Goal Class name of the goal node.
	Goal Class `json:"goal" jsonschema:"Class name of the goal node, in DOMAIN:CLASS format."`

	// Rules Set of rules followed along this edge.
	Rules []Rule `json:"rules,omitempty" jsonschema:"Set of rules followed along this edge."`

	// Start Class name of the start node.
	Start Class `json:"start" jsonschema:"Class name of the start node, in DOMAIN:CLASS format."`
}

// Empty Empty JSON object.
type Empty = map[string]interface{}

// Error Error result containing an error message.
type Error struct {
	// Error Error message.
	Error string `json:"error"`
}

// Goals Parameters for a goal-directed correlation search. Finds paths from start objects to goal classes.
type Goals struct {
	// Goals Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert
	Goals []Class `json:"goals" jsonschema:"Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Graph Graph resulting from a correlation search.
type Graph struct {
	// Edges List of graph edges.
	Edges []Edge `json:"edges,omitempty" jsonschema:"List of graph edges."`

	// Nodes List of graph nodes.
	Nodes []Node `json:"nodes,omitempty" jsonschema:"List of graph nodes."`
}

// Neighbors Parameters for a neighborhood correlation search. Finds all objects reachable from the start by following correlation rules up to the maximum depth.
type Neighbors struct {
	// Depth Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only.
	Depth int `json:"depth" jsonschema:"Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Node Node in the result graph, contains results for a single class.
type Node struct {
	// Class Full class name.
	Class string `json:"class" jsonschema:"Full class name in DOMAIN:CLASS format."`

	// Count Number of results for this class, after de-duplication.
	Count *int `json:"count,omitempty" jsonschema:"Number of results for this class, after de-duplication."`

	// Queries Queries yielding results for this class.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries yielding results for this class."`

	// Result Serialized result contents, may be large.
	Result []Object `json:"result,omitempty" jsonschema:"Serialized result contents, may be large."`
}

// Nodes List of result nodes.
type Nodes = []Node

// Object Data object serialized as JSON.
type Object = json.RawMessage

// Objects List of data objects serialized as JSON.
type Objects = []Object

// Query Query for data objects, format is DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string.
type Query = string

// QueryCount Query with number of results.
type QueryCount struct {
	// Count Number of results, omitted if the query was not executed.
	Count *int `json:"count,omitempty" jsonschema:"Number of results, omitted if the query was not executed."`

	// Query Query for correlation data.
	Query Query `json:"query" jsonschema:"Query for correlation data in DOMAIN:CLASS:SELECTOR format."`

	// Statuses Statuses found on data objects for this query.
	Statuses []StatusCount `json:"statuses,omitempty"`
}

// Rule Rule is a correlation rule with a list of queries and results counts found during navigation.
type Rule struct {
	// Name Name is an optional descriptive name.
	Name string `json:"name" jsonschema:"Name is an optional descriptive name."`

	// Queries Queries generated while following this rule.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries generated while following this rule."`
}

// Search Correlation search parameters. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
type Search struct {
	// Goals Parameters for a goal-directed correlation search.
	Goals *Goals `json:"goals,omitempty" jsonschema:"Parameters for a goal-directed correlation search."`

	// Neighbors Parameters for a neighborhood correlation search.
	Neighbors *Neighbors `json:"neighbors,omitempty" jsonschema:"Parameters for a neighborhood correlation search."`
}

// Start Starting point for a correlation search. It usually specifies queries to get the starting objects, but can include serialized objects as well as/instead of queries.
type Start struct {
	// Class Class of starting objects. Required when using 'objects' to provide serialized objects. If queries are included, they must all be of this class.
	Class Class `json:"class,omitempty" jsonschema:"Class of starting objects in DOMAIN:CLASS format. Required when using objects. If queries are included, they must all be of this class."`

	// Constraint Constrains the objects that will be included in search results.
	Constraint *Constraint `json:"constraint,omitempty" jsonschema:"Constrains the objects that will be included in search results."`

	// Objects Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
	Objects []Object `json:"objects,omitempty" jsonschema:"Start objects serialized as JSON. Requires class to identify the object type."`

	// Queries Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point.
	Queries []Query `json:"queries,omitempty" jsonschema:"Queries for starting objects in DOMAIN:CLASS:SELECTOR format."`
}

// StatusCount Status with number of instances found.
type StatusCount struct {
	// Count Number of instances found, omitted if none.
	Count *int `json:"count,omitempty"`

	// Status Status for correlation data.
	Status string `json:"status"`
}

// Store Store is a map string keys and values used to connect to a store.
type Store map[string]string

// GraphOptions Options controlling the form of the returned graph.
type GraphOptions struct {
	// Errors If true include non-fatal error messages.
	Errors *bool `json:"errors,omitempty" jsonschema:"If true include non-fatal error messages."`

	// Results If true include full JSON results with each Query.
	Results *bool `json:"results,omitempty" jsonschema:"If true include full JSON results with each Query."`

	// Rules If true include rule names in graph edges.
	Rules *bool `json:"rules,omitempty" jsonschema:"If true include rule names in graph edges."`
}

// SetConfigParams defines parameters for SetConfig.
type SetConfigParams struct {
	// Verbose Verbose level for logging.
	Verbose *int `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// GraphGoalsParams defines parameters for GraphGoals.
type GraphGoalsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighborsParams defines parameters for GraphNeighbors.
type GraphNeighborsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighboursParams defines parameters for GraphNeighbours.
type GraphNeighboursParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// ObjectsParams defines parameters for Objects.
type ObjectsParams struct {
	// Query Query string.
	Query Query `form:"query" json:"query"`

	// Constraint Constrains the objects that will be included in results.
	Constraint *Constraint `form:"constraint,omitempty" json:"constraint,omitempty"`
}

// SetConsoleJSONRequestBody defines body for SetConsole for application/json ContentType.
type SetConsoleJSONRequestBody = Console

// GraphGoalsJSONRequestBody defines body for GraphGoals for application/json ContentType.
type GraphGoalsJSONRequestBody = Goals

// GraphNeighborsJSONRequestBody defines body for GraphNeighbors for application/json ContentType.
type GraphNeighborsJSONRequestBody = Neighbors

// GraphNeighboursJSONRequestBody defines body for GraphNeighbours for application/json ContentType.
type GraphNeighboursJSONRequestBody = Neighbors

// ListGoalsJSONRequestBody defines body for ListGoals for application/json ContentType.
type ListGoalsJSONRequestBody = Goals

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hxbc9s4lvBfQfH7qhzXUlKc7qpO6S3teLLZzsUTpfdh4+wURB5RGEMAA4ByNCn/961zAF5EQTJ9ibtr",
	"Oi+JLZEH536HvyWZXpVagXI2mX5LSm74ChwY+u2V4eXyfemEVvR7DjYzgn5Ppkn4gmVaOaOlFKpgbgls",
	"oc2K6QX9bMBVRkHOCgQ1TtIEvpZS55BMnakgTQRC+lKB2SRpovgKkmmiw4lpYrMlrPhDHV0aXYJxAogY",
	"MEabCFmvFwxRY0JlssqBKa1GC+64ZPQGW4G1vACLEN2mRITnWkvgKkmTryPNSzHKdA4FqBF8dYaPHC/o",
	"nH9arWqKbnHM9XWaGLCVdAOwXVRSsv+avX/HwivsSrglA54t2d+RzQ+M9oDzCP9KwgDs8TGGWmCZUF5w",
	"DPKHZ/aBc64R3XCUnv8TMpdcp4l1G4mfoIIRQR40nXQquY3Q9jfkDJ6BCslZhk/hjzl3PCVN5Y4Jy16+",
	"f/vi9bvp6ZsXs9m4/q3zYq5XXCj2BMbFmF0+tymTukjZCpwRWcq4BONS5gzPIGUK3ELqq+MxI3gBDopE",
	"KLIKD218ocgU+apEsj4ll8/t9FznSUo/vYRS6s0KlBvzskRDlLqY8rKUIuNEXpr486f+vyRNCI8p/YuW",
	"7PGYKnBX2lwmn9Ok5M6BQc58+t/p5/+Y0r+tWK0zQhUk1UKP8MORvRTlyDsDLkelFsqB8Y7jOvVsjynV",
	"G2Edss5z3Et5oU3DyvE26Z7sGZi1yCBJk5Z4xFo4WEXOOG1gsyfIXV25WlClgYX4erxDWatW3Bi+uQ2l",
	"WlmNyPaxmDnuoPZ3lQVzZL0yi4xLdI74GsuFLSXfBA16X4KaLcXCsSuY188ce4XYdpAWuMmW+BOX8v0i",
	"mX76lvx/A4tkmvy/SRs2JsEUJjP//PXntIfmxyUwZ3Q1l2CXWjv01iVXIGvUbHDY3oEQPQKduzEgSd+Y",
	"x2V8K6N/wGPR4tcCroYzg3zfHl6QmtTSQbCHEfpSu+3hpNPppPQudl6KXq/rd6azszdnpx/ffwh+aZ8b",
	"RE10hgvlIiZRf+ep8C/hz9yxKyElmzf+N8fzPW9raiPxWeWRgFEobVrgFGucWIF1fFVaxhcOjOcaqJy+",
	"2bL25NnTk19GT38ZPTv5ePLL9Kdn02fPxyc//Xzy7KeT/0nSxFOfTJOcOxjh61EHNTjs3AFb5LsUK+Fi",
	"jm0lHHMakwRVreZgUEdq6CWYVlUCzuhHCjC3QnrwKRQGHTfu1mKawwK/JsoJQiOpxxXAPjziyv+S/Psu",
	"sf5zNLCFKCrjPYdQnhSh1a5qb73fB/erEbBgnc9qB99Gr7uGTJ9f9w98F1KNQ2eQqLWJhdsZfd6QD3nj",
	"d1pgTRQ9GD8Q0J3DJCXJXyphIMeoTqR+3ivFA2nDb+T/n5uAvmVc5V3qPB8GUxW05u7R/ywvIkJ7KQxk",
	"DnJKW1lI7rwv9SlAyhZGr9jMq7VmrzSmBD5n2tXIQnM5PLj5jHc3uHWyoqBPCJcpncPt4tcBQDuxqxOy",
	"9tYZMyDR0rdsoaXUV5AzLjXVjeh/8wIGi/RDJe+sp7fhwkCsrwnmClEv3abRm8Y1P7RMvad8CKG2kA5J",
	"tWfZnq7Uq2zMws88G/o6QB/7UtU/2/FynZex+I68TDV5sK9MK8eFwnySq+1yfU+bYR/Azls9f9sj2kOJ",
	"UYt2HdH486aRE2ofZNcor71GJMllfxMqt6zkbmm97/DiaRI57Y2w9iGRiqGI49J1PXvknDIqTnplZqhu",
	"fVW5v2TdLkU/D7TioPDf34wfhvxevjWwJKPHd42aPqd6CIlqAvZdqqwbQO2Yr9eRmpKoRmP4imgRdWm8",
	"CeJ5pKJ8T5XYs8G8ONQo6PWZBmkPReVHUJ4ojshT9Jo30kQPDabpnc7/AJoCjvGc+x2IYjmP9ml3PJwK",
	"zy61PuTguJSNTzPAsyWfS/Da1Mak+SYEXNS0LiwfjKsS3aGvrb+KVbViOZRuGfOJ9MUu9m/De22FtYWx",
	"g5I8rkeih92YvUSg7CT0uC3zfr0LwjKt5MYjdI9i8JHQ/DfxbV7Wh3wbmdhuBabzPTl8SDVs0xTyqm6F",
	"KiT4oLLr7rIDDem2KTq+V2XdA3YwKc90FWsYvWt0qkuc78Eh4DQ0SHIY5VUTFO/Z3bjroUjHlwpMrIKn",
	"dpsAyzYCZI76Eoc92BFT++6UuPYI7ngw9u0gKlZhGcGl+Bfk3SwZqUrZim/YHJjk5hZF1vvGZr5/mTUU",
	"9R2D95a2z9APhOdw0OPF5+s0CRxFB5vnwj903nEcnm+9NgN3PERLZls+cUuF1G4F1cEmmRKbxx/41Vtf",
	"5iQNEgc4k7cn2j1HPoL+XKe+hx63dd9a72K6b6DXNNa/02SvM1rcGvAFoOc6T9lWRdEDbkuuCPaVNpfH",
	"Y1ajOw1wRraETCxE5pu+zEeKkOfEBnr3Hut1fN8e3lMXV/X9eCQMDgw7KdMr4bAqFr4t4Um94pYp7Rh8",
	"haxykD904Bl8bB16NvefPrXK203jUJHvOl/qwxkyWaIEyVU23k3237CFrlTOaqi1Q2hCUjPpGNhaRqj3",
	"iqh91+8lEnP91B7cIQw/Re/Ad8oJr9CcyeABQ5pBfec6FJMu10zJK7QppvhaFHsmDAc6/YiDYjWR7aBh",
	"DQ+QFg47YVAyVYACw9E+rpYCK7SmHiMFQM79yROqQRRcD55czJp5fH/w2i91WbvGNWYzQGfCMyc3TCsK",
	"GUfUhDliTxzmNYhgeM9p1jj80LE6Ztqwo7q2xpd0ieSrHHJGy1xh4uU0hjSsgI4P9gaHeTDf1tz1YLfv",
	"a95Kf+8Anpox3TbFMALbzsYAIm9qbdyPxhuhx3szs/jsN1I0R7t07LVjla24lJta6cA2zs9pVoBrmwkI",
	"sMm15pVjGVfNOlcnTawDBbfsCqRk3E6Esg543nGtMf1siuaHGJfoxQ7WY/YhGDm7WoJiFdbw7Ch8e4QE",
	"l0avRZScMXvdiQumXaRIkUMbtqqso8bWHNo9FiraLtT38HB7qdzXB4gSf2/iQnehu5MyUHrtOxER3nuR",
	"5RaMvOdZyAC9r6Sabc1vIrVULRXLjoihpIUiB+XEYtNBiKHujNkLifk+p0DuNDsKMjvyMt3oinFpgOcb",
	"tuT4SEuQV8M/W90/nD2+wjrEnGE5DTrDmMlcJL7cmtJBUwsSMqfNRdLYz0fUeuG1ZKWtY5lerbRiV3zT",
	"Ru0N4y144su+Rc/ptwtKNGzJM7hIphdJDgteSXeRpP4b+nC1GZU6v0iuB0/VQuXxeEnWPpbeZb2tWybs",
	"qUz61ScGF66yumC5QxXag7BVFiqtIFJ3NhXUXiz3lXiHp8wBaDT5pOWcvb2jb7v7QpEtIV//rHgZ+gjs",
	"Eja+zllzWYFllYUc1TnTSpFpadJobSAyrEfs4Su5JPlSZxFmNKs8v1sw7FUlckjSpDIymSZL50o7nUwu",
	"wzPjQrhlNR8L3Xw0QTKEWmgvR+W4b5+FawrnRpP916fsgA4QM71qQdY/7HKoQbaWG1im5xbMms+FFG7D",
	"rCgUl01hqCuT+YkyZ79VczAKHPmqyjowlF8FPlpfRNN4JheLBRhQrtlveiJ1YevOkA2tIRsaTzbtwm5O",
	"Pb5pQuY0m1dC5phC05iPGh+SqqE2KLQ0GyCCObOAxYvDLMhahIeqTNcJKhRiqJUrJb5UwP7z48dz9qJy",
	"S23Ev/zxS+A5Un+6tY6XLbkqkJh6DRZVHVJiJelXzSqaSVESYrXHtgRT4+IjAtiwSqgrh4Vu7Hxmlwik",
	"mdQE79oAIrcsRQbKQkelXpQ8WwJ7Nn56K2WazKWeT1CakzevT8/ezc7IAwtHO68Nkz+czT6yF+evkzRZ",
	"g7Fe7dYnXJZLfkI+ugY4ar9/Oj45GZ+MclgjTKz9eCmSafLT+On4xHcBl2R6E78jR7eIqojHe6tzjFA+",
	"tkHe25e04NCD29C4lLpgazBzbYXbHDONOm4qRTs31q/qex6iCyIIr3O/MeXlToi1V5k+9ZH5b4INTMIa",
	"JKmY1EUhVEEthcidJI8MbN1JCrPfZHryNE1WQvlfnu66a8wxDdhSq9Dzevb0ae1TIOStbZN2gnGOFvCb",
	"kw5uItC6E3nD3iWp33yvrVqtuNlgsklGsI/x3CGH60VcH3M/Jc3iY/IZgU2y9i5CVMqz2phaK2NWo5nw",
	"Ap0Olm2YIzLh2Fpw9vb0nDmtJVZ7/wivYbYD9E0mBb5EFUCTU1q+ar3Dk5j1HWMKh4+Sxnsg+9WF6PGB",
	"EKz7VeebB5NNDT0inV4VTjc4ypwHy+he3Bgn3Sgd2uSPr06nveskNba2yjKwdlFJSYnfzw+JDK29RZAR",
	"as2lyDuNrp6uv+WXfTXkay4kLXu4ViF7uk7S+oyusE5Bg1qM5jrfjIIzCJ8lXYuYwLq+RFlAxDB+J3b5",
	"2OKMKArAanhe85GZOrJQlG7Mwi711T+EenTTCNI+80TdqG8OvjrPgZF1BvjqQWxkNjtjHhyWmAZ8HkDH",
	"HNU5jQCZt2sSnCq3ESgUX85qnQ0LnxeqpyV4AIGrj6EFl5ieB7kcVBtSB59VTb75/68nWXtNLaoXH8Ju",
	"TNv/799bI8GGBlm+dYFvW2RvhHV+27y+GndDENxd/EfLIDTqdcWFNlv3Zy6f2zpAYuBv46N/f8dTdcNl",
	"v/b4nkGx5sCesPgHeik8+ufvf3SQp9LOl5U9xX8VeqtbOhe5J1nreJh2dTT8NhodvVLhW7uxuyNk5UP0",
	"fIBjujtr6yP+sirU7KgMVKFuu8Hzbp8GUUVoJ81IqNQ2lkq2PS1/EWJrHz3FQFZ3jbWJNM19dcc7W+tY",
	"v9W66avS7iq/lGH5XQLPOxvG3WN9R4IgtjGlr6C0qfwq7Dn3PHBMEu0jk62/uOA95MNnpWG2Fom3vrvc",
	"Wf7vL/0/airqF8F/2F/c/k6pZdKbrXmtPnB7o56AbeUvod90y8Q3WPHW7PP7WjJNl5ucaGtsWQ8V+wau",
	"Fx3DpuaRB4IVP1h/hapn8VvI7bXvdn77p7Txznh5iJ0jTxtB/rDyP6GVb2m7121uaB0oGqHEGlS4lPDg",
	"pl71bb00kHHX5vx/Geuvfpj/D/P/9zd/TPH/4HS9rjK6t7e6V8PDhH7JfYt5Dv5uF1aUu1n8vqqyztn/",
	"ykm3v7jwwx5vsMdaH5u/S2Cb8WYYWm+tYTyAEXbWfKJtlzO/MN7OHJuuCy3qbI7C3Bgtaqtwj2zP+V0G",
	"9lKDX0YvwdCf1uNqs1VucD8wjdlTfdHjhh7k37vXCvbM3upf97cWB2ykXKf3/YNFnQWvAX/EsLOWlt6i",
	"E15vpfX/5Nz3bJbWovph9HGjby2LZJw291lbN9D5sxLxrhcCBLOujcDP9ie8FJNmAI8yDu/tmZ2DKoTq",
	"D3BjA/Pxlh6GAe6uBXjj89vNcvdS07hvgrsQXoUV990mhN3CoXZ5uxB+NSIvgM3BXQEoxtmr3183M5gn",
	"H85mH499YqDYi9dhiPzk7en58bap0QTp8/X/BQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
