// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// Class Full name of a class of data, format is DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain.
type Class = string

// Classes List of class names for a domain.
type Classes = []string

// Console State of the user's graphical console display (e.g. OpenShift web console).
type Console struct {
	// Search The troubleshooting panel displays the results of this correlation search.
	Search *Search `json:"search,omitempty" jsonschema:"The troubleshooting panel displays the results of this correlation search."`

	// View The main console view displays the results of this query.
	View Query `json:"view,omitempty" jsonschema:"Query for the main console view, in DOMAIN:CLASS:SELECTOR format."`
}

// Constraint Constrains the objects that will be included in search results.
type Constraint struct {
	// End Ignore objects with timestamps after this end time. Default: now.
	End *time.Time `json:"end,omitempty" jsonschema:"Ignore objects with timestamps after this end time. Default: now."`

	// Limit Limit total number of objects per query. Default: 100.
	Limit *int `json:"limit,omitempty" jsonschema:"Limit total number of objects per query. Default: 100."`

	// QueryLimit Limit total number of queries per class during traversal. Default: 10.
	QueryLimit *int `json:"queryLimit,omitempty" jsonschema:"Limit total number of queries per class during traversal. Default: 10."`

	// Start Ignore objects with timestamps before this start time. Default: 1 hour before end.
	Start *time.Time `json:"start,omitempty" jsonschema:"Ignore objects with timestamps before this start time. Default: 1 hour before end."`
}

// Domain Domain configuration information.
type Domain struct {
	// Description Brief description of the domain.
	Description string `json:"description,omitempty"`

	// Name Name of the domain.
	Name string `json:"name"`

	// Stores Stores configured for the domain.
	Stores []Store `json:"stores,omitempty"`
}

// Domains List of Korrel8r domains and configured stores.
type Domains = []Domain

// Edge Directed edge in the result graph, from Start to Goal classes.
type Edge struct {
	// Goal Class name of the goal node.
	Goal Class `json:"goal" jsonschema:"Class name of the goal node, in DOMAIN:CLASS format."`

	// Rules Set of rules followed along this edge.
	Rules []Rule `json:"rules,omitempty" jsonschema:"Set of rules followed along this edge."`

	// Start Class name of the start node.
	Start Class `json:"start" jsonschema:"Class name of the start node, in DOMAIN:CLASS format."`
}

// Empty Empty JSON object.
type Empty = map[string]interface{}

// Error Error result containing an error message.
type Error struct {
	// Error Error message.
	Error string `json:"error"`
}

// Goals Parameters for a goal-directed correlation search. Finds paths from start objects to goal classes.
type Goals struct {
	// Goals Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert
	Goals []Class `json:"goals" jsonschema:"Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Graph Graph resulting from a correlation search.
type Graph struct {
	// Edges List of graph edges.
	Edges []Edge `json:"edges,omitempty" jsonschema:"List of graph edges."`

	// Nodes List of graph nodes.
	Nodes []Node `json:"nodes,omitempty" jsonschema:"List of graph nodes."`
}

// Help Domain help documentation including query syntax and examples.
type Help struct {
	// Documentation Full documentation text for one or more domains.
	Documentation string `json:"documentation"`
}

// Neighbors Parameters for a neighborhood correlation search. Finds all objects reachable from the start by following correlation rules up to the maximum depth.
type Neighbors struct {
	// Depth Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only.
	Depth int `json:"depth" jsonschema:"Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Node Node in the result graph, contains results for a single class.
type Node struct {
	// Class Full class name.
	Class string `json:"class" jsonschema:"Full class name in DOMAIN:CLASS format."`

	// Count Number of results for this class, after de-duplication.
	Count *int `json:"count,omitempty" jsonschema:"Number of results for this class, after de-duplication."`

	// Queries Queries yielding results for this class.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries yielding results for this class."`

	// Result Serialized result contents, may be large.
	Result []Object `json:"result,omitempty" jsonschema:"Serialized result contents, may be large."`
}

// Nodes List of result nodes.
type Nodes = []Node

// Object Data object serialized as JSON.
type Object = json.RawMessage

// Objects List of data objects serialized as JSON.
type Objects = []Object

// Query Query for data objects, format is DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string.
type Query = string

// QueryCount Query with number of results.
type QueryCount struct {
	// Count Number of results, omitted if the query was not executed.
	Count *int `json:"count,omitempty" jsonschema:"Number of results, omitted if the query was not executed."`

	// Query Query for correlation data.
	Query Query `json:"query" jsonschema:"Query for correlation data in DOMAIN:CLASS:SELECTOR format."`

	// Statuses Statuses found on data objects for this query.
	Statuses []StatusCount `json:"statuses,omitempty"`
}

// Rule Rule is a correlation rule with a list of queries and results counts found during navigation.
type Rule struct {
	// Name Name is an optional descriptive name.
	Name string `json:"name" jsonschema:"Name is an optional descriptive name."`

	// Queries Queries generated while following this rule.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries generated while following this rule."`
}

// Search Correlation search parameters. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
type Search struct {
	// Goals Parameters for a goal-directed correlation search.
	Goals *Goals `json:"goals,omitempty" jsonschema:"Parameters for a goal-directed correlation search."`

	// Neighbors Parameters for a neighborhood correlation search.
	Neighbors *Neighbors `json:"neighbors,omitempty" jsonschema:"Parameters for a neighborhood correlation search."`
}

// Start Starting point for a correlation search. It usually specifies queries to get the starting objects, but can include serialized objects as well as/instead of queries.
type Start struct {
	// Class Class of starting objects. Required when using 'objects' to provide serialized objects. If queries are included, they must all be of this class.
	Class Class `json:"class,omitempty" jsonschema:"Class of starting objects in DOMAIN:CLASS format. Required when using objects. If queries are included, they must all be of this class."`

	// Constraint Constrains the objects that will be included in search results.
	Constraint *Constraint `json:"constraint,omitempty" jsonschema:"Constrains the objects that will be included in search results."`

	// Objects Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
	Objects []Object `json:"objects,omitempty" jsonschema:"Start objects serialized as JSON. Requires class to identify the object type."`

	// Queries Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point.
	Queries []Query `json:"queries,omitempty" jsonschema:"Queries for starting objects in DOMAIN:CLASS:SELECTOR format."`
}

// StatusCount Status with number of instances found.
type StatusCount struct {
	// Count Number of instances found, omitted if none.
	Count *int `json:"count,omitempty"`

	// Status Status for correlation data.
	Status string `json:"status"`
}

// Store Store is a map string keys and values used to connect to a store.
type Store map[string]string

// GraphOptions Options controlling the form of the returned graph.
type GraphOptions struct {
	// Errors If true include non-fatal error messages.
	Errors *bool `json:"errors,omitempty" jsonschema:"If true include non-fatal error messages."`

	// Results If true include full JSON results with each Query.
	Results *bool `json:"results,omitempty" jsonschema:"If true include full JSON results with each Query."`

	// Rules If true include rule names in graph edges.
	Rules *bool `json:"rules,omitempty" jsonschema:"If true include rule names in graph edges."`
}

// SetConfigParams defines parameters for SetConfig.
type SetConfigParams struct {
	// Verbose Verbose level for logging.
	Verbose *int `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// GraphGoalsParams defines parameters for GraphGoals.
type GraphGoalsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighborsParams defines parameters for GraphNeighbors.
type GraphNeighborsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighboursParams defines parameters for GraphNeighbours.
type GraphNeighboursParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// ObjectsParams defines parameters for Objects.
type ObjectsParams struct {
	// Query Query string.
	Query Query `form:"query" json:"query"`

	// Constraint Constrains the objects that will be included in results.
	Constraint *Constraint `form:"constraint,omitempty" json:"constraint,omitempty"`
}

// SetConsoleJSONRequestBody defines body for SetConsole for application/json ContentType.
type SetConsoleJSONRequestBody = Console

// ShowInConsoleJSONRequestBody defines body for ShowInConsole for application/json ContentType.
type ShowInConsoleJSONRequestBody = Console

// GraphGoalsJSONRequestBody defines body for GraphGoals for application/json ContentType.
type GraphGoalsJSONRequestBody = Goals

// GraphNeighborsJSONRequestBody defines body for GraphNeighbors for application/json ContentType.
type GraphNeighborsJSONRequestBody = Neighbors

// GraphNeighboursJSONRequestBody defines body for GraphNeighbours for application/json ContentType.
type GraphNeighboursJSONRequestBody = Neighbors

// ListGoalsJSONRequestBody defines body for ListGoals for application/json ContentType.
type ListGoalsJSONRequestBody = Goals

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hxbcxu3kvBfQc33VcmqHZKSk6qk+ObIOj7e+KJjOvuwlvcUONMkcQQCEwBDisel/77VDcyFQ5AeXeNN",
	"/JJY5Eyju9H3C78kmV4WWoFyNhl/SQpu+BIcGPrrleHF4n3hhFb0dw42M4L+TsZJ+IJlWjmjpRRqztwC",
	"2EybJdMz+rcBVxoFOZsjqGGSJnBdSJ1DMnamhDQRCOn3EswmSRPFl5CMEx1OTBObLWDJH+rowugCjBNA",
	"xIAx2kTIej1jiBoTKpNlDkxpNZhxxyWjN9gSrOVzsAjRbQpEeKq1BK6SNLkeaF6IQaZzmIMawLUzfOD4",
	"nM75l9WqougWx9zcpIkBW0rXA9tZKSX7z8n7dyy8wtbCLRjwbMH+gWx+YLR7nEf4lxJ6YI+PMZQCy4Ty",
	"F8cgf3hmHzjnBtENR+npvyBzyU2aWLeR+AkKGBHkQdNJZ5LbCG1/Q87gGSiQnGX4FP4z546nJKncMWHZ",
	"y/dvX7x+Nz5782IyGVZ/tV7M9ZILxZ7BcD5kVz/blEk9T9kSnBFZyrgE41LmDM8gZQrcTOr18ZARvAAH",
	"r0Qo0goPbXipSBX5skCyPiVXP9vxhc6TlP71EgqpN0tQbsiLAhVR6vmYF4UUGSfy0sSfP/b/S9KE8BjT",
	"f1GTPR5jBW6tzVXyOU0K7hwY5Myn/xl//o8x/be5VuuMUHO61bke4IcDeyWKgTcGXA4KLZQD4w3HTerZ",
	"HhOqN8I6ZJ3nuL/lmTY1K4fbpHuyJ2BWIoMkTRriEWvhYBk546yGzZ4hd3XpqosqDMzE9fEOZY1YcWP4",
	"5jaUamU1ItvFYuK4g8relRbMkfXCLDIu0TjiaywXtpB8EyTofQFqshAzx9YwrZ459gKxbSAtcJMt8F9c",
	"yvezZPzpS/L/DcyScfL/Ro3bGAVVGE388zef0w6aHxfAnNHlVIJdaO3QWhdcgaxQs8FgewNC9Ag07saA",
	"JHljHpfhrZT+AY9FjV8JWPdnBtm+PbwgMaluB8EeRuj3ymz3J51OJ6F3sfNStHptuzOenL85P/v4/kOw",
	"S/vMIEqiM1woF1GJ6jtPhX8J/80dWwsp2bS2vzme73lbURvxzyqPOIy50qYBTr7GiSVYx5eFZXzmwHiu",
	"gcrpmyF7CTNeSjdmSq87hi95fnL60+Dkp8Hz04+nP41/eD5+/vPw9IcfT5//cPrfSZp4biTjJOcOBggu",
	"arB6u6H7Yk+CKMVSBP7TV8n49OQk3TGCS+GY0xhQqHI5BYPyVJ1cgAli1cA/PTnx3An0oQ2ag7kVgXc7",
	"laiiL95ESOtHGb4uwJ/hDX9eGgoLDV+BsVxuHfpIlN4WCx9KOG7crUV9CjP8mqSFIHTl5ZQtdGmq50Dl",
	"nuanFek7YLnH9Lwk77rLJv85mreZmJfG222hPJlCq13DsvV+F9wvRsCMtT6r3GsTO9w1YPHZTffAdyHQ",
	"O3QGCYk2sWBnQp/X5ENeW/0GWB3DHPTeCOjOQQqlKL+XwkCOMRWR+nnvLR4I2n4l7/uzCehbxlXeps7z",
	"oTdVQWruHnud5/PIpb0UBjIHOSUNLITW3pP5ACxlM6OXbOJFXrNXGgMyH7HuSuRcc9k/tPD5xm5o0YpJ",
	"gzwhXKZ0DreLHg4A2okcWgHD3ixvAnS19C2baSn1GnLGpaasHb1dPofeV/qhlHeW09twoSfWNwRziagX",
	"blPLTW3UH/pOvRV9iEttIB261Y5me7pSL7IxDT/3bOjKAH3sCwX+2ZaVa71sjDaRl6kiEvQr08pxodCr",
	"crVdLNlT5NkHsPVWx952iPZQYtSiXkck/qIuo4XME9k1yCurEUkx2N+Eyi0ruFtYbzv89dRhtPZKWNmQ",
	"SL42j+PSNj177jlllBp2kvxQW/A5/f6CwXYh4HNPLQ4C//hq/DDkdyK1ngkxPb6r1PQ5ZaNIVO2w75Lj",
	"fgXUjvp6GakoiUo0uq+IFFGNzKsgnkciyvfk6B0dzOeHyjSdKl8v6SGv/ATCE8UReYpW86s00UO9aXqn",
	"8z+ApoBjPOb+O8hib8S9AFmwXGflEpSrwm5M71E8KJtjdqMcv6YQLpiOSPCzBWJPGXX7GAfXXtS1AoZ2",
	"HFOHEC/ePUDvaMo2WjFNeQdivphGewg79l+FZxdaHzL/XMra4hvg2YJPJXhdazz2dBPCEWR0G5YPVcoC",
	"nYWv+1yLZblkORRuEfMY9MUu9m/De01eu4Wxg4L8kUeigx2mdoVbsNPQf7HMe702CMu0kpt7p+BPhOaf",
	"xPL7uz5k+ckA7eanOt+T4YRAzNYFSy/qVqi5BO9yd7U9O9AsaQr2w3vVJDrADqYsmS5jxcx3tUy1ifP1",
	"YQSchmJdDoO8rEOG4f0E+q6HVuWzWH2DSsECLNsIkGSa47B7uykqLZ8R157AWfXGvmmSxvJPI7gU/4a8",
	"nUMgVSlb8g2bApPc3CIFfV/rzOMnoX1R31F4r2n7FP1A8BIOerro5SZNAkfRwOa58A9dtAyH51snDuGO",
	"B2/JbMMnbinN3M0vW9gkY2Lz8ANfv/VJYFIjcYAzeXOi3XPkE8jPTer7O3Fd922fNqb7ms110+eRus6t",
	"tvdW8zkAvdB5yrbyrQ5wW3BFsNfaXB0PWYXuOMAZ2AIyMRNZFW2SpwhxTqzZfO+Wc8v27eE91b9V145H",
	"3GBPt5MyvRTOQc6EL9p4UtfcMqUdg2vISgf5Qzue3sfWnZv7d0Yb4W2HcSjId+19duH06XpSgORKG6+1",
	"+2/YTJcqZxXUyiDULqlu2PYsvCPUe3nUrun3NxIz/VQ83SEMP0XrwHfSCS/QnMlgAasGF6Z0lSsmWa6Y",
	"Evpdiq/EfE//5UAfBHFQrCKyacOs4AHCwn4n9Aqm5qDAcNSP9UJghlbnYyQAyLlvPKDqRcFN777OpJ4V",
	"6Q4FdFNd1owYDtkE0JjwzMmNT+Zn7IhKVEfsmcO4BhEM7znNaoMf6nnHmP0fVbk1vqQLJF/lkDMaNAz9",
	"QKfRpWEGdHywctrPgvmi764Fu33V91byewfwVKpqlyn6EdhUNnoQ+bXSxv1o/Cr0eOVqEu+pR5LmaA2T",
	"vXastCWXclMJHdja+DnN5uCaYgICrGOtaelYxlU9atgKEytHwS1bg5SM25FQ1gHPW6Y1Jp910vwQzSQ9",
	"28F6yD4EJWfrBShWYg7PjsK3R0hwYfRKRMkZstctv2CaIZ8UObRhy9I6KmxNoZmxoqTtUj2GhdtL5b46",
	"QJT4exMXqgvteamet9e8E7nCew9Z3YKR9zwLGaD3pVSTre5WJJeqbsWyI2IoSaHIQTkx27QQYig7Q/ZC",
	"YrzPyZE7zY7CnR35O93oknFpgOcbtuD4SEOQF8NvLe/vzx6fYR1iTr+YBo1hTGUuE59ujemgsQUJmdPm",
	"Mqn15yNKvfBSstTWsUwvl1qxNd80XnvDeAOe+LJvCHn85ZICDVvwDC6T8WU1DXaZpP4b+nC5GRQ6v0xu",
	"evccQ+bxdEHWPpbeZfSynSbsyUy62Sc6F66yKmG5QxbagbCVFiqtIJJ31hnUXiz3pXiHe/ABaDT4pNGl",
	"vbWjL7vTVJEZKp//LHkR6gjsCjY+z1lxWYJlpYUcxTnTSpFqaZJobSAyyoDYwzWZJPlSZxFm1INOv1kw",
	"7FUpckjSpDQyGScL5wo7Ho2uwjPDuXCLcjoUuv5ohGQINdP+HpXjvnwWVmgujCb9r07ZAR0gZnrZgKz+",
	"scuhGtnq3sAyPbVgVnwqpHAbZsVccVknhro0me+3c/ZrOQWjwJGtKq0DQ/FV4KP1STS1Z3Ixm4EB5erp",
	"r2dSz21VGbKhNGRD4cmmbdj1qcdf65A5zaalkDmG0NQEpcKHpGyocQoNzQaIYM4sYPLiMAqyFuGhKNOq",
	"S4mXGHLlUonfS2B///jxgr0o3UIb8W9//AJ4jtSfbQ0rZguu5khMNaKNog4psZLkq2IV9aQoCLHaY1uA",
	"qXDxHgFsGMLUpcNEN3Y+swsEUndqgnWtAZFZliIDZaElUi8Kni2APR+e3EqYRlOppyO8zdGb12fn7ybn",
	"ZIGFo/nrmskfzicf2YuL10marMBYL3arUy6LBT8lG10BHDTfnwxPT4c/IjzM+3ghknHyw/BkeOorgAtS",
	"u5GfHqTttjJi7d7qHL2T92uQdyZJLTi03jYULaWesxWYqbbCbY6ZRvk2paJpJOtXSDz/0PwQhNe5nyXz",
	"d06INSt2n7rI/BfBBiZhBZLES+r5XKg5lRMiu3IeGdjalQt9Xz88vRTK/3Gya6oxvjRgC61Cvev5yUll",
	"TyDErE2BdoQ+jhZD6pMOzmjQIBhZws7y3q++zlYul9xsMNAkBdjHeO6QwzQ2jHaW/O2npB4JTT4jsFHW",
	"7MjMIXLLH0KbF2OUrDRkZLb0DQ9Ew8HZ1Oi1pQFugU+tBGcXv31k1RFDdq74FO0InyPBaE5yYTO9QhOA",
	"wXG1jYMuRWp9RaNqLiYXr0guCPFHvInqiD13kSY/nvz4cNdOs3KRo5TuMJyvuJDIyY44vAIXv6LO/RNN",
	"n2/SuFpPKsvZvmKNNpGujXJ0TAiY8Ff89uyCOa0lpvb/rK/64wLomyALlO7VCYTly8YVPIuZ2mOM1/FR",
	"Mm8eyH77UMsB2fFfdL55ChHolFxIeIucB1PY3iAbJu2QLPREnt5+nHX22ipsbZllYO2slHLjpfrk8aVa",
	"qBWXIm9VNTvS/JZfwT7BpxgyCGRUuNHvVflGEIvBVOebQbD+4bOkbQJHsKq2uaOW8Ddilw8knBHzORjI",
	"0fJ5PjJThREUktVqYRd6/U+hnlw1wm2fe6K+Km8Orp3nwMA6A3z5IDoymZwzD46tF2DAB310zFEVwAqQ",
	"eTMTwylNH4DC68tZJbNh9vlSdaQEDyBw1TE0zRST83AvB8Vmn028KO2CCp4xwNXUWBcVf9PhGWFZDlKs",
	"SGbCCx1/GYJVyMmsvjpvPGeQzLgDpekr8s4BO+9WCcG67k+pYsx+LvT6tfrDTOjZXoZaWuTb4tM3YkW9",
	"GUAE3bdjOZ8+FKmltauQeHF8j4pUNvDeJtunuaMv/v83o6zZaT8YxTYN2e6SOxnf0LHIt7b9tzXmjbDO",
	"D/JWe/RfyUx299SQG4RGNV0/02ZrufbqZ1tlLZiNNUmLf39HD9o5TLcY9JiZSsWBA/Hxn1sfwn0q7Xyd",
	"LxKQ47VvyVzkRxUqXQjjBy0Jv41ERzcAfa8ttupInriPnNvHTLGqI/6yIlQPDfYUoXb9tzW5H5EgKtHZ",
	"Ud2jL7SNpXtNk8Hv7W2tT6UYbFZtPG0iXUxfbuOtJasha2TTlwnbm2dShl0tCTxvLcS0j/UlYoLYxH07",
	"JQAE/Sqs5XQscOwmmkdGWz/P5C3kw4c9YdghEhP7dl9rV627o/akgY7fW/quf3H9O6MadmfYwUv1gWXD",
	"aiRhK84JDYBbRjpBi7eGUR5Xk2ncp46JtuZIqimProLrWUuxqZrvgWjDJFi/8dvR+C3k9up3M1DzTep4",
	"a96nj54jT+uL/K7l36CWb0m7l21uaD4z6qHEClTYEntwVS+7ul4YyLhrYv6/jPaX39X/u/r/+dV/EZaG",
	"D6Z7s92tXsompYylBmlrs7hV8Ei31ozT7T3jiDLSOvMjSifB79PwxGyI1qf5lPr0xIuDSRA+XZeJ7szd",
	"uuNPcB6Qqy+rgs4dSkjzihn/V8tHh6792yngtOWtVVA/WLzBbP0PzryrgkF7M779o0Rh+nHBfUd3Cn5v",
	"HvJYQr6vQFSl33/l/NkvhX53rV9xrZU81r+IZevRsTAQuDXi+gD+tDVCHTX6534Zr7HudQGVhqA3R2Em",
	"DzVqqwYX2Uzwc6LspQa/6FeAoZ/U5mqz5Ze5H0aL6VO1RPsVX/CP9srmntmm6s/9Zr7HtO9Net8fKm0N",
	"z/f48fLWyH96i85iNfHf/anpx3Rc1VV9V/q40jeaRXec1r8V0piB1g+axWM3BAhmVSmBn5sc8UKM6uFG",
	"vOPw3p7ZRFBzoboDcrGBxOGWHIYBuV0N8Mrne+5yd2F82FXBXQivwvrgbj3RbuFQmbxdCL8Ykc+BTcGt",
	"ARTj7NVvr+uu7LMP55OPxz4wUOzF6zCz9ezt2cXxtqpRR/7zzf8GAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
