#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: graph {nodes|edges|queries|objects} [FILE]" >&2
    exit 2
}

command=${1:-}
file=${2:--}

[[ $# -le 2 ]] || usage

case "$command" in
nodes | edges)
    yq -p yaml -o yaml ".$command | length" "$file"
    ;;
queries)
    yq -p yaml -o yaml '[.nodes[].queries[]] | length' "$file"
    ;;
objects)
    yq -p yaml -o yaml '.nodes[].queries[].count as $count ireduce (0; . + $count)' "$file"
    ;;
*)
    usage
    ;;
esac
