= Hacker's guide to Korrel8r
:doctype: book
:toc: left
include::attributes.adoc[]

Tips for contributing to or hacking on the Korrel8r project.

TIP: `make help` will list make targets with brief explanation.


== Building

.Build and install korrel8r using `go install`.
    make install

.Build and publish a korrel8r image using your public image repository.
    make image REGISTRY_BASE=quay.io/myaccount

TIP: Set  `REGISTRY_BASE` or `IMG` to the repository where you want to push images.


IMPORTANT: you need a _public_ image repository for your cluster to pull images.
Some registry services create _private_ repositories by default, make sure your repository is _public_.

== Running korrel8r

=== Cluster Set-up

For korrel8r to work, you need some observability data to look at.

- https://github.com/korrel8r/config/[] has scripts to set up observability on an OpenShift cluster.
-  link:hack/kind/README.md[hack/kind] has some scripts for testing on Kind clusters.

Log into your cluster as `kubeadmin` or other admin user.

=== Running outside the cluster

You can run korrel8r on your local host, it can observe your cluster from the outside.
You need to be logged-in as `kubeadmin` to your cluster:

.Run korrel8r service outside the cluster.
[source,bash]
----
korrel8r web -c etc/korrel8r/openshift-route.yaml -http :8080
----

Browse the interactive API page:
    xdg-open http://localhost:8080/api

Use `korrel8r --help` for more commands and options.

=== Deploy to Cluster

.Build a new image and deploy it to a cluster.
[source,bash]
----
make deploy
----

TIP: Set  `REGISTRY_BASE` or `IMG` to the repository where you want to push images.

.Browse the interactive REST API:
  xdg-open $(oc get route/korrel8r -n korrel8r -o 'template=https://{{.spec.host}}')

== Contributing to documentation

. Fork and clone the repository
. Install Go
. Install make
. Run the following command to install required tools:
+
[source,terminal]
----
make tools
----

. Make changes to the docs, then run the following command to generate the local `_site` directory:
+
[source,terminal]
----
make _site
----

Preview `_site` with your web browser.
