[id="index"]
= Korrel8r User Guide
:doctype: book
:toc: left
include::attributes.adoc[]

[id="index-overview"]

Documentation for the {project}#readme[Korrel8r Project image:images/icon.svg[width=32]]

== Overview

Observing a cluster involves different types of signal; for examples logs, metrics, traces, cluster events, cluster alerts, network events and so on.
This usually means using several Observability tools, each with their own data model, storage technology, and query language.
These differences make it difficult to recognize relationships between different signals and resources in a cluster.

Korrel8r is a _correlation engine_ for observable signals and Kubernetes resources.
Each distinct data set, with its own labelling, storage, and schema, is known as a _domain_.
Examples of domains include:

- Kubernetes Resources, managed by the Kubernetes API server.
- Metrics stored in Prometheus.
- Logs stored in Loki in a known format.

New domains can be added to deal with new signal types, for example Network Observability Events.

Korrel8r uses an extendable set of _rules_ to define relationships between data items.
Rules can define relationships within a domain, or _between different domains_.
For example, rules can define

- How to find logs or metrics related to Kubernetes resources and vice-versa.
- How to find Kubernetes resources related to network events.
- How to find logs, metrics or resources related to Prometheus Alerts

Given a _start_ object (resource or signal), Korrel8r searches its rule graph to find a network of related objects.
There are two types of search:

_Goal_ search:: given a _goal_ data type (log, metric, Pod etc.), find all paths from the _start_ to objects of the goal type.
_Neighbourhood_ search:: given a numeric _depth_  find all objects reachable from _start_ by following _depth_ rules or less.


== Architecture

include::about-domains.adoc[leveloffset=+2]

include::about-rules.adoc[leveloffset=+2]

== Getting Started

include::korrel8r-command.adoc[leveloffset=+2]

include::in-cluster.adoc[leveloffset=+2]

include::korrel8rcli-command.adoc[leveloffset=+2]

[id="index-architecture"]
include::configuration.adoc[leveloffset=+1]

[id="index-reference"]
= Reference

[id="index-domain-reference"]
== Domains
Reference details for the for the classes, objects, queries and stores of each available domain.

include::gen/domains.adoc[leveloffset=+2]

[id="index-rest-api-reference"]
include::gen/rest_api.adoc[leveloffset=+1]

include::troubleshooting.adoc[leveloffset=+1]
