[id="index"]
= Korrel8r User Guide
:doctype: book
:toc: left
:toclevels: 3
:keywords: correlation, observability, signal, kubernetes
include::attributes.adoc[]
include::gen/attributes.adoc[]

[.metadata]
{author} -- version {revnumber}, {revdate}

[id="index-overview"]
== Overview

Observing a cluster involves many types of signal; for examples logs, metrics, traces, cluster events, cluster alerts, network events and so on.
This usually means using several Observability tools, which often have their own unique data models, storage technologies, query languages, and related nomenclature.
These differences make it difficult to recognize relationships between different signals and resources.
As a result, troubleshooting and identifying resources affected by issues in your cluster can be time consuming and difficult.

Korrel8r is a _correlation engine_ for observable signals and Kubernetes resources from multiple _domains_.
A _domain_ is a data set with consistent labelling, storage, and schema. Examples of domains include:

- Resources managed by the Kubernetes API server itself.
- Metrics stored in Prometheus.
- Logs stored in Loki in a known format.


Korrel8r uses an extendable set of _rules_ to define relationships between data in _multiple_ domains.
For example, rules can define

- How to find logs or metrics related to Kubernetes resources and vice-versa.
- How to find Kubernetes resources related to network events.
- How to find logs, metrics or resources related to Prometheus Alerts

Given a _start_ object, Korrel8r can searches its graph of rules to find related _goal_ objects, or to show the _neighbourhood_ data related to the start object.

[id="index-architecture"]
=== Architecture

include::about-domains.adoc[leveloffset=+3]

include::about-objects.adoc[leveloffset=+3]

include::about-rules.adoc[leveloffset=+3]

== Installing on a cluster

include::installing-korrel8r-ocp.adoc[leveloffset=+2]

include::korrel8r-resource.adoc[leveloffset=+2]

include::using-korrel8r.adoc[leveloffset=+1]

include::configuration.adoc[leveloffset=+1]

include::troubleshooting.adoc[leveloffset=+1]

[id="index-reference"]
== Reference

[id="index-domain-reference"]
=== Domains

Reference details for the for the classes, objects, queries and stores of each available domain.

include::gen/domains.adoc[leveloffset=+3]

[id="index-rest-api-reference"]
include::gen/rest_api.adoc[leveloffset=+2]
