[id="index"]
= Korrel8r User Guide
:doctype: book
:toc: left
:toclevels: 3
:keywords: correlation, observability, signal, kubernetes
include::attributes.adoc[]

[NOTE]
====
This documentation is part of the {project}[Korrel8r project]. +
It is available in {pages}/index.html[HTML] and {pages}/ebook.pdf[PDF] format.
====

[id="index-overview"]
== Overview

Many observability tools and observable systems use their own unique data models, storage technologies, query languages, and related nomenclature.

The differences between these nomenclatures can make it difficult for users to recognize relationships between different Kubernetes cluster resources. As a result, troubleshooting and identifying resources affected by issues in your cluster can be time consuming and difficult.

Korrel8r is a correlation engine for observable signals that relates Kubernetes objects to different types of signal data. Given a _start_ object, Korrel8r searches for a chain of rules to related _goal_ objects. Korrel8r can also show the _neighbourhood_ of all data related to an object of interest.

A REST API can be used by clients to make correlation queries. The REST API can be deployed as a service in a cluster, or run outside the cluster and connect to signal stores inside the cluster.

Signal data can be stored in separate signal stores, and encoded using different schema.

[IMPORTANT]
====
To navigate between correlated data, Korrel8r needs access to the cluster API and several data stores.
Currently Korrel8r can only be deployed by a user with the `cluster-admin` role.

This may change in future, see:
link:{project}/issues/73[Issue 73: Authentication and Authorization for restricted access.]
====

[id="index-architecture"]
=== Architecture

include::about-domains.adoc[leveloffset=+3]
include::about-objects.adoc[leveloffset=+3]
include::about-rules.adoc[leveloffset=+3]

// OCP setup / installation docs
include::installing-korrel8r-ocp.adoc[leveloffset=+1]
// troubleshooting
include::troubleshooting.adoc[leveloffset=+2]

// User guides
include::using-korrel8r.adoc[leveloffset=+1]
include::configuration.adoc[leveloffset=+1]

[id="index-reference"]
== Reference

[id="index-api-reference"]
// REST API
include::zz_rest_api.adoc[leveloffset=+2]

[id="index-domain-reference"]
=== Domain Reference

Reference details for the for the classes, objects, queries and stores of each available domain.

include::zz_domains.adoc[leveloffset=+3]
