= The Korrel8r Resource
:instance-ns: korrel8r
:instance-name: korrel8r-instance
:instance-role: view
:instance-sa: system:serviceaccount:
:user-facing-roles: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
include::attributes.adoc[]

== Default korrel8r-instance

NOTE: These examples assume the operator is installed in the namespace `{instance-ns}`.
Modify the example accordingly if it is installed in a different namespace.

The simplest way to run Korrel8r is to create the special _default instance_
in namespace `{instance-ns}` with name `{instance-name}`.

[source,yaml,subs=attributes+]
.Example of a default Korrel8r instance.
----
apiVersion: korrel8r.openshift.io/v1alpha1
kind: Korrel8r
metadata:
  name: korrel8r-instance <1>
  namespace: {instance-ns} <2>
  spec: <3>
----

<1> Required name `{instance-name}` for the default instance.
<2> Required namespace `{instance-ns}` for the default instance.
<3> If `spec` is absent or empty, Korrel8r uses a default configuration
    that connects to the default signal stores for {rh-ocp}, and integrates with the {rh-console}. +
    You can customize the behaviour of the default instance by adding `spec` fields.

[NOTE]
====
A `ClusterRoleBinding` for the _default instance_ is installed as part of the operator.
It binds the standard kubernetes `clusterrole/{instance-role}` to the default instance `ServiceAccount`.
You do not need to create this binding or service account.

This allows the default instance to read most cluster resources and connect to observability stores like Prometheus and Loki.
See the link:{user-facing-roles}[Kubernetes RBAC documentation] for details of the `view` role.

[source,yaml,subs=attributes+]
.Default instance ClusterRoleBinding installed with the operator. You do not need to create this binding.
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: korrel8r
  name: korrel8r-instance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: korrel8r-instance
  namespace: korrel8r
----
====

== Other Korrel8r resources

You can create other instances of Korrel8r in any namespace, with any name.
You need to create your own `ClusterRoleBinding` or `RoleBinding` for non-default instances.
You do not need to create `ServiceAccount`, the operator will do that automatically.

[soure,yaml,subs="attributes+"]
.Example ClusterRoleBinding for Korrel8r my-name in my-namespace.
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding <1>
metadata:
  name: my-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view <2>
subjects:
- kind: ServiceAccount <3>
  name: my-name
  namespace: my-namespace
----

<1> You can also create a `RoleBinding` to restrict Korrel8r to a single namespace.
    This will limit correlation results to resources in that namespace.
<2> You can modify the role to restrict what your Korrel8r instance can read.
    Korrel8r's functionality will be limited to resources and stores it can access.
<3> The operator creates a `ServiceAccount` with the same namespace and name as the `Korrel8r` instance.
    Your `ClusterRoleBinding` or `RoleBinding` should use this as its subject.
    You do not need to create this `ServiceAccount`.

