= The korrel8r command
include::attributes.adoc[]

See {korrel8r-help}[korrel8r help] for more details.

`korrel8r` loads correlation rules and connects to data stores based on a xref:configuration.adoc[configuration file]

.Install the korrel8r engine
[source,terminal]
----
go install github.com/korrel8r/korrel8r/cmd/korrel8r@latest
----

== Authentication and Authorization

Korrel8r queries observability signal stores with sensitive data.
It requires a _Bearer Token_ to ensure that only authorized data is returned.

On the command line, korrel8r uses the token associated with your kubectl login.
When run as a REST server, it uses the bearer token from the incoming request to impersonate the client.

This means you need to be logged on as an admin cluster user to run korrel8r locally, and you need to use
an appropriate bearer token with clients like https://curl.se[curl] or xref:korrel8rcli-command.adoc[korrel8rcli].

If you are logged in to a {rh-ocp} cluster, you can get your bearer token with


[source,terminal]
----
oc whoami -t
----

== Configuration

There are some example configuration files to get started.
You can download them locally or use them directly by URL.

link:{raw-etc-korrel8r}/openshift-route.yaml[openshift-route.yaml]::
Run korrel8r outside the cluster, connect to stores via routes:

link:{raw-etc-korrel8r}/openshift-svc.yaml[openshift-svc.yaml]::
Used to run korrel8r as a clutser service, connect to stores via service URLs.
See xref:in-cluster.adoc[] for more about running as a cluster service.

== Command-line Examples

.List the known korrel8r domains.
[source,terminal,subs=attributes+]
----
korrel8r --config {raw-etc-korrel8r}/openshift-route.yaml list
----

.List korrel8r classes in the k8s domain.
[source,terminal,subs=attributes+]
----
korrel8r --config {raw-etc-korrel8r}/openshift-route.yaml list k8s
----

== Run as a REST service

.Run the korrel8r engine outside the cluster, with REST API at localhost:8080.
[source,terminal,subs=attributes+]
----
korrel8r --config {raw-etc-korrel8r}/openshift-route.yaml web --http=localhost:8080
----

This runs the engine as a REST service that can be queried by other services.
For example, the {rh-ocp} console uses Korrel8r to implement a {troubleshooting-panel}[troubleshooting panel].

You can also use the xref:korrel8rcli-command.adoc[korrel8rcli] command to query
a korrel8r engine from the command line.

NOTE: See xref:_authentication_and_authorization[] for details about access control.

Korrel8r can also run as a xref:in-cluster.adoc[cluster service]
