= Releasing a new version

Steps to release a new version X.Y.Z, for maintainers.

On branch `vX.Y`:

== Update CHANGELOG

Update CHANGELOG.md to reflect changes since last release, add the new release header.
Follow http://keepachangelog.com[these guidelines]. +
You can list git changes with:

  git log --oneline $(git describe --abbrev=0)..

== Prepare for release

Edit Makefile and set 'VERSION?=X.Y.Z' for the new release.
Make sure you are logged in to `quay.io/korrel8r` to push images.

  make clean; make pre-release REGISTRY_BASE=quay.io/korrel8r

Use `git status` to verify that all changes are related to the version number change.

Commit and push your changes with commit message 'Release X.Y.Z'
- Push directly to `main` if version X.Y.Z is the next release version.
- Push to branch `vX.Y` if it exists, and merge or cherry pick changes back to `main` as appropriate.

The `vX.Y` branch only needs to be created if/when main has moved on to a version > X.Y.

== Publish the release

  make release REGISTRY_BASE=quay.io/korrel8r

This does the following:
- `make clean` and re-build, verify nothing changes and the working tree is clean.
- Creates and pushes the git tag 'vX.Y.Z'
- Updates the 'latest' image tag to point to the new images.

== Update main

If necessary, port changes on the release branch back to `main`.

Cherry pick the release commit back to `main` to keep the main CHANGELOG up to date.
