[id="using-korrel8r"]
= Using Korrel8r
include::attributes.adoc[]

[id="using-ocp-console"]
== On {rh-ocp}

[IMPORTANT]
====
Ensure that you have xref:#installing-korrel8r-ocp[installed Korrel8r]
====

. Refresh the web console
. Navigate to *Observe* -> *Logs*. Click the *Metrics* link to see correlated metrics of each log record.
. Navigate to *Observe* -> *Alerting*, and click an alert. Alerts that have related logs have a *see related logs* link.

[TIP]
====
Not all alerts have a *see related logs* link. Only alerts that are _related_ to container workloads can have related logs. For example, `KubePodCrashLooping` is related to a pod and so can have related logs. See the xref:troubleshooting.adoc#troubleshooting-no-related-logs[There is no "see related logs" link] documentation for more information.
====

== Command Line

=== Installing

[source,terminal]
.Install the korrel8r executable:
----
go install github.com/korrel8r/korrel8r/cmd/korrel8r@latest
go install github.com/korrel8r/korrel8r/cmd/korrel8rcli@latest
----

=== Commands

{korrel8r-help}[korrel8r]::
The correlation engine. Can be used from the command line or as a REST server.
The REST API can be deployed as a service in a cluster, or run outside the cluster and connect to signal stores inside the cluster.
{korrel8r-help}[korrel8r help]

{korrel8rcli-help}[korrel8rcli]::
A command line client to query a remote `korrel8r` server.
{korrel8rcli-help}[korrel8rcli help]

Log into your cluster with admin privileges to test korrel8r can read kubernetes resources:

.Listing k8s resource types using default configuration URL.
----
korrel8r -c https://raw.githubusercontent.com/korrel8r/korrel8r/main/etc/korrel8r/korrel8r.yaml list k8s
----

== Running as a Service

🚧 #Under Construction# 🚧
// TODO: move from README. Link to reference. Curl examples of API, use swagger UI.#

== Using the client

🚧 #Under Construction# 🚧
