apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-cluster-observability-operator
resources:
- route.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: korrel8r
