= korrel8rcli completion

Generate the autocompletion script for the specified shell

== Synopsis

Generate the autocompletion script for korrel8rcli for the specified shell.
See each sub-command's help for details on how to use the generated script.

== Options

----
  -h, --help   help for completion
----

== Options inherited from parent commands

----
  -t, --bearer-token string                         Authhorization token, default from env KORREL8RCLI_BEARER_TOKEN or kube config.
      --debug                                       Enable debug output.
  -k, --insecure                                    Insecure connection, skip TLS verification.
  -o, --output enum(yaml,json-pretty,json,ndjson)   Output format (default yaml)
  -u, --url string                                  URL of remote korrel8r, default from env KORREL8RCLI_URL (default "https://korrel8r-openshift-cluster-observability-operator.apps.snoflake.home")
----

== SEE ALSO

* xref:korrel8rcli.adoc[korrel8rcli]	 - REST client for a remote korrel8r server.
* xref:korrel8rcli_completion_bash.adoc[korrel8rcli completion bash]	 - Generate the autocompletion script for bash
* xref:korrel8rcli_completion_fish.adoc[korrel8rcli completion fish]	 - Generate the autocompletion script for fish
* xref:korrel8rcli_completion_powershell.adoc[korrel8rcli completion powershell]	 - Generate the autocompletion script for powershell
* xref:korrel8rcli_completion_zsh.adoc[korrel8rcli completion zsh]	 - Generate the autocompletion script for zsh
