= korrel8r

REST service to correlate observability data

== Options

----
  -c, --config string        Configuration file (default "/etc/korrel8r/korrel8r.yaml")
  -h, --help                 help for korrel8r
  -o, --output string        Output format: [json, json-pretty, yaml] (default "yaml")
      --profile string       Enable profiling, one of [block, cpu, goroutine, mem, alloc, heap, mutex, clock, http]
      --profilePath string   Output path for profile
  -v, --verbose int          Verbosity for logging (0: notice/error/warn, 1: info, 2: debug, 3: trace-per-request, 4: trace-per-rule, 5: trace-per-object)
----

== SEE ALSO

* xref:korrel8r_goals.adoc[korrel8r goals]	 - Execute QUERY, find all paths to GOAL classes.
* xref:korrel8r_list.adoc[korrel8r list]	 - List domains or classes in DOMAIN.
* xref:korrel8r_neighbours.adoc[korrel8r neighbours]	 - Get graph of nearest neighbours
* xref:korrel8r_objects.adoc[korrel8r objects]	 - Execute QUERY and print the results
* xref:korrel8r_rules.adoc[korrel8r rules]	 - List rules by start, goal or name
* xref:korrel8r_template.adoc[korrel8r template]	 - Apply a Go template to the korrel8r engine.
* xref:korrel8r_version.adoc[korrel8r version]	 - Print the version of this command.
* xref:korrel8r_web.adoc[korrel8r web]	 - Start REST server. Listening address must be  provided via --http or --https.
