= korrel8r completion

Generate the autocompletion script for the specified shell

== Synopsis

Generate the autocompletion script for korrel8r for the specified shell.
See each sub-command's help for details on how to use the generated script.

== Options

----
  -h, --help   help for completion
----

== Options inherited from parent commands

----
  -c, --config string    Configuration file (default "/etc/korrel8r/korrel8r.yaml")
  -o, --output string    Output format: [json, json-pretty, yaml] (default "yaml")
      --panic            panic on error instead of exit code 1
      --profile string   Enable profiling, one of [cpu mem trace]
  -v, --verbose int      Verbosity for logging (0 = notice, 1 = info, 2 = debug, 3 = trace)
----

== SEE ALSO

* xref:korrel8r.adoc[korrel8r]	 - Correlation of observability signal data from command line or as a REST service
* xref:korrel8r_completion_bash.adoc[korrel8r completion bash]	 - Generate the autocompletion script for bash
* xref:korrel8r_completion_fish.adoc[korrel8r completion fish]	 - Generate the autocompletion script for fish
* xref:korrel8r_completion_powershell.adoc[korrel8r completion powershell]	 - Generate the autocompletion script for powershell
* xref:korrel8r_completion_zsh.adoc[korrel8r completion zsh]	 - Generate the autocompletion script for zsh
