// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

package rules

import (
	"bytes"
	"fmt"

	"github.com/korrel8r/korrel8r/pkg/korrel8r"
	"github.com/valyala/quicktemplate"
)

// QuickApplyFunc writes the result of applying a rule to a start object.
//
// The result is written as a list of goal query strings, one per line.
// A blank (whitespace-only) result means the rule does not apply to the start object.
//
// QuickApplyFunc has the same signature as the Stream* functions generated by
// [github.com/valyala/quicktemplate], so compiled template functions can be used directly.
type QuickApplyFunc func(qw *quicktemplate.Writer, start korrel8r.Object)

var _ korrel8r.Rule = &quickRule{}

type quickRule struct {
	name        string
	start, goal []korrel8r.Class
	apply       QuickApplyFunc
	domains     *korrel8r.Domains
}

// NewQuickRule returns a korrel8r.Rule that uses a pre-compiled quicktemplate function to
// transform objects to queries. apply must be a compiled quicktemplate Stream* function, see
// [QuickApplyFunc]. Unlike [NewTemplateRule], parsing cannot fail; any template errors are reported
// when the rule is applied.
func NewQuickRule(name string, start, goal []korrel8r.Class, apply QuickApplyFunc, domains *korrel8r.Domains) korrel8r.Rule {
	return &quickRule{name: name, start: start, goal: goal, apply: apply, domains: domains}
}

func (r *quickRule) Name() string            { return r.name }
func (r *quickRule) String() string          { return r.Name() }
func (r *quickRule) Start() []korrel8r.Class { return r.start }
func (r *quickRule) Goal() []korrel8r.Class  { return r.goal }

// Apply the rule by running the compiled template.
//
// Returns (nil, err) if the template panics with an error (see [Fail]), or if the result
// contains an invalid query string.
// Returns (nil, nil) if the result is blank (all spaces).
func (r *quickRule) Apply(start korrel8r.Object) (queries []korrel8r.Query, err error) {
	defer func() {
		if p := recover(); p != nil {
			queries, err = nil, fmt.Errorf("%v", p)
		}
	}()
	b := bufPool.Get().(*bytes.Buffer)
	b.Reset()
	defer bufPool.Put(b)
	qw := quicktemplate.AcquireWriter(b)
	r.apply(qw, start)
	quicktemplate.ReleaseWriter(qw)
	return parseQueries(r.domains, b.String())
}

// Fail aborts the current rule with an error.
// It is intended for use in compiled quicktemplate rules where a condition is not met and the
// rule should fail rather than not apply.
func Fail(format string, args ...any) {
	panic(fmt.Errorf(format, args...))
}
