// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/korrel8r/korrel8r/client/pkg/swagger/models"
)

// NewPostGraphsNeighboursParams creates a new PostGraphsNeighboursParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostGraphsNeighboursParams() *PostGraphsNeighboursParams {
	return &PostGraphsNeighboursParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostGraphsNeighboursParamsWithTimeout creates a new PostGraphsNeighboursParams object
// with the ability to set a timeout on a request.
func NewPostGraphsNeighboursParamsWithTimeout(timeout time.Duration) *PostGraphsNeighboursParams {
	return &PostGraphsNeighboursParams{
		timeout: timeout,
	}
}

// NewPostGraphsNeighboursParamsWithContext creates a new PostGraphsNeighboursParams object
// with the ability to set a context for a request.
func NewPostGraphsNeighboursParamsWithContext(ctx context.Context) *PostGraphsNeighboursParams {
	return &PostGraphsNeighboursParams{
		Context: ctx,
	}
}

// NewPostGraphsNeighboursParamsWithHTTPClient creates a new PostGraphsNeighboursParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostGraphsNeighboursParamsWithHTTPClient(client *http.Client) *PostGraphsNeighboursParams {
	return &PostGraphsNeighboursParams{
		HTTPClient: client,
	}
}

/*
PostGraphsNeighboursParams contains all the parameters to send to the API endpoint

	for the post graphs neighbours operation.

	Typically these are written to a http.Request.
*/
type PostGraphsNeighboursParams struct {

	/* Request.

	   search from neighbours
	*/
	Request *models.Neighbours

	/* Rules.

	   include rules in graph edges
	*/
	Rules *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post graphs neighbours params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGraphsNeighboursParams) WithDefaults() *PostGraphsNeighboursParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post graphs neighbours params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGraphsNeighboursParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) WithTimeout(timeout time.Duration) *PostGraphsNeighboursParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) WithContext(ctx context.Context) *PostGraphsNeighboursParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) WithHTTPClient(client *http.Client) *PostGraphsNeighboursParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) WithRequest(request *models.Neighbours) *PostGraphsNeighboursParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) SetRequest(request *models.Neighbours) {
	o.Request = request
}

// WithRules adds the rules to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) WithRules(rules *bool) *PostGraphsNeighboursParams {
	o.SetRules(rules)
	return o
}

// SetRules adds the rules to the post graphs neighbours params
func (o *PostGraphsNeighboursParams) SetRules(rules *bool) {
	o.Rules = rules
}

// WriteToRequest writes these params to a swagger request
func (o *PostGraphsNeighboursParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if o.Rules != nil {

		// query param rules
		var qrRules bool

		if o.Rules != nil {
			qrRules = *o.Rules
		}
		qRules := swag.FormatBool(qrRules)
		if qRules != "" {

			if err := r.SetQueryParam("rules", qRules); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
