
[#_alert_domain]
= alert domain


Domain alert provides Prometheus alerts, queries and access to Thanos and AlertManager stores.

== Class

There is a single class `alert:alert`.

== Object

An alert object is represented by this Go type. Rules starting from an alert should use the capitalized Go field names rather than the lowercase JSON names. link:https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/alert#Object[Object]

== Query

A JSON map of string names to string values, matched against alert labels, for example:

----
alert:alert:{"alertname":"KubeStatefulSetReplicasMismatch","container":"kube-rbac-proxy-main","namespace":"openshift-logging"}
----

To query mutiple alerts at the same time, it's possible to provide an array of maps:

----
alert:alert:[{"alertname":"alert1"},{"alertname":"alert2"}]
----

== Store

A client of Prometheus and/or AlertManager. Store configuration:

----
domain: alert
metrics: PROMETHEUS_URL
alertmanager: ALERTMANAGER_URL
----

Either or both of `metrics` or `alertmanager` may be present.


== Query


Query is a map of label name:value pairs for matching alerts, serialized as JSON.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/alert#Query[Query]

== Object


Object contains alert data, passed as *Object when used as a korrel8r.Object.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/alert#Object[Object]

[#_incident_domain]
= incident domain


Domain incident provides mapping to link:https://github.com/openshift/cluster-health-analyzer[https://github.com/openshift/cluster-health-analyzer] incidents.

== Class

There is a single class `incident:incident`.

== Object

An incident object contains id and mapping to the sources (alert is the only supported source type at the moment).

== Query

One can query the incident by its id.

----
incident:incident:{"id":"id-of-the-incident"}
----

It's also possible to provide labels from an alert to get a corresponding incident.

----
incident:incident:{"alertLabels":{
 "alertname":"AlertmanagerReceiversNotConfigured",
 "namespace":"openshift-monitoring"}}
----

== Store

A client of Prometheus. Store configuration:

----
domain: incident
metrics: PROMETHEUS_URL
----


== Query





See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/incident#Query[Query]

== Object


Object contains incident data, passed as *Object when used as a korrel8r.Object.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/incident#Object[Object]

[#_k8s_domain]
= k8s domain


Domain k8s implements link:https://kubernetes.io/docs/concepts/overview/[Kubernetes] resources stored in a Kube API server.

== Store

The k8s domain automatically connects to the current cluster (as determined by kubectl), no additional configuration is needed.

----
 stores:
	  domain: k8s
----

== Template Functions

The following template functions are available to rules.

----
k8sClass
    Takes string arguments (apiVersion, kind).
    Returns the korrel8r.Class implied by the arguments, or an error.
----


== Query


Query struct for a Kubernetes query.

Example:

----
k8s:Pod.v1:{"namespace":"openshift-cluster-version","name":"cluster-version-operator-8d86bcb65-btlgn"}
----


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/k8s#Query[Query]

== Object


Object represents a kubernetes resource as a map, map keys are serialized field names. Rule templates should use the JSON (lowerCase) field names, NOT the UpperCase Go struct field names.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/k8s#Object[Object]

[#_log_domain]
= log domain


Domain log is a domain for openshift-logging ViaQ logs stored in Loki or LokiStack.

== Class

There are 3 classes corresponding to the 3 openshift logging log types:

----
log:application
log:infrastructure
log:audit
----

== Object

A log object is a JSON map\[string]any in ViaQ format.

== Query

A query is a link:https://grafana.com/docs/loki/latest/query/[LogQL] query string, prefixed by the logging class, for example:

----
log:infrastructure:{ kubernetes_namespace_name="openshift-cluster-version", kubernetes_pod_name=~".*-operator-.*" }
----

== Store

To connect to a lokiStack store use this configuration:

----
domain: log
lokistack: URL_OF_LOKISTACK_PROXY
----

To connect to plain loki store use:

----
domain: log
loki: URL_OF_LOKI
----

Copyright: This file is part of korrel8r, released under link:https://github.com/korrel8r/korrel8r/blob/main/LICENSE[https://github.com/korrel8r/korrel8r/blob/main/LICENSE]

== Template Functions

----
logTypeForNamespace
    Takes a namespace string argument.
    Returns the log type ("application" or "infrastructure") of a container in the namespace.

logSafeLabel
    Convert the string argument into a  safe label containing only alphanumerics '_' and ':'.
----


== Query


Query is a LogQL query string


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/log#Query[Query]

== Object


Object is a map in Viaq format.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/log#Object[Object]

[#_metric_domain]
= metric domain


package metric represents Prometheus metric time-series as objects.

== Class

There is only one class: `metric:metric`

== Object

A link:https://pkg.go.dev/github.com/prometheus/common@v0.45.0/model#Metric[Metric] is a time series identified by a label set. Korrel8r does not consider load the sample data for a time series, or use it in rules. If a korrel8r search time constraints, then metrics that have no values that meet the constraint are ignored.

== Store

Prometheus is the store, store configuration:

----
domain: metric
metric: URL_OF_PROMETHEUS
----


== Query


Query is a link:https://prometheus.io/docs/prometheus/latest/querying/basics/[PromQL] query string.

Korrel8r uses metric labels for correlation, it does not use time-series data values. The link:https://prometheus.io/docs/prometheus/latest/querying/basics/[PromQL] query is analyzed to identify series it uses, labels of those series are used for correlation.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/metric#Query[Query]

== Object





See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/metric#Object[Object]

[#_netflow_domain]
= netflow domain


Domain netflow is a domain for network observability flow events stored in Loki or LokiStack.

== Class

There is a single class `netflow:network`

== Object

A log object is a JSON `map\[string]any` in link:https://docs.openshift.com/container-platform/latest/observability/network_observability/json-flows-format-reference.html[NetFlow] format.

== Query

A query is a link:https://grafana.com/docs/loki/latest/query/[LogQL] query string, prefixed by `netflow:network:`, for example:

----
netflow:network:{SrcK8S_Type="Pod", SrcK8S_Namespace="myNamespace"}
----

== Store

To connect to a netflow lokiStack store use this configuration:

----
domain: netflow
lokistack: URL_OF_LOKISTACK_PROXY
----

To connect to plain loki store use:

----
domain: netflow
loki: URL_OF_LOKI
----


== Query


Query is a LogQL query string


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/netflow#Query[Query]

== Object


Object is a map holding netflow entries


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/netflow#Object[Object]

[#_otellog_domain]
= otellog domain


Domain otellog is a domain for openshift-logging OTLP logs stored in Loki or LokiStack.

== Class

There are 3 classes corresponding to the 3 openshift logging log types:

----
otellog:application
otellog:infrastructure
otellog:audit
----

== Object

A otellog object is a JSON map\[string]any in ViaQ format.

== Query

A query is a link:https://grafana.com/docs/loki/latest/query/[LogQL] query string, prefixed by the logging class, for example:

----
otellog:infrastructure:{ kubernetes_namespace_name="openshift-cluster-version", kubernetes_pod_name=~".*-operator-.*" }
----

== Store

To connect to a lokiStack store use this configuration:

----
domain: otellog
lokistack: URL_OF_LOKISTACK_PROXY
----

To connect to plain loki store use:

----
domain: otellog
loki: URL_OF_LOKI
----


== Query


Query is a LogQL query string


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/otellog#Query[Query]

== Object


Object represents an OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/logs/#log-record[log]


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/otellog#Object[Object]

[#_podlog_domain]
= podlog domain


Domain podlog provides direct access to Kubernetes Pod logs via the Kube API-server.

Logs are returned in OTEL format.

== Store

The store is the Kube API server itself, providing direct access to live pod log files. Logs are not guaranteed to be persisted after a pod is destroyed. No parameters are required, a podlog store automatically connects using Kube configuration.

----
domain: podlog
----


== Query


Query has the same fields as a link:https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/k8s#Query[k8s.Query] with and additional 'containers' field.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/podlog#Query[Query]

== Object





See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/podlog#Object[Object]

[#_trace_domain]
= trace domain


Domain trace implements OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/traces[traces] stored in the Grafana link:https://grafana.com/docs/tempo/latest/[Tempo] data store.

== Store

The trace domain accepts an optional "tempostack" field with a URL for tempostack. If absent, connect to the default location for the trace store on an Openshift cluster.

----
stores:
  domain: trace
  tempostack: "https://url-of-tempostack"
----


== Query


Query selector has two forms: a link:https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query string, or a list of trace IDs.

A link:https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query selects spans from many traces that match the query criteria. Example:

----
`trace:span:{resource.kubernetes.namespace.name="korrel8r"}`
----

A trace-id query is a list of hexadecimal trace IDs. It returns all the spans included by each trace. Example:

----
`trace:span:a7880cc221e84e0d07b15993358811b7,b7880cc221e84e0d07b15993358811b7
----


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/trace#Query[Query]

== Object


Object represents an OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/traces/#spans[span]

A trace is simply a set of spans with the same trace-id. There is no explicit class or object representing a trace.


See Go documentation for https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/trace#Object[Object]
