
[#_trace_domain]
= Trace

image:https://pkg.go.dev/badge/github.com/korrel8r/korrel8r.svg[Go Reference,link="https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/trace"]


Package trace implements OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/traces[traces] stored in the Grafana link:https://grafana.com/docs/tempo/latest/[Tempo] data store.

== Class

Class singleton `trace:span` representing an OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/traces/#spans[span]

A trace is simply a set of spans with the same trace-id. There is no explicit class or object representing a trace.

== Object

Object represents an OpenTelemetry link:https://opentelemetry.io/docs/concepts/signals/traces/#spans[span]

A trace is simply a set of spans with the same trace-id. There is no explicit class or object representing a trace.

== Query

Query selector has two forms: a link:https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query string, or a list of trace IDs.

A link:https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query selects spans from many traces that match the query criteria. Example:

----
`trace:span:{resource.k8s.namespace.name="korrel8r"}`
----

A trace-id query is a list of hexadecimal trace IDs. It returns all the spans included by each trace. Example:

----
`trace:span:a7880cc221e84e0d07b15993358811b7,b7880cc221e84e0d07b15993358811b7
----

== Store

The trace domain accepts an optional "tempostack" field with a URL for tempostack. If absent, connect to the default location for the trace store on an Openshift cluster.

----
stores:
  domain: trace
  tempostack: "https://url-of-tempostack"
----

