== alert

Alerts that metric values are out of bounds.

=== Classes

 alert:alert

=== Object

See the https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/domains/alert#Object[Go Object type].
Use capitalized Go field name in templates, not lowercase JSON names.

=== Query

Selector is one of the following

* JSON object with alert label field names and matching label values.
* Array of objects as above, gets alerts that match any object in the array

An empty selector matches all alerts:

 alert:alert:{}

Examples:
    alert:alert:{"container":"kube-rbac-proxy-main","namespace":"openshift-logging"}
    alert:alert:[{"alertname":"alert1"},{"alertname":"alert2"}]

=== Store

A client of Prometheus and/or AlertManager. Store configuration fields:

 domain: alert
 metrics: PROMETHEUS_URL
 alertmanager: ALERTMANAGER_URL

At least one of the fields "metrics" or "alertmanager" must be present.

== incident

Incidents group alerts into higher-level groups.

For more about incidents see the https://github.com/openshift/cluster-health-analyzer[cluster-health-analyzer].

=== Classes

 incident:incident

=== Object

An incident object contains id and mapping to the sources.
Alert is the only supported source type at present.

=== Query

Query selectors are JSON objects.

An empty selector matches all incidents:

 incident:incident:{}

Getting an incident by ID:

 incident:incident:{"id":"id-of-the-incident"}

Using alert labels to get a corresponding incident:

 incident:incident:{"alertLabels":{"alertname":"AlertmanagerReceiversNotConfigured","namespace":"openshift-monitoring"}}

=== Store

A client of Prometheus. Store configuration:

 domain: incident
 metrics: PROMETHEUS_URL

== k8s

Kubernetes resources.

=== Classes

Each Kind of kubernetes resource is a class. Class names have the format:

 k8s:KIND[.VERSION][.GROUP]

Missing VERSION implies "v1", if present VERSION must follow the https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-priority[Kubernetes version patterns]. Missing GROUP implies the core group.

Examples:

 k8s:Pod
 k8s:Pod.v1
 k8s:Deployment.apps
 k8s:Deployment.v1.apps
 k8s:Route.v1.route.openshift.io

=== Object

A map of JSON kubernetes field names and Go values.
Rule templates should use the JSON (lowerCase) field names, not the UpperCase Go field names.

=== Query

JSON selector with the following fields

* *namespace*: namespace containing the resource
* *name*: name of resource
* *labels*: label selector object for metadata labels - { "label": "value", ... }
* *fields*: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/[field selector object] - { "field": "value", ... }

An empty selector matches all resources of the class:

 k8s:Pod:{}

Examples:

 k8s:Pod.v1:{"namespace":"some-namespace", "name":"some-name"}
 k8s:Deployment.v1:{"labels":{"app":"my-application"}, "namespace":"some-namespace" }

=== Store

The k8s domain automatically connects to the currently logged-in kubectl cluster.
No additional configuration is needed.

  stores:
       domain: k8s

=== Template Functions

The following template functions are available to rules.

* *k8sClass*: Takes string arguments (apiVersion, kind).
Returns the korrel8r.Class implied by the arguments, or an error.
* *k8sIsNamespaced*: Takes a k8s Class argument, returns true if the class is a namespace-scoped resource.

== log

Log records from container and node logs.

Logs can be stored on the cluster in LokiStack or in an external Loki server.
They can also be retrieved directly from the Kubernetes API server.
Direct API server access does not provide long-term log storage,
but it gives short-term access when there is no long term log store available.

=== Classes

 log:application
 log:infrastructure
 log:audit

=== Object

A log object is a map of attributes with string keys and values.
Attribute names contain only ASCII letters, digits, underscores, and colons (required for Loki labels).
Other characters are replaced with "_".

For stored logs: Loki stream labels and structured metadata labels become attributes.
If the log body is a JSON object, all nested field paths are flattened into attribute names.

For direct logs: the pod, namespace, and label meta-data are added as attributes
using the same label names as for stored logs.

Special attributes:

* *body*: original log message.
* *timestamp*: time the log was produced, if known, in RFC3339 format.
* *observed_timestamp*: time the log was first stored or recorded, in RFC3339 format.

==== Viaq and OTEL attributes

The openshift logging collector can store logs in two formats:

* *Viaq*: legacy format with attributes like: "kubernetes_namespace_name", "kubernetes_pod_name"
* *OTEL*: new standard format with attributes like: "k8s_namespace_name", "k8s_pod_name".
Note the use of "_" rather than "." to give legal Loki label names.
Otherwise these names are as given in the OTEL specification.

For stored logs, korrel8r returns whatever format has been stored in Loki.

For direct logs, _both_ Viaq and OTEL attributes are included to ease migration.

=== Query

There are two types of query selector:

* Direct container selector: The same JSON selector used in k8s queries, with an additional "container" field.
* https://grafana.com/docs/loki/latest/query[LogQL] expression: LogQL queries can only be used to retrieve stored logs

==== Container selectors

Container selector fields (see k8s domain for more detail), all fields are optional:

* *namespace*
* *name*
* *labels*
* *fields*
* *containers*: array of container names, only get logs from these containers.

If stored logs are available, the container selector is automatically translated into
an equivalent LogQL expression.

An empty selector matches all logs of the class:

 log:application:{}

Examples:

 log:application:{ "namespace": "something", "labels":{"app": "myapp"}, "containers":["foo", "bar"]}
 log:infrastructure:{ "namespace": "openshift-kube-apiserver", "containers":["kube-apiserver"]}

==== LogQL queries

Selector is a https://grafana.com/docs/loki/latest/query[LogQL] expression, for example:

 log:infrastructure:{kubernetes_namespace_name="openshift-cluster-version", kubernetes_pod_name=~".*-operator-.*"}

==== Viaq and OTEL

When translating container selectors into LogQL, Korrel8r currently uses Viaq attributes.
This works with existing deployments and with the early support for OTEL logging,
which include backward-compatible Viaq labels.

Korrel8r will be updated to use OTEL directly in future.

=== Store Configuration

 domain: log
 lokiStack: https://URL_OF_DEFAULT_LOKISTACK
 direct: true

Log queries work as follows:

. If lokiStack is set, try to connect to the URL and retrieve stored logs.
. If direct is true and lokiStack get fails (or lokiStack is not set): use the API server directly.

At least one of lokiStack and direct must be set.

=== Template functions

The following functions can be used in rule templates when the log domain is available:

* *logTypeForNamespace*: Takes a namespace string, returns the log type for logs in that namespace; "application" or "infrastructure"
* *logSafeLabel*: Replace all characters other than alphanumerics, '_' and ':' with '_'.
* *logSafeLabels*: Takes a map[string]string argument.
Returns a map where each key is replaced by the result of logSafeLabel

== metric

Time-series of measured values.

=== Classes

 metric:metric

=== Object

A https://pkg.go.dev/github.com/prometheus/common@v0.45.0/model#Metric[Metric] is a time series identified by a label set. Korrel8r only uses labels for correlation, it does not use sample values. If a korrel8r search has time constraints, then metrics with no values that meet the constraint are ignored.

=== Query

Selector is a https://prometheus.io/docs/prometheus/latest/querying/basics/[PromQL] query string.

Korrel8r uses metric labels for correlation, it does not use time-series data values.
The PromQL expression is parsed to extract the label matchers for the series it refers to.

An empty selector matches all metrics:

 metric:metric:{}

Examples:

 metric:metric:kube_pod_info{namespace="default"}
 metric:metric:{namespace="tracing-app-k6",pod="k6-tracing-564cf6dc8b-hpxd2"}

=== Store

Prometheus is the store, store configuration:

 domain: metric
 metric: URL_OF_PROMETHEUS

== mock

Mock domain.

== netflow

Network flows from source nodes to destination nodes.

=== Classes

 netflow:network

=== Object

JSON object in https://docs.openshift.com/container-platform/latest/observability/network_observability/json-flows-format-reference.html[NetFlow] format.

=== Query

Selector is a https://grafana.com/docs/loki/latest/query/[LogQL] query string.

An empty selector matches all network flows:

 netflow:network:{}

Examples:

 netflow:network:{SrcK8S_Type="Pod", SrcK8S_Namespace="myNamespace"}
 netflow:network:{DstK8S_Namespace="openshift-apiserver", DstK8S_OwnerName="apiserver"}

=== Store

To connect to a netflow lokiStack store use this configuration:

 domain: netflow
 lokistack: URL_OF_LOKISTACK_PROXY

To connect to plain loki store use:

 domain: netflow
 loki: URL_OF_LOKI

== trace

Follow the path of a request through your application.

OpenTelemetry https://opentelemetry.io/docs/concepts/signals/traces[traces] stored in the Grafana https://grafana.com/docs/tempo/latest/[Tempo] data store.

=== Classes

 trace:span

=== Object

Represents a https://opentelemetry.io/docs/concepts/signals/traces/#spans[span].
A trace is a set of spans with the same trace-id, there is no explicit class representing a trace.

=== Query

Selector has two forms:

* https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query string
* A list of trace IDs.

An empty selector matches all spans:

 trace:span:{}

A https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query can select spans from many traces.

Example:

 trace:span:{resource.k8s.namespace.name="korrel8r"}

A trace-id query is a list of hexadecimal trace IDs.
It returns all the spans included by each trace.

Example:

 trace:span:a7880cc221e84e0d07b15993358811b7,b7880cc221e84e0d07b15993358811b7

=== Store

The trace domain accepts an optional "tempoStack" field with a URL to connect.

 stores:
   domain: trace
   tempoStack: "https://url-of-tempostack"
