
= Domain `alert`

Domain `alert` provides Prometheus alerts, queries and access to Thanos and AlertManager stores.

== Class

There is a single class `alert:alert`.

== Object

An alert object is represented by this Go type. Rules starting from an alert should use the capitalized Go field names rather than the lowercase JSON names.

----
type Object struct {
	// Common fields.
	Labels		map[string]string	`json:"labels"`
	Annotations	map[string]string	`json:"annotations"`
	Status		string			`json:"status"`	// inactive|pending|firing|suppressed
	StartsAt	time.Time		`json:"startsAt"`

	// Prometheus fields.
	Value		string	`json:"value"`
	Expression	string	`json:"expression"`
	Fingerprint	string	`json:"fingerprint"`

	// Alertmanager fields.
	EndsAt		time.Time	`json:"endsAt"`
	UpdatedAt	time.Time	`json:"updatedAt"`
	Receivers	[]Receiver	`json:"receivers"`
	InhibitedBy	[]string	`json:"inhibitedBy"`
	SilencedBy	[]string	`json:"silencedBy"`
	GeneratorURL	string		`json:"generatorURL"`
}
----

== Query

A JSON map of string names to string values, matched against alert labels, for example:

----
alert:alert:{"alertname":"KubeStatefulSetReplicasMismatch","container":"kube-rbac-proxy-main","namespace":"openshift-logging"}
----

== Store

A client of Prometheus and/or AlertManager. Store configuration:

----
domain: alert
metrics: PROMETHEUS_URL
alertmanager: ALERTMANAGER_URL
----

Either or both of `metrics` or `alertmanager` may be present.

= Domain `k8s`

Domain `k8s` implements Kubernetes resources stored in a Kube API server.

== Class

A k8s class corresponds to a kind of Kubernetes resource, the class name is `KIND.VERSION.GROUP` VERSION and/or GROUP can be omitted if there is no ambiguity. Example class names: `k8s:Pod.v1`, `ks8:Pod`, `k8s:Deployment.v1.apps`, `k8s:Deployment.apps`, `k8s:Deployment`

== Object

Objects are represented by the standard Go types used by `k8s.io/client-go/api`, and by Kube-generated CRD struct types. Rules starting from the k8s domain should use the capitalized Go field names rather than the lowercase JSON field names.

== Query

Queries are the JSON-serialized form of this struct:

----
type Query struct {
	// Namespace restricts the search to a namespace.
	Namespace	string	`json:"namespace,omitempty"`
	Name		string	`json:"name,omitempty"`
	// Labels restricts the search to objects with matching label values (optional)
	Labels	client.MatchingLabels	`json:"labels,omitempty"`
	// Fields restricts the search to objects with matching field values (optional)
	Fields	client.MatchingFields	`json:"fields,omitempty"`
	// contains filtered or unexported fields
}
----

For example:

----
k8s:Pod.v1.:{"namespace":"openshift-cluster-version","name":"cluster-version-operator-8d86bcb65-btlgn"}
----

== Store

k8s stores connects to the current logged-in Kubernetes cluster, no other configuration is needed than:

----
domain: k8s
----

Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE[https://github.com/korrel8r/korrel8r/blob/main/LICENSE]

== Template Functions

----
k8sClass
    Takes string arguments (apiVersion, kind).
    Returns the korrel8r.Class implied by the arguments, or an error.
----

= Domain `log`

Domain `log` is a domain for openshift-logging ViaQ logs stored in Loki or LokiStack.

== Class

There are 3 classes corresponding to the 3 openshift logging log types:

----
log:application
log:infrastructure
log:audit
----

== Object

A log object is a JSON map\[string]any in ViaQ format.

== Query

A query is a https://grafana.com/docs/loki/latest/query/[LogQL] query string, prefixed by the logging class, for example:

----
log:infrastructure:{ kubernetes_namespace_name="openshift-cluster-version", kubernetes_pod_name=~".*-operator-.*" }
----

== Store

To connect to a lokiStack store use this configuration:

----
domain: log
lokistack: URL_OF_LOKISTACK_PROXY
----

To connect to plain loki store use:

----
domain: log
loki: URL_OF_LOKI
----

Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE[https://github.com/korrel8r/korrel8r/blob/main/LICENSE]

== Template Functions

----
logTypeForNamespace
    Takes a namespace string argument.
    Returns the log type ("application" or "infrastructure") of a container in the namespace.

logSafeLabel
    Convert the string argument into a  safe label containing only alphanumerics '_' and ':'.
----

= Domain `metric`

Domain `metric` represents Prometheus metric time-series as objects.

== Class

There is only one class: `metric:metric`

== Object

A https://pkg.go.dev/github.com/prometheus/common@v0.45.0/model#Metric[Metric] is a time series identified by a label set. Korrel8r does not consider load the sample data for a time series, or use it in rules. If a korrel8r search time constraints, then metrics that have no values that meet the constraint are ignored.

== Query

Query data is a PromQL https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors[instant vector selector], for example:

----
metric:metric:http_requests_total{environment=~"staging|testing",method!="GET"}
----

== Store

Prometheus is the store, store configuration:

----
domain: metric
metric: URL_OF_PROMETHEUS
----

= Domain `netflow`

Domain `netflow` is a domain for network observability flow events stored in Loki or LokiStack.

== Class

There is a single class `netflow:network`

== Object

A log object is a JSON `map\[string]any` in https://docs.openshift.com/container-platform/latest/observability/network_observability/json-flows-format-reference.html[NetFlow] format.

== Query

A query is a https://grafana.com/docs/loki/latest/query/[LogQL] query string, prefixed by `netflow:network:`, for example:

----
netflow:network:{SrcK8S_Type="Pod", SrcK8S_Namespace="myNamespace"}
----

== Store

To connect to a netflow lokiStack store use this configuration:

----
domain: netflow
lokistack: URL_OF_LOKISTACK_PROXY
----

To connect to plain loki store use:

----
domain: netflow
loki: URL_OF_LOKI
----

= Domain `trace`

Domain `trace` is a domain for https://opentelemetry.io/docs/concepts/signals/traces/[OpenTelemetry traces], stored in https://grafana.com/docs/tempo/latest/[Tempo].

FIXME Re-write review all public godoc, rewrite package doc, explain OTEL relationships, link to spec.

== TODO rewrite

== Class

There is a single class `trace:span`. A _span_ is the basic unit of work in a trace. A _trace_ is the set of all spans with the same `traceID`.

== Object

A span object is an OpenTelemetry trace in the form of a `map\[string]any

== Query

A query is a https://grafana.com/docs/tempo/latest/traceql/[TraceQL] query string, prefixed by `trace:trace:`, for example:

----
trace:trace:{resource.k8s.namespace.name="tracing-app-k6"}
----

== Store

To connect to a tempoStack store use this configuration:

----
domain: trace
tempostack: URL_OF_TEMPOSTACK_PROXY
----

To connect to plain tempo store use:

----
domain: trace
tempo: URL_OF_TEMPO
----
