[id="background"]
= Background

Many observability tools and observable systems have their own vocabularies or _data models_ that describe the components being observed and the associated data.

For example, consider a Kubernetes pod, which is the basic unit of execution in a Kubernetes cluster. Pods can be identified by a name, but this name is labeled differently in different systems. For example:

* OpenTelemetry tracees: `k8s.pod.name`
* Prometheus metrics: `pod` or `pod_name`
* Red Hat Openshift Container Platform logging subsystem records: `kubernetes.pod_name`

The https://opentelemetry.io/[Open Telemetry Project] aims to create a standard vocabulary. However, in the short to medium term there are many long-lived, widely-used alternative vocabularies in use. There are also multiple storage technologies used to store signal data, and multiple query languages to search them.

Korrel8r addresses this problem by introducing a set of standard concepts, namely:

* xref:index.adoc#about-domains[Domains]
* xref:index.adoc#about-objects[Objects]
* xref:index.adoc#about-rules[Rules]
