[id="index"]
= Korrel8r: Signal Correlation for Kubernetes
Alan Conway
:doctype: book
:toc: left
:keywords: correlation, observability, signal, kubernetes
:copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE
:source-highlighter: rouge
:project: https://github.com/korrel8r/korrel8r
:pages: https://korrel8r.github.io/korrel8r
:icons: font

[NOTE]
====
This documentation is available in {pages}[HTML] and {pages}/ebook.pdf[PDF] format.

Software is available from the {project}[Korrel8r project].
====

Korrel8r is a correlation engine for Kubernetes objects. It provides a REST API for running correlation queries, by using a set of rules that relate objects.

Given a _start_ object, korrel8r searches for a chain of related rules, and finds other related objects. Related objects can be in multiple different back-end stores, and can be encoded using multiple different schemas. Korrel8r can also show the _neighbourhood_ of all data related to an object of interest.

Korrel8r can be run as a plain executable, outside the cluster, and connect to the API server and stores inside the cluster. It can also run as a deployed service inside the cluster.

[id="index-architecture"]
== Korrel8r architecture

include::background.adoc[leveloffset=+2]
include::about-domains.adoc[leveloffset=+2]
include::about-objects.adoc[leveloffset=+2]
include::about-rules.adoc[leveloffset=+2]

// OCP setup / installation docs
include::installing-korrel8r-ocp.adoc[leveloffset=+1]

// User guides
include::using-korrel8r.adoc[leveloffset=+1]

[id="index-api-reference"]
== API reference documentation

include::zz_domains.adoc[leveloffset=+2]
include::zz_rest_api.adoc[leveloffset=+2]
