[id="installing-korrel8r"]
= Installing Korrel8r
include::attributes.adoc[]


[id="installing-korrel8r-ocp"]
==  {rh-ocp}

The following steps install Korrel8r on {rh-ocp} using an operator.footnote:[link:{github}/operator[]].

[TIP]
====
This _may_ work for Kubernetes clusters that do not use {rh-ocp}, provided they have the  link:https://olm.operatorframework.io/[Operator Lifecycle Manager (OLM)]. This has not been tested.
====

The latest version of the {rh-console} has preview features that display correlated data found by Korrel8r.
You can also query or browse the Korrel8r service directly.

.Prerequisites

* You have administrator permissions on an Red{nbsp}Hat OpenShift Container Platform cluster version 4.12 or newer.
* You have installed the link:https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-console_cluster-logging-deploying[Red Hat OpenShift Logging Operator] version 5.8.1 or newer provided by {red-hat}.
* You have installed the link:https://docs.openshift.com/container-platform/latest/logging/cluster-logging-loki.html#logging-loki-gui-install_cluster-logging-loki[Loki Operator] version 5.8.1 or newer provided by Red{nbsp}Hat, and have created a `LokiStack` custom resource (CR).
* You have link:https://docs.openshift.com/container-platform/latest/logging/cluster-logging-deploying.html#configuring-log-storage-cr_cluster-logging-deploying[created a `ClusterLogging` CR that configures LokiStack as the log store].

.Procedure

. Install the link:https://sdk.operatorframework.io/docs/installation/[`operator-sdk` command].
. Create a namespace for Korrel8r by running the following command:
+
[source,terminal]
----
$ oc create namespace korrel8r
----

. Install the Korrel8r Operator by running the following command:
+
[source,terminal]
----
$ operator-sdk -n korrel8r run bundle quay.io/korrel8r/operator-bundle:latest
----
+
.Example output
[source,terminal]
----
INFO[0015] Creating a File-Based Catalog of the bundle "quay.io/korrel8r/operator-bundle:latest"
INFO[0016] Generated a valid File-Based Catalog
INFO[0024] Created registry pod: quay-io-korrel8r-operator-bundle-latest
INFO[0024] Created CatalogSource: korrel8r-catalog
INFO[0024] OperatorGroup "operator-sdk-og" created
INFO[0024] Created Subscription: korrel8r-v0-0-7-sub
INFO[0040] Approved InstallPlan install-bblsw for the Subscription: korrel8r-v0-0-7-sub
INFO[0040] Waiting for ClusterServiceVersion "default/korrel8r.v0.0.7" to reach 'Succeeded' phase
INFO[0040]   Waiting for ClusterServiceVersion "default/korrel8r.v0.0.7" to appear
INFO[0042]   Found ClusterServiceVersion "default/korrel8r.v0.0.7" phase: Pending
INFO[0043]   Found ClusterServiceVersion "default/korrel8r.v0.0.7" phase: Installing
INFO[0064]   Found ClusterServiceVersion "default/korrel8r.v0.0.7" phase: Succeeded
INFO[0064] OLM has successfully installed "korrel8r.v0.0.7"
----

. In the *Administrator* perspective of the Red{nbsp}Hat OpenShift Container Platform web console, navigate to *Operators* -> *Installed Operators*.
. In the *Provided APIs* column, click *Korrel8r*.
. In the *Korrel8RS* page, click *Create Korrel8r*.
. Use the default configuration and click *Create*.
. To enable the preview features in the Console plugin, annotate the `ClusterLogging` CR by running the following command:
+
[source,terminal]
----
oc patch -n openshift-logging --type merge --patch \
'{"metadata":{"annotations":{"logging.openshift.io/preview-korrel8r-console":"enabled"}}}' \
clusterlogging/instance
----

To verify it is working, see xref:using-korrel8r.adoc#using-ocp-console[using the console]

.Removing Korrel8r

* Delete the Operator and custom resource definitions (CRDs) by running the following command:
+
[source,terminal]
----
$ operator-sdk cleanup -n korrel8r korrel8r
----
+
.Example output
[source,terminal]
----
INFO[0001] subscription "korrel8r-v0-0-7-sub" deleted
INFO[0001] customresourcedefinition "korrel8rs.korrel8r.openshift.io" deleted
INFO[0001] clusterserviceversion "korrel8r.v0.0.7" deleted
INFO[0001] catalogsource "korrel8r-catalog" deleted
INFO[0001] operatorgroup "operator-sdk-og" deleted
INFO[0001] Operator "korrel8r" uninstalled
----
