= Using Korrel8r

Korrel8r connects to multiple data _stores_ such as loki for logs, prometheus for metrics, and the kube-API server for cluster resources.
It provides a REST API for running correlation _queries_ using a set of _rules_ that relate object within and between stores.
Korrel8r can be run as a plain executable, outside the cluster, and connect to the API server and stores inside the cluster.
It can also run as a deployed service inside the cluster.

== Configuration

// TODO: default configuration & rules. Configure outside/inside cluster. Link to reference.

== Command Line

// TODO: move from README, use default config.

== Browser

The `korrel8r web` command provides browser access to:

- Interactive queries and correlation graphs `http://localhost:8080/correlate`
- Interactive REST API documentation on `http://localhost:8080/api`

WARNING: The interactive web interface may be dropped in future.
Other consoles or tools acting as korrel8r clients will provide better visualization and processing of results.

== REST Service

// TODO: move from README. Link to reference. Curl examples of API, use swagger UI.
