// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "alert.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// # Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE
// #

//line pkg/rules/quickrules/alert.qtpl:3
package quickrules

//line pkg/rules/quickrules/alert.qtpl:5
import "github.com/korrel8r/korrel8r/pkg/domains/alert"

//line pkg/rules/quickrules/alert.qtpl:6
import "github.com/korrel8r/korrel8r/pkg/rules"

// # AlertToDeployment creates a k8s Deployment query from the deployment labels of an alert.
// name: AlertToDeployment
// start:
//   domain: alert
//   classes: [alert]
// goal:
//   domain: k8s
//   classes: [Deployment.apps]
//

//line pkg/rules/quickrules/alert.qtpl:17
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/rules/quickrules/alert.qtpl:17
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/rules/quickrules/alert.qtpl:17
func StreamAlertToDeployment(qw422016 *qt422016.Writer, o interface{}) {
//line pkg/rules/quickrules/alert.qtpl:17
	qw422016.N().S(`
`)
//line pkg/rules/quickrules/alert.qtpl:19
	a := o.(*alert.Object)
	ns := a.Labels["namespace"]
	name := a.Labels["deployment"]
	if ns == "" || name == "" {
		rules.Fail("AlertToDeployment: missing required deployment labels: %v", a.Labels)
	}

//line pkg/rules/quickrules/alert.qtpl:25
	qw422016.N().S(`
k8s:Deployment.apps:{"namespace":`)
//line pkg/rules/quickrules/alert.qtpl:26
	qw422016.N().Q(ns)
//line pkg/rules/quickrules/alert.qtpl:26
	qw422016.N().S(`,"name":`)
//line pkg/rules/quickrules/alert.qtpl:26
	qw422016.N().Q(name)
//line pkg/rules/quickrules/alert.qtpl:26
	qw422016.N().S(`}
`)
//line pkg/rules/quickrules/alert.qtpl:27
}

//line pkg/rules/quickrules/alert.qtpl:27
func WriteAlertToDeployment(qq422016 qtio422016.Writer, o interface{}) {
//line pkg/rules/quickrules/alert.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/rules/quickrules/alert.qtpl:27
	StreamAlertToDeployment(qw422016, o)
//line pkg/rules/quickrules/alert.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line pkg/rules/quickrules/alert.qtpl:27
}

//line pkg/rules/quickrules/alert.qtpl:27
func AlertToDeployment(o interface{}) string {
//line pkg/rules/quickrules/alert.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/rules/quickrules/alert.qtpl:27
	WriteAlertToDeployment(qb422016, o)
//line pkg/rules/quickrules/alert.qtpl:27
	qs422016 := string(qb422016.B)
//line pkg/rules/quickrules/alert.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/rules/quickrules/alert.qtpl:27
	return qs422016
//line pkg/rules/quickrules/alert.qtpl:27
}
