// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated from quicktemplate rules by hack/gen-applyfuncs.sh. DO NOT EDIT.

package quickrules

import (
	"github.com/korrel8r/korrel8r/pkg/korrel8r"
	"github.com/valyala/quicktemplate"
)

// applyFuncs maps rule names to the generated quicktemplate stream functions that render them.
var applyFuncs = map[string]func(qw *quicktemplate.Writer, start korrel8r.Object){
	"AlertToDaemonSet":            StreamAlertToDaemonSet,
	"AlertToDeployment":           StreamAlertToDeployment,
	"AlertToIncident":             StreamAlertToIncident,
	"AlertToMetric":               StreamAlertToMetric,
	"AlertToPod":                  StreamAlertToPod,
	"AlertToPodDisruptionBudget":  StreamAlertToPodDisruptionBudget,
	"AlertToStatefulSet":          StreamAlertToStatefulSet,
	"AlertToVM":                   StreamAlertToVM,
	"AlertToVMI":                  StreamAlertToVMI,
	"AlertToVmim":                 StreamAlertToVmim,
	"AllToEvent":                  StreamAllToEvent,
	"AllToMetric":                 StreamAllToMetric,
	"ClusterInstanceToOperands":   StreamClusterInstanceToOperands,
	"CRDToInstances":              StreamCRDToInstances,
	"CSVToCRD":                    StreamCSVToCRD,
	"CSVToDeployment":             StreamCSVToDeployment,
	"CSVToPartOf":                 StreamCSVToPartOf,
	"DaemonSetToAlert":            StreamDaemonSetToAlert,
	"DataVolumeToImporterPod":     StreamDataVolumeToImporterPod,
	"DataVolumeToPVC":             StreamDataVolumeToPVC,
	"DependentToOwner":            StreamDependentToOwner,
	"DeploymentToAlert":           StreamDeploymentToAlert,
	"EndpointSliceToService":      StreamEndpointSliceToService,
	"Event2ToAll":                 StreamEvent2ToAll,
	"EventToAll":                  StreamEventToAll,
	"HPAToTarget":                 StreamHPAToTarget,
	"IncidentToAlert":             StreamIncidentToAlert,
	"IngressToService":            StreamIngressToService,
	"InstallPlanToCSV":            StreamInstallPlanToCSV,
	"InstanceToOperands":          StreamInstanceToOperands,
	"K8sDstOwnerToNetflow":        StreamK8sDstOwnerToNetflow,
	"K8sDstToNetflow":             StreamK8sDstToNetflow,
	"K8sSrcOwnerToNetflow":        StreamK8sSrcOwnerToNetflow,
	"K8sSrcToNetflow":             StreamK8sSrcToNetflow,
	"LogToPod":                    StreamLogToPod,
	"MetricToDaemonSet":           StreamMetricToDaemonSet,
	"MetricToDeployment":          StreamMetricToDeployment,
	"MetricToNode":                StreamMetricToNode,
	"MetricToPod":                 StreamMetricToPod,
	"MetricToStatefulSet":         StreamMetricToStatefulSet,
	"NetflowToDstK8s":             StreamNetflowToDstK8s,
	"NetflowToDstK8sOwner":        StreamNetflowToDstK8sOwner,
	"NetflowToSrcK8s":             StreamNetflowToSrcK8s,
	"NetflowToSrcK8sOwner":        StreamNetflowToSrcK8sOwner,
	"NodeToVmi":                   StreamNodeToVmi,
	"OperatorToCRD":               StreamOperatorToCRD,
	"OperatorToCSV":               StreamOperatorToCSV,
	"OperatorToSubscription":      StreamOperatorToSubscription,
	"PodDisruptionBudgetToAlert":  StreamPodDisruptionBudgetToAlert,
	"PodToAlert":                  StreamPodToAlert,
	"PodToConfigMap":              StreamPodToConfigMap,
	"PodToLogs":                   StreamPodToLogs,
	"PodToLokiAlert":              StreamPodToLokiAlert,
	"PodToPVC":                    StreamPodToPVC,
	"PodToSecret":                 StreamPodToSecret,
	"PodToServiceAccount":         StreamPodToServiceAccount,
	"PodToTrace":                  StreamPodToTrace,
	"PVCToPV":                     StreamPVCToPV,
	"PVCToStorageClass":           StreamPVCToStorageClass,
	"PVToPVC":                     StreamPVToPVC,
	"PVToStorageClass":            StreamPVToStorageClass,
	"SelectorToLogs":              StreamSelectorToLogs,
	"SelectorToPods":              StreamSelectorToPods,
	"ServiceToEndpointSlice":      StreamServiceToEndpointSlice,
	"ServiceToLogs":               StreamServiceToLogs,
	"ServiceToPods":               StreamServiceToPods,
	"StatefulSetToAlert":          StreamStatefulSetToAlert,
	"SubscriptionToCatalogSource": StreamSubscriptionToCatalogSource,
	"SubscriptionToCSV":           StreamSubscriptionToCSV,
	"SubscriptionToInstallPlan":   StreamSubscriptionToInstallPlan,
	"TraceToPod":                  StreamTraceToPod,
	"VmExportToPVC":               StreamVmExportToPVC,
	"VmExportToVm":                StreamVmExportToVm,
	"VmExportToVmSnapshot":        StreamVmExportToVmSnapshot,
	"VmimToAlert":                 StreamVmimToAlert,
	"VmimToVmi":                   StreamVmimToVmi,
	"VmiToAlert":                  StreamVmiToAlert,
	"VmiToConfigMap":              StreamVmiToConfigMap,
	"VmiToDataVolume":             StreamVmiToDataVolume,
	"VmiToLogs":                   StreamVmiToLogs,
	"VmiToMetric":                 StreamVmiToMetric,
	"VmiToNetAttachDef":           StreamVmiToNetAttachDef,
	"VmiToNode":                   StreamVmiToNode,
	"VmiToPod":                    StreamVmiToPod,
	"VmiToPVC":                    StreamVmiToPVC,
	"VmiToSecret":                 StreamVmiToSecret,
	"VmiToServiceAccount":         StreamVmiToServiceAccount,
	"VmiToVmim":                   StreamVmiToVmim,
	"VmRestoreToVm":               StreamVmRestoreToVm,
	"VmRestoreToVmSnapshot":       StreamVmRestoreToVmSnapshot,
	"VmSnapshotToVm":              StreamVmSnapshotToVm,
	"VmToAlert":                   StreamVmToAlert,
	"VmToConfigMap":               StreamVmToConfigMap,
	"VmToDataVolume":              StreamVmToDataVolume,
	"VmToInstancetype":            StreamVmToInstancetype,
	"VmToMetric":                  StreamVmToMetric,
	"VmToNetAttachDef":            StreamVmToNetAttachDef,
	"VmToPreference":              StreamVmToPreference,
	"VmToPVC":                     StreamVmToPVC,
	"VmToSecret":                  StreamVmToSecret,
	"VmToServiceAccount":          StreamVmToServiceAccount,
	"VmToVmi":                     StreamVmToVmi,
	"VmToVmRestore":               StreamVmToVmRestore,
	"VmToVmSnapshot":              StreamVmToVmSnapshot,
}
