// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "incident.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line incident.qtpl:1
package quickrules

//line incident.qtpl:3
import "github.com/korrel8r/korrel8r/pkg/domains/alert"

//line incident.qtpl:4
import "github.com/korrel8r/korrel8r/pkg/domains/incident"

// # AlertToIncident finds incidents matching an alert's labels.
// name: AlertToIncident
// start:
//   domain: alert
// goal:
//   domain: incident
//

//line incident.qtpl:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line incident.qtpl:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line incident.qtpl:13
func StreamAlertToIncident(qw422016 *qt422016.Writer, o interface{}) {
//line incident.qtpl:13
	qw422016.N().S(`
`)
//line incident.qtpl:14
	l := o.(*alert.Object).Labels

//line incident.qtpl:14
	qw422016.N().S(`
incident:incident:{"alertLabels":`)
//line incident.qtpl:15
	qw422016.N().S(ToJSON(l))
//line incident.qtpl:15
	qw422016.N().S(`}
`)
//line incident.qtpl:16
}

//line incident.qtpl:16
func WriteAlertToIncident(qq422016 qtio422016.Writer, o interface{}) {
//line incident.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line incident.qtpl:16
	StreamAlertToIncident(qw422016, o)
//line incident.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line incident.qtpl:16
}

//line incident.qtpl:16
func AlertToIncident(o interface{}) string {
//line incident.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line incident.qtpl:16
	WriteAlertToIncident(qb422016, o)
//line incident.qtpl:16
	qs422016 := string(qb422016.B)
//line incident.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line incident.qtpl:16
	return qs422016
//line incident.qtpl:16
}

// # IncidentToAlert finds alerts associated with an incident.
// name: IncidentToAlert
// start:
//   domain: incident
// goal:
//   domain: alert
//

//line incident.qtpl:25
func StreamIncidentToAlert(qw422016 *qt422016.Writer, o interface{}) {
//line incident.qtpl:25
	qw422016.N().S(`
`)
//line incident.qtpl:26
	al := o.(*incident.Object).AlertsLabels
	RequireAll(al)

//line incident.qtpl:26
	qw422016.N().S(`
alert:alert:`)
//line incident.qtpl:27
	qw422016.N().S(ToJSON(al))
//line incident.qtpl:27
	qw422016.N().S(`
`)
//line incident.qtpl:28
}

//line incident.qtpl:28
func WriteIncidentToAlert(qq422016 qtio422016.Writer, o interface{}) {
//line incident.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line incident.qtpl:28
	StreamIncidentToAlert(qw422016, o)
//line incident.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line incident.qtpl:28
}

//line incident.qtpl:28
func IncidentToAlert(o interface{}) string {
//line incident.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line incident.qtpl:28
	WriteIncidentToAlert(qb422016, o)
//line incident.qtpl:28
	qs422016 := string(qb422016.B)
//line incident.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line incident.qtpl:28
	return qs422016
//line incident.qtpl:28
}
