// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "k8s.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line k8s.qtpl:1
package quickrules

//line k8s.qtpl:3
import "github.com/korrel8r/korrel8r/pkg/domains/k8s"

//line k8s.qtpl:4
import "k8s.io/apimachinery/pkg/runtime/schema"

//line k8s.qtpl:5
import "strings"

// # DependentToOwner follows the first ownerReference of any k8s object to its owner.
// name: DependentToOwner
// start:
//   domain: k8s
// goal:
//   domain: k8s
//

//line k8s.qtpl:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line k8s.qtpl:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line k8s.qtpl:14
func StreamDependentToOwner(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:14
	qw422016.N().S(`
`)
//line k8s.qtpl:16
	obj := o.(map[string]any)
	metadata := obj["metadata"].(map[string]any)
	ref := mapSlice(metadata, "ownerReferences")[0].(map[string]any)
	apiVersion := ref["apiVersion"].(string)
	kind := ref["kind"].(string)
	name := ref["name"].(string)
	class := k8s.Class(schema.FromAPIVersionAndKind(apiVersion, kind))
	ns, _ := metadata["namespace"].(string)

//line k8s.qtpl:24
	qw422016.N().S(`
`)
//line k8s.qtpl:25
	if class.Namespaced() && ns != "" {
//line k8s.qtpl:25
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:26
		qw422016.N().S(class.Name())
//line k8s.qtpl:26
		qw422016.N().S(`:{"namespace":`)
//line k8s.qtpl:26
		qw422016.N().Q(ns)
//line k8s.qtpl:26
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:26
		qw422016.N().Q(name)
//line k8s.qtpl:26
		qw422016.N().S(`}
`)
//line k8s.qtpl:27
	} else {
//line k8s.qtpl:27
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:28
		qw422016.N().S(class.Name())
//line k8s.qtpl:28
		qw422016.N().S(`:{"name":`)
//line k8s.qtpl:28
		qw422016.N().Q(name)
//line k8s.qtpl:28
		qw422016.N().S(`}
`)
//line k8s.qtpl:29
	}
//line k8s.qtpl:29
	qw422016.N().S(`
`)
//line k8s.qtpl:30
}

//line k8s.qtpl:30
func WriteDependentToOwner(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:30
	StreamDependentToOwner(qw422016, o)
//line k8s.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:30
}

//line k8s.qtpl:30
func DependentToOwner(o interface{}) string {
//line k8s.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:30
	WriteDependentToOwner(qb422016, o)
//line k8s.qtpl:30
	qs422016 := string(qb422016.B)
//line k8s.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:30
	return qs422016
//line k8s.qtpl:30
}

// # AllToEvent creates a k8s Event query to find events related to any k8s object.
// name: AllToEvent
// start:
//   domain: k8s
// goal:
//   domain: k8s
//   classes: [Event.]
//

//line k8s.qtpl:40
func StreamAllToEvent(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:40
	qw422016.N().S(`
`)
//line k8s.qtpl:42
	_, _, ns, name, kind := k8sMetadata(o)
	apiVersion, _ := o.(map[string]any)["apiVersion"].(string)
	RequireAll(ns, name, kind, apiVersion)

//line k8s.qtpl:45
	qw422016.N().S(`
k8s:Event:{"namespace":`)
//line k8s.qtpl:46
	qw422016.N().Q(ns)
//line k8s.qtpl:46
	qw422016.N().S(`,"fields":{"involvedObject.apiVersion":`)
//line k8s.qtpl:46
	qw422016.N().Q(apiVersion)
//line k8s.qtpl:46
	qw422016.N().S(`,"involvedObject.kind":`)
//line k8s.qtpl:46
	qw422016.N().Q(kind)
//line k8s.qtpl:46
	qw422016.N().S(`,"involvedObject.name":`)
//line k8s.qtpl:46
	qw422016.N().Q(name)
//line k8s.qtpl:46
	qw422016.N().S(`,"involvedObject.namespace":`)
//line k8s.qtpl:46
	qw422016.N().Q(ns)
//line k8s.qtpl:46
	qw422016.N().S(`}}
`)
//line k8s.qtpl:47
}

//line k8s.qtpl:47
func WriteAllToEvent(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:47
	StreamAllToEvent(qw422016, o)
//line k8s.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:47
}

//line k8s.qtpl:47
func AllToEvent(o interface{}) string {
//line k8s.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:47
	WriteAllToEvent(qb422016, o)
//line k8s.qtpl:47
	qs422016 := string(qb422016.B)
//line k8s.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:47
	return qs422016
//line k8s.qtpl:47
}

// # AllToMetric creates a metric query from any k8s object using namespace and kind.
// name: AllToMetric
// start:
//   domain: k8s
// goal:
//   domain: metric
//   classes: [metric]
//

//line k8s.qtpl:57
func StreamAllToMetric(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:57
	qw422016.N().S(`
`)
//line k8s.qtpl:59
	_, _, ns, name, kind := k8sMetadata(o)
	RequireAll(ns, name, kind)

//line k8s.qtpl:61
	qw422016.N().S(`
metric:metric:{namespace=`)
//line k8s.qtpl:62
	qw422016.N().Q(ns)
//line k8s.qtpl:62
	qw422016.N().S(`,`)
//line k8s.qtpl:62
	qw422016.N().S(strings.ToLower(kind))
//line k8s.qtpl:62
	qw422016.N().S(`=`)
//line k8s.qtpl:62
	qw422016.N().Q(name)
//line k8s.qtpl:62
	qw422016.N().S(`}
`)
//line k8s.qtpl:63
}

//line k8s.qtpl:63
func WriteAllToMetric(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:63
	StreamAllToMetric(qw422016, o)
//line k8s.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:63
}

//line k8s.qtpl:63
func AllToMetric(o interface{}) string {
//line k8s.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:63
	WriteAllToMetric(qb422016, o)
//line k8s.qtpl:63
	qs422016 := string(qb422016.B)
//line k8s.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:63
	return qs422016
//line k8s.qtpl:63
}

// # SelectorToPods finds Pods matching the selector of a k8s workload resource.
// name: SelectorToPods
// start:
//   domain: k8s
//   classes:
//     - ReplicationController
//     - DaemonSet.apps
//     - Deployment.apps
//     - ReplicaSet.apps
//     - StatefulSet.apps
//     - Job.batch
//     - PodDisruptionBudget.policy
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line k8s.qtpl:81
func StreamSelectorToPods(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:81
	qw422016.N().S(`
`)
//line k8s.qtpl:83
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	matchLabels := obj["spec"].(map[string]any)["selector"].(map[string]any)["matchLabels"]
	RequireAll(matchLabels)

//line k8s.qtpl:87
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line k8s.qtpl:88
	qw422016.N().Q(ns)
//line k8s.qtpl:88
	qw422016.N().S(`,"labels":`)
//line k8s.qtpl:88
	qw422016.N().S(ToJSON(matchLabels))
//line k8s.qtpl:88
	qw422016.N().S(`}
`)
//line k8s.qtpl:89
}

//line k8s.qtpl:89
func WriteSelectorToPods(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:89
	StreamSelectorToPods(qw422016, o)
//line k8s.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:89
}

//line k8s.qtpl:89
func SelectorToPods(o interface{}) string {
//line k8s.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:89
	WriteSelectorToPods(qb422016, o)
//line k8s.qtpl:89
	qs422016 := string(qb422016.B)
//line k8s.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:89
	return qs422016
//line k8s.qtpl:89
}

// # SelectorToLogs finds logs for pods matching the selector of a k8s workload resource.
// name: SelectorToLogs
// start:
//   domain: k8s
//   classes:
//     - ReplicationController
//     - DaemonSet.apps
//     - Deployment.apps
//     - ReplicaSet.apps
//     - StatefulSet.apps
//     - Job.batch
//     - PodDisruptionBudget.policy
// goal:
//   domain: log
//

//line k8s.qtpl:106
func StreamSelectorToLogs(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:106
	qw422016.N().S(`
`)
//line k8s.qtpl:108
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	matchLabels := obj["spec"].(map[string]any)["selector"].(map[string]any)["matchLabels"]
	RequireAll(matchLabels)

//line k8s.qtpl:112
	qw422016.N().S(`
log:`)
//line k8s.qtpl:113
	qw422016.N().S(logTypeForNamespace(ns))
//line k8s.qtpl:113
	qw422016.N().S(`:{"namespace":`)
//line k8s.qtpl:113
	qw422016.N().Q(ns)
//line k8s.qtpl:113
	qw422016.N().S(`,"labels":`)
//line k8s.qtpl:113
	qw422016.N().S(ToJSON(matchLabels))
//line k8s.qtpl:113
	qw422016.N().S(`}
`)
//line k8s.qtpl:114
}

//line k8s.qtpl:114
func WriteSelectorToLogs(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:114
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:114
	StreamSelectorToLogs(qw422016, o)
//line k8s.qtpl:114
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:114
}

//line k8s.qtpl:114
func SelectorToLogs(o interface{}) string {
//line k8s.qtpl:114
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:114
	WriteSelectorToLogs(qb422016, o)
//line k8s.qtpl:114
	qs422016 := string(qb422016.B)
//line k8s.qtpl:114
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:114
	return qs422016
//line k8s.qtpl:114
}

// # K8sSrcToNetflow finds netflows where the k8s resource is the source.
// name: K8sSrcToNetflow
// start:
//   domain: k8s
//   classes: [Node, Pod, Service]
// goal:
//   domain: netflow
//   classes: [network]
//

//line k8s.qtpl:125
func StreamK8sSrcToNetflow(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:125
	qw422016.N().S(`
`)
//line k8s.qtpl:127
	_, _, ns, name, kind := k8sMetadata(o)
	RequireAll(name, kind)

//line k8s.qtpl:129
	qw422016.N().S(`
netflow:network:{SrcK8S_Type=`)
//line k8s.qtpl:130
	qw422016.N().Q(kind)
//line k8s.qtpl:130
	qw422016.N().S(`, SrcK8S_Namespace=`)
//line k8s.qtpl:130
	qw422016.N().Q(ns)
//line k8s.qtpl:130
	qw422016.N().S(`} | json | SrcK8S_Name=`)
//line k8s.qtpl:130
	qw422016.N().Q(name)
//line k8s.qtpl:130
	qw422016.N().S(`
`)
//line k8s.qtpl:131
}

//line k8s.qtpl:131
func WriteK8sSrcToNetflow(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:131
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:131
	StreamK8sSrcToNetflow(qw422016, o)
//line k8s.qtpl:131
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:131
}

//line k8s.qtpl:131
func K8sSrcToNetflow(o interface{}) string {
//line k8s.qtpl:131
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:131
	WriteK8sSrcToNetflow(qb422016, o)
//line k8s.qtpl:131
	qs422016 := string(qb422016.B)
//line k8s.qtpl:131
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:131
	return qs422016
//line k8s.qtpl:131
}

// # K8sSrcOwnerToNetflow finds netflows where the k8s owner resource is the source owner.
// name: K8sSrcOwnerToNetflow
// start:
//   domain: k8s
//   classes:
//     - DaemonSet.apps
//     - Deployment.apps
//     - ReplicaSet.apps
//     - StatefulSet.apps
// goal:
//   domain: netflow
//   classes: [network]
//

//line k8s.qtpl:146
func StreamK8sSrcOwnerToNetflow(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:146
	qw422016.N().S(`
`)
//line k8s.qtpl:148
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line k8s.qtpl:150
	qw422016.N().S(`
netflow:network:{SrcK8S_Namespace=`)
//line k8s.qtpl:151
	qw422016.N().Q(ns)
//line k8s.qtpl:151
	qw422016.N().S(`, SrcK8S_OwnerName=`)
//line k8s.qtpl:151
	qw422016.N().Q(name)
//line k8s.qtpl:151
	qw422016.N().S(`}
`)
//line k8s.qtpl:152
}

//line k8s.qtpl:152
func WriteK8sSrcOwnerToNetflow(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:152
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:152
	StreamK8sSrcOwnerToNetflow(qw422016, o)
//line k8s.qtpl:152
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:152
}

//line k8s.qtpl:152
func K8sSrcOwnerToNetflow(o interface{}) string {
//line k8s.qtpl:152
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:152
	WriteK8sSrcOwnerToNetflow(qb422016, o)
//line k8s.qtpl:152
	qs422016 := string(qb422016.B)
//line k8s.qtpl:152
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:152
	return qs422016
//line k8s.qtpl:152
}

// # K8sDstToNetflow finds netflows where the k8s resource is the destination.
// name: K8sDstToNetflow
// start:
//   domain: k8s
//   classes: [Node, Pod, Service]
// goal:
//   domain: netflow
//   classes: [network]
//

//line k8s.qtpl:163
func StreamK8sDstToNetflow(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:163
	qw422016.N().S(`
`)
//line k8s.qtpl:165
	_, _, ns, name, kind := k8sMetadata(o)
	RequireAll(name, kind)

//line k8s.qtpl:167
	qw422016.N().S(`
netflow:network:{DstK8S_Type=`)
//line k8s.qtpl:168
	qw422016.N().Q(kind)
//line k8s.qtpl:168
	qw422016.N().S(`, DstK8S_Namespace=`)
//line k8s.qtpl:168
	qw422016.N().Q(ns)
//line k8s.qtpl:168
	qw422016.N().S(`} | json | DstK8S_Name=`)
//line k8s.qtpl:168
	qw422016.N().Q(name)
//line k8s.qtpl:168
	qw422016.N().S(`
`)
//line k8s.qtpl:169
}

//line k8s.qtpl:169
func WriteK8sDstToNetflow(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:169
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:169
	StreamK8sDstToNetflow(qw422016, o)
//line k8s.qtpl:169
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:169
}

//line k8s.qtpl:169
func K8sDstToNetflow(o interface{}) string {
//line k8s.qtpl:169
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:169
	WriteK8sDstToNetflow(qb422016, o)
//line k8s.qtpl:169
	qs422016 := string(qb422016.B)
//line k8s.qtpl:169
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:169
	return qs422016
//line k8s.qtpl:169
}

// # K8sDstOwnerToNetflow finds netflows where the k8s owner resource is the destination owner.
// name: K8sDstOwnerToNetflow
// start:
//   domain: k8s
//   classes:
//     - DaemonSet.apps
//     - Deployment.apps
//     - ReplicaSet.apps
//     - StatefulSet.apps
// goal:
//   domain: netflow
//   classes: [network]
//

//line k8s.qtpl:184
func StreamK8sDstOwnerToNetflow(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:184
	qw422016.N().S(`
`)
//line k8s.qtpl:186
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line k8s.qtpl:188
	qw422016.N().S(`
netflow:network:{DstK8S_Namespace=`)
//line k8s.qtpl:189
	qw422016.N().Q(ns)
//line k8s.qtpl:189
	qw422016.N().S(`, DstK8S_OwnerName=`)
//line k8s.qtpl:189
	qw422016.N().Q(name)
//line k8s.qtpl:189
	qw422016.N().S(`}
`)
//line k8s.qtpl:190
}

//line k8s.qtpl:190
func WriteK8sDstOwnerToNetflow(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:190
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:190
	StreamK8sDstOwnerToNetflow(qw422016, o)
//line k8s.qtpl:190
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:190
}

//line k8s.qtpl:190
func K8sDstOwnerToNetflow(o interface{}) string {
//line k8s.qtpl:190
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:190
	WriteK8sDstOwnerToNetflow(qb422016, o)
//line k8s.qtpl:190
	qs422016 := string(qb422016.B)
//line k8s.qtpl:190
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:190
	return qs422016
//line k8s.qtpl:190
}

// # ServiceToPods finds Pods matching the selector of a k8s Service.
// name: ServiceToPods
// start:
//   domain: k8s
//   classes: [Service]
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line k8s.qtpl:201
func StreamServiceToPods(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:201
	qw422016.N().S(`
`)
//line k8s.qtpl:203
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	selector := obj["spec"].(map[string]any)["selector"]
	RequireAll(selector)

//line k8s.qtpl:207
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line k8s.qtpl:208
	qw422016.N().Q(ns)
//line k8s.qtpl:208
	qw422016.N().S(`,"labels":`)
//line k8s.qtpl:208
	qw422016.N().S(ToJSON(selector))
//line k8s.qtpl:208
	qw422016.N().S(`}
`)
//line k8s.qtpl:209
}

//line k8s.qtpl:209
func WriteServiceToPods(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:209
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:209
	StreamServiceToPods(qw422016, o)
//line k8s.qtpl:209
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:209
}

//line k8s.qtpl:209
func ServiceToPods(o interface{}) string {
//line k8s.qtpl:209
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:209
	WriteServiceToPods(qb422016, o)
//line k8s.qtpl:209
	qs422016 := string(qb422016.B)
//line k8s.qtpl:209
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:209
	return qs422016
//line k8s.qtpl:209
}

// # EventToAll correlates a core v1 Event to the resource it references.
// name: EventToAll
// start:
//   domain: k8s
//   classes: [Event.v1]
// goal:
//   domain: k8s
//

//line k8s.qtpl:219
func StreamEventToAll(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:219
	qw422016.N().S(`
`)
//line k8s.qtpl:221
	obj := o.(map[string]any)
	inv := obj["involvedObject"].(map[string]any)
	class := k8s.Class(schema.FromAPIVersionAndKind(inv["apiVersion"].(string), inv["kind"].(string)))
	ns, _ := inv["namespace"].(string)
	name := inv["name"].(string)
	RequireAll(name)

//line k8s.qtpl:227
	qw422016.N().S(`
`)
//line k8s.qtpl:228
	if ns != "" {
//line k8s.qtpl:228
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:229
		qw422016.N().S(class.Name())
//line k8s.qtpl:229
		qw422016.N().S(`:{"namespace":`)
//line k8s.qtpl:229
		qw422016.N().Q(ns)
//line k8s.qtpl:229
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:229
		qw422016.N().Q(name)
//line k8s.qtpl:229
		qw422016.N().S(`}
`)
//line k8s.qtpl:230
	} else {
//line k8s.qtpl:230
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:231
		qw422016.N().S(class.Name())
//line k8s.qtpl:231
		qw422016.N().S(`:{"name":`)
//line k8s.qtpl:231
		qw422016.N().Q(name)
//line k8s.qtpl:231
		qw422016.N().S(`}
`)
//line k8s.qtpl:232
	}
//line k8s.qtpl:232
	qw422016.N().S(`
`)
//line k8s.qtpl:233
}

//line k8s.qtpl:233
func WriteEventToAll(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:233
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:233
	StreamEventToAll(qw422016, o)
//line k8s.qtpl:233
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:233
}

//line k8s.qtpl:233
func EventToAll(o interface{}) string {
//line k8s.qtpl:233
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:233
	WriteEventToAll(qb422016, o)
//line k8s.qtpl:233
	qs422016 := string(qb422016.B)
//line k8s.qtpl:233
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:233
	return qs422016
//line k8s.qtpl:233
}

// # Event2ToAll correlates a events.k8s.io/v1 Event to the resource it references.
// name: Event2ToAll
// start:
//   domain: k8s
//   classes: [Event.v1.events.k8s.io]
// goal:
//   domain: k8s
//

//line k8s.qtpl:243
func StreamEvent2ToAll(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:243
	qw422016.N().S(`
`)
//line k8s.qtpl:245
	obj := o.(map[string]any)
	reg := obj["regarding"].(map[string]any)
	class := k8s.Class(schema.FromAPIVersionAndKind(reg["apiVersion"].(string), reg["kind"].(string)))
	ns, _ := reg["namespace"].(string)
	name := reg["name"].(string)
	RequireAll(name)

//line k8s.qtpl:251
	qw422016.N().S(`
`)
//line k8s.qtpl:252
	if ns != "" {
//line k8s.qtpl:252
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:253
		qw422016.N().S(class.Name())
//line k8s.qtpl:253
		qw422016.N().S(`:{"namespace":`)
//line k8s.qtpl:253
		qw422016.N().Q(ns)
//line k8s.qtpl:253
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:253
		qw422016.N().Q(name)
//line k8s.qtpl:253
		qw422016.N().S(`}
`)
//line k8s.qtpl:254
	} else {
//line k8s.qtpl:254
		qw422016.N().S(`
k8s:`)
//line k8s.qtpl:255
		qw422016.N().S(class.Name())
//line k8s.qtpl:255
		qw422016.N().S(`:{"name":`)
//line k8s.qtpl:255
		qw422016.N().Q(name)
//line k8s.qtpl:255
		qw422016.N().S(`}
`)
//line k8s.qtpl:256
	}
//line k8s.qtpl:256
	qw422016.N().S(`
`)
//line k8s.qtpl:257
}

//line k8s.qtpl:257
func WriteEvent2ToAll(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:257
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:257
	StreamEvent2ToAll(qw422016, o)
//line k8s.qtpl:257
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:257
}

//line k8s.qtpl:257
func Event2ToAll(o interface{}) string {
//line k8s.qtpl:257
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:257
	WriteEvent2ToAll(qb422016, o)
//line k8s.qtpl:257
	qs422016 := string(qb422016.B)
//line k8s.qtpl:257
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:257
	return qs422016
//line k8s.qtpl:257
}

// # PodToPVC finds PersistentVolumeClaims referenced by a Pod's volumes.
// name: PodToPVC
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line k8s.qtpl:268
func StreamPodToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:268
	qw422016.N().S(`
`)
//line k8s.qtpl:270
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line k8s.qtpl:273
	qw422016.N().S(`
`)
//line k8s.qtpl:274
	for _, v := range volumes {
//line k8s.qtpl:274
		qw422016.N().S(`
`)
//line k8s.qtpl:275
		vol := v.(map[string]any)

//line k8s.qtpl:275
		qw422016.N().S(`
`)
//line k8s.qtpl:276
		if pvc, ok := vol["persistentVolumeClaim"].(map[string]any); ok {
//line k8s.qtpl:276
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line k8s.qtpl:277
			qw422016.N().Q(ns)
//line k8s.qtpl:277
			qw422016.N().S(`,"name":`)
//line k8s.qtpl:277
			qw422016.N().Q(pvc["claimName"].(string))
//line k8s.qtpl:277
			qw422016.N().S(`}
`)
//line k8s.qtpl:278
		}
//line k8s.qtpl:278
		qw422016.N().S(`
`)
//line k8s.qtpl:279
	}
//line k8s.qtpl:279
	qw422016.N().S(`
`)
//line k8s.qtpl:280
}

//line k8s.qtpl:280
func WritePodToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:280
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:280
	StreamPodToPVC(qw422016, o)
//line k8s.qtpl:280
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:280
}

//line k8s.qtpl:280
func PodToPVC(o interface{}) string {
//line k8s.qtpl:280
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:280
	WritePodToPVC(qb422016, o)
//line k8s.qtpl:280
	qs422016 := string(qb422016.B)
//line k8s.qtpl:280
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:280
	return qs422016
//line k8s.qtpl:280
}

// # PodToConfigMap finds ConfigMaps referenced by a Pod's volumes.
// name: PodToConfigMap
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: k8s
//   classes: [ConfigMap]
//

//line k8s.qtpl:291
func StreamPodToConfigMap(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:291
	qw422016.N().S(`
`)
//line k8s.qtpl:293
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line k8s.qtpl:296
	qw422016.N().S(`
`)
//line k8s.qtpl:297
	for _, v := range volumes {
//line k8s.qtpl:297
		qw422016.N().S(`
`)
//line k8s.qtpl:298
		vol := v.(map[string]any)

//line k8s.qtpl:298
		qw422016.N().S(`
`)
//line k8s.qtpl:299
		if cm, ok := vol["configMap"].(map[string]any); ok {
//line k8s.qtpl:299
			qw422016.N().S(`
k8s:ConfigMap:{"namespace":`)
//line k8s.qtpl:300
			qw422016.N().Q(ns)
//line k8s.qtpl:300
			qw422016.N().S(`,"name":`)
//line k8s.qtpl:300
			qw422016.N().Q(cm["name"].(string))
//line k8s.qtpl:300
			qw422016.N().S(`}
`)
//line k8s.qtpl:301
		}
//line k8s.qtpl:301
		qw422016.N().S(`
`)
//line k8s.qtpl:302
	}
//line k8s.qtpl:302
	qw422016.N().S(`
`)
//line k8s.qtpl:303
}

//line k8s.qtpl:303
func WritePodToConfigMap(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:303
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:303
	StreamPodToConfigMap(qw422016, o)
//line k8s.qtpl:303
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:303
}

//line k8s.qtpl:303
func PodToConfigMap(o interface{}) string {
//line k8s.qtpl:303
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:303
	WritePodToConfigMap(qb422016, o)
//line k8s.qtpl:303
	qs422016 := string(qb422016.B)
//line k8s.qtpl:303
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:303
	return qs422016
//line k8s.qtpl:303
}

// # PodToSecret finds Secrets referenced by a Pod's volumes.
// name: PodToSecret
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: k8s
//   classes: [Secret]
//

//line k8s.qtpl:314
func StreamPodToSecret(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:314
	qw422016.N().S(`
`)
//line k8s.qtpl:316
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line k8s.qtpl:319
	qw422016.N().S(`
`)
//line k8s.qtpl:320
	for _, v := range volumes {
//line k8s.qtpl:320
		qw422016.N().S(`
`)
//line k8s.qtpl:321
		vol := v.(map[string]any)

//line k8s.qtpl:321
		qw422016.N().S(`
`)
//line k8s.qtpl:322
		if sec, ok := vol["secret"].(map[string]any); ok {
//line k8s.qtpl:322
			qw422016.N().S(`
k8s:Secret:{"namespace":`)
//line k8s.qtpl:323
			qw422016.N().Q(ns)
//line k8s.qtpl:323
			qw422016.N().S(`,"name":`)
//line k8s.qtpl:323
			qw422016.N().Q(sec["secretName"].(string))
//line k8s.qtpl:323
			qw422016.N().S(`}
`)
//line k8s.qtpl:324
		}
//line k8s.qtpl:324
		qw422016.N().S(`
`)
//line k8s.qtpl:325
	}
//line k8s.qtpl:325
	qw422016.N().S(`
`)
//line k8s.qtpl:326
}

//line k8s.qtpl:326
func WritePodToSecret(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:326
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:326
	StreamPodToSecret(qw422016, o)
//line k8s.qtpl:326
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:326
}

//line k8s.qtpl:326
func PodToSecret(o interface{}) string {
//line k8s.qtpl:326
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:326
	WritePodToSecret(qb422016, o)
//line k8s.qtpl:326
	qs422016 := string(qb422016.B)
//line k8s.qtpl:326
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:326
	return qs422016
//line k8s.qtpl:326
}

// # PodToServiceAccount finds the ServiceAccount used by a Pod.
// name: PodToServiceAccount
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: k8s
//   classes: [ServiceAccount]
//

//line k8s.qtpl:337
func StreamPodToServiceAccount(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:337
	qw422016.N().S(`
`)
//line k8s.qtpl:339
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	sa := Require(obj["spec"].(map[string]any)["serviceAccountName"].(string))

//line k8s.qtpl:342
	qw422016.N().S(`
k8s:ServiceAccount:{"namespace":`)
//line k8s.qtpl:343
	qw422016.N().Q(ns)
//line k8s.qtpl:343
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:343
	qw422016.N().Q(sa)
//line k8s.qtpl:343
	qw422016.N().S(`}
`)
//line k8s.qtpl:344
}

//line k8s.qtpl:344
func WritePodToServiceAccount(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:344
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:344
	StreamPodToServiceAccount(qw422016, o)
//line k8s.qtpl:344
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:344
}

//line k8s.qtpl:344
func PodToServiceAccount(o interface{}) string {
//line k8s.qtpl:344
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:344
	WritePodToServiceAccount(qb422016, o)
//line k8s.qtpl:344
	qs422016 := string(qb422016.B)
//line k8s.qtpl:344
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:344
	return qs422016
//line k8s.qtpl:344
}

// # ServiceToEndpointSlice finds EndpointSlices for a Service.
// name: ServiceToEndpointSlice
// start:
//   domain: k8s
//   classes: [Service]
// goal:
//   domain: k8s
//   classes: [EndpointSlice.discovery.k8s.io]
//

//line k8s.qtpl:355
func StreamServiceToEndpointSlice(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:355
	qw422016.N().S(`
`)
//line k8s.qtpl:356
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line k8s.qtpl:356
	qw422016.N().S(`
k8s:EndpointSlice.discovery.k8s.io:{"namespace":`)
//line k8s.qtpl:357
	qw422016.N().Q(ns)
//line k8s.qtpl:357
	qw422016.N().S(`,"labels":{"kubernetes.io/service-name":`)
//line k8s.qtpl:357
	qw422016.N().Q(name)
//line k8s.qtpl:357
	qw422016.N().S(`}}
`)
//line k8s.qtpl:358
}

//line k8s.qtpl:358
func WriteServiceToEndpointSlice(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:358
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:358
	StreamServiceToEndpointSlice(qw422016, o)
//line k8s.qtpl:358
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:358
}

//line k8s.qtpl:358
func ServiceToEndpointSlice(o interface{}) string {
//line k8s.qtpl:358
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:358
	WriteServiceToEndpointSlice(qb422016, o)
//line k8s.qtpl:358
	qs422016 := string(qb422016.B)
//line k8s.qtpl:358
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:358
	return qs422016
//line k8s.qtpl:358
}

// # EndpointSliceToService finds the Service for an EndpointSlice.
// name: EndpointSliceToService
// start:
//   domain: k8s
//   classes: [EndpointSlice.discovery.k8s.io]
// goal:
//   domain: k8s
//   classes: [Service]
//

//line k8s.qtpl:369
func StreamEndpointSliceToService(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:369
	qw422016.N().S(`
`)
//line k8s.qtpl:371
	_, metadata, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	labels := metadata["labels"].(map[string]any)
	svcName := Require(labels["kubernetes.io/service-name"].(string))

//line k8s.qtpl:375
	qw422016.N().S(`
k8s:Service:{"namespace":`)
//line k8s.qtpl:376
	qw422016.N().Q(ns)
//line k8s.qtpl:376
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:376
	qw422016.N().Q(svcName)
//line k8s.qtpl:376
	qw422016.N().S(`}
`)
//line k8s.qtpl:377
}

//line k8s.qtpl:377
func WriteEndpointSliceToService(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:377
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:377
	StreamEndpointSliceToService(qw422016, o)
//line k8s.qtpl:377
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:377
}

//line k8s.qtpl:377
func EndpointSliceToService(o interface{}) string {
//line k8s.qtpl:377
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:377
	WriteEndpointSliceToService(qb422016, o)
//line k8s.qtpl:377
	qs422016 := string(qb422016.B)
//line k8s.qtpl:377
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:377
	return qs422016
//line k8s.qtpl:377
}

// # PVCToPV finds the PersistentVolume bound to a PersistentVolumeClaim.
// name: PVCToPV
// start:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
// goal:
//   domain: k8s
//   classes: [PersistentVolume]
//

//line k8s.qtpl:388
func StreamPVCToPV(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:388
	qw422016.N().S(`
`)
//line k8s.qtpl:390
	obj := o.(map[string]any)
	volName := Require(obj["spec"].(map[string]any)["volumeName"].(string))

//line k8s.qtpl:392
	qw422016.N().S(`
k8s:PersistentVolume:{"name":`)
//line k8s.qtpl:393
	qw422016.N().Q(volName)
//line k8s.qtpl:393
	qw422016.N().S(`}
`)
//line k8s.qtpl:394
}

//line k8s.qtpl:394
func WritePVCToPV(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:394
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:394
	StreamPVCToPV(qw422016, o)
//line k8s.qtpl:394
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:394
}

//line k8s.qtpl:394
func PVCToPV(o interface{}) string {
//line k8s.qtpl:394
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:394
	WritePVCToPV(qb422016, o)
//line k8s.qtpl:394
	qs422016 := string(qb422016.B)
//line k8s.qtpl:394
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:394
	return qs422016
//line k8s.qtpl:394
}

// # PVToPVC finds the PersistentVolumeClaim bound to a PersistentVolume.
// name: PVToPVC
// start:
//   domain: k8s
//   classes: [PersistentVolume]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line k8s.qtpl:405
func StreamPVToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:405
	qw422016.N().S(`
`)
//line k8s.qtpl:407
	obj := o.(map[string]any)
	ref := obj["spec"].(map[string]any)["claimRef"].(map[string]any)

//line k8s.qtpl:409
	qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line k8s.qtpl:410
	qw422016.N().Q(ref["namespace"].(string))
//line k8s.qtpl:410
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:410
	qw422016.N().Q(ref["name"].(string))
//line k8s.qtpl:410
	qw422016.N().S(`}
`)
//line k8s.qtpl:411
}

//line k8s.qtpl:411
func WritePVToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:411
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:411
	StreamPVToPVC(qw422016, o)
//line k8s.qtpl:411
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:411
}

//line k8s.qtpl:411
func PVToPVC(o interface{}) string {
//line k8s.qtpl:411
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:411
	WritePVToPVC(qb422016, o)
//line k8s.qtpl:411
	qs422016 := string(qb422016.B)
//line k8s.qtpl:411
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:411
	return qs422016
//line k8s.qtpl:411
}

// # PVToStorageClass finds the StorageClass for a PersistentVolume.
// name: PVToStorageClass
// start:
//   domain: k8s
//   classes: [PersistentVolume]
// goal:
//   domain: k8s
//   classes: [StorageClass.storage.k8s.io]
//

//line k8s.qtpl:422
func StreamPVToStorageClass(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:422
	qw422016.N().S(`
`)
//line k8s.qtpl:424
	obj := o.(map[string]any)
	sc := Require(obj["spec"].(map[string]any)["storageClassName"].(string))

//line k8s.qtpl:426
	qw422016.N().S(`
k8s:StorageClass.storage.k8s.io:{"name":`)
//line k8s.qtpl:427
	qw422016.N().Q(sc)
//line k8s.qtpl:427
	qw422016.N().S(`}
`)
//line k8s.qtpl:428
}

//line k8s.qtpl:428
func WritePVToStorageClass(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:428
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:428
	StreamPVToStorageClass(qw422016, o)
//line k8s.qtpl:428
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:428
}

//line k8s.qtpl:428
func PVToStorageClass(o interface{}) string {
//line k8s.qtpl:428
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:428
	WritePVToStorageClass(qb422016, o)
//line k8s.qtpl:428
	qs422016 := string(qb422016.B)
//line k8s.qtpl:428
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:428
	return qs422016
//line k8s.qtpl:428
}

// # PVCToStorageClass finds the StorageClass for a PersistentVolumeClaim.
// name: PVCToStorageClass
// start:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
// goal:
//   domain: k8s
//   classes: [StorageClass.storage.k8s.io]
//

//line k8s.qtpl:439
func StreamPVCToStorageClass(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:439
	qw422016.N().S(`
`)
//line k8s.qtpl:441
	obj := o.(map[string]any)
	sc := Require(obj["spec"].(map[string]any)["storageClassName"].(string))

//line k8s.qtpl:443
	qw422016.N().S(`
k8s:StorageClass.storage.k8s.io:{"name":`)
//line k8s.qtpl:444
	qw422016.N().Q(sc)
//line k8s.qtpl:444
	qw422016.N().S(`}
`)
//line k8s.qtpl:445
}

//line k8s.qtpl:445
func WritePVCToStorageClass(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:445
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:445
	StreamPVCToStorageClass(qw422016, o)
//line k8s.qtpl:445
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:445
}

//line k8s.qtpl:445
func PVCToStorageClass(o interface{}) string {
//line k8s.qtpl:445
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:445
	WritePVCToStorageClass(qb422016, o)
//line k8s.qtpl:445
	qs422016 := string(qb422016.B)
//line k8s.qtpl:445
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:445
	return qs422016
//line k8s.qtpl:445
}

// # SubscriptionToCSV finds the ClusterServiceVersion for an OLM Subscription.
// name: SubscriptionToCSV
// start:
//   domain: k8s
//   classes: [Subscription.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:456
func StreamSubscriptionToCSV(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:456
	qw422016.N().S(`
`)
//line k8s.qtpl:458
	obj := o.(map[string]any)
	csv := Require(obj["status"].(map[string]any)["currentCSV"].(string))

//line k8s.qtpl:460
	qw422016.N().S(`
k8s:ClusterServiceVersion.v1alpha1.operators.coreos.com:{"name":`)
//line k8s.qtpl:461
	qw422016.N().Q(csv)
//line k8s.qtpl:461
	qw422016.N().S(`}
`)
//line k8s.qtpl:462
}

//line k8s.qtpl:462
func WriteSubscriptionToCSV(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:462
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:462
	StreamSubscriptionToCSV(qw422016, o)
//line k8s.qtpl:462
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:462
}

//line k8s.qtpl:462
func SubscriptionToCSV(o interface{}) string {
//line k8s.qtpl:462
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:462
	WriteSubscriptionToCSV(qb422016, o)
//line k8s.qtpl:462
	qs422016 := string(qb422016.B)
//line k8s.qtpl:462
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:462
	return qs422016
//line k8s.qtpl:462
}

// # CSVToCRD finds CustomResourceDefinitions owned by a ClusterServiceVersion.
// name: CSVToCRD
// start:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [CustomResourceDefinition.v1.apiextensions.k8s.io]
//

//line k8s.qtpl:473
func StreamCSVToCRD(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:473
	qw422016.N().S(`
`)
//line k8s.qtpl:475
	obj := o.(map[string]any)
	owned := mapSlice(obj["spec"].(map[string]any)["customresourcedefinitions"].(map[string]any), "owned")

//line k8s.qtpl:477
	qw422016.N().S(`
`)
//line k8s.qtpl:478
	for _, item := range owned {
//line k8s.qtpl:478
		qw422016.N().S(`
`)
//line k8s.qtpl:479
		crd := item.(map[string]any)

//line k8s.qtpl:479
		qw422016.N().S(`
k8s:CustomResourceDefinition.apiextensions.k8s.io:{"name":`)
//line k8s.qtpl:480
		qw422016.N().Q(crd["name"].(string))
//line k8s.qtpl:480
		qw422016.N().S(`}
`)
//line k8s.qtpl:481
	}
//line k8s.qtpl:481
	qw422016.N().S(`
`)
//line k8s.qtpl:482
}

//line k8s.qtpl:482
func WriteCSVToCRD(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:482
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:482
	StreamCSVToCRD(qw422016, o)
//line k8s.qtpl:482
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:482
}

//line k8s.qtpl:482
func CSVToCRD(o interface{}) string {
//line k8s.qtpl:482
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:482
	WriteCSVToCRD(qb422016, o)
//line k8s.qtpl:482
	qs422016 := string(qb422016.B)
//line k8s.qtpl:482
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:482
	return qs422016
//line k8s.qtpl:482
}

// # CRDToInstances finds instances of a CustomResourceDefinition.
// name: CRDToInstances
// start:
//   domain: k8s
//   classes: [CustomResourceDefinition.apiextensions.k8s.io]
// goal:
//   domain: k8s
//

//line k8s.qtpl:492
func StreamCRDToInstances(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:492
	qw422016.N().S(`
`)
//line k8s.qtpl:494
	obj := o.(map[string]any)
	spec := obj["spec"].(map[string]any)
	kind := spec["names"].(map[string]any)["kind"].(string)
	version := mapSlice(spec, "versions")[0].(map[string]any)["name"].(string)
	group := spec["group"].(string)

//line k8s.qtpl:499
	qw422016.N().S(`
k8s:`)
//line k8s.qtpl:500
	qw422016.N().S(kind)
//line k8s.qtpl:500
	qw422016.N().S(`.`)
//line k8s.qtpl:500
	qw422016.N().S(version)
//line k8s.qtpl:500
	qw422016.N().S(`.`)
//line k8s.qtpl:500
	qw422016.N().S(group)
//line k8s.qtpl:500
	qw422016.N().S(`:{}
`)
//line k8s.qtpl:501
}

//line k8s.qtpl:501
func WriteCRDToInstances(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:501
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:501
	StreamCRDToInstances(qw422016, o)
//line k8s.qtpl:501
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:501
}

//line k8s.qtpl:501
func CRDToInstances(o interface{}) string {
//line k8s.qtpl:501
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:501
	WriteCRDToInstances(qb422016, o)
//line k8s.qtpl:501
	qs422016 := string(qb422016.B)
//line k8s.qtpl:501
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:501
	return qs422016
//line k8s.qtpl:501
}

// # CSVToDeployment finds Deployments installed by a ClusterServiceVersion.
// name: CSVToDeployment
// start:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [Deployment.apps]
//

//line k8s.qtpl:512
func StreamCSVToDeployment(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:512
	qw422016.N().S(`
`)
//line k8s.qtpl:514
	_, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	obj := o.(map[string]any)
	deployments := mapSlice(obj["spec"].(map[string]any)["install"].(map[string]any)["spec"].(map[string]any), "deployments")

//line k8s.qtpl:518
	qw422016.N().S(`
`)
//line k8s.qtpl:519
	for _, d := range deployments {
//line k8s.qtpl:519
		qw422016.N().S(`
`)
//line k8s.qtpl:520
		dep := d.(map[string]any)

//line k8s.qtpl:520
		qw422016.N().S(`
k8s:Deployment.apps:{"namespace":`)
//line k8s.qtpl:521
		qw422016.N().Q(ns)
//line k8s.qtpl:521
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:521
		qw422016.N().Q(dep["name"].(string))
//line k8s.qtpl:521
		qw422016.N().S(`}
`)
//line k8s.qtpl:522
	}
//line k8s.qtpl:522
	qw422016.N().S(`
`)
//line k8s.qtpl:523
}

//line k8s.qtpl:523
func WriteCSVToDeployment(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:523
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:523
	StreamCSVToDeployment(qw422016, o)
//line k8s.qtpl:523
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:523
}

//line k8s.qtpl:523
func CSVToDeployment(o interface{}) string {
//line k8s.qtpl:523
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:523
	WriteCSVToDeployment(qb422016, o)
//line k8s.qtpl:523
	qs422016 := string(qb422016.B)
//line k8s.qtpl:523
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:523
	return qs422016
//line k8s.qtpl:523
}

// # SubscriptionToInstallPlan finds the InstallPlan for an OLM Subscription.
// name: SubscriptionToInstallPlan
// start:
//   domain: k8s
//   classes: [Subscription.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [InstallPlan.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:534
func StreamSubscriptionToInstallPlan(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:534
	qw422016.N().S(`
`)
//line k8s.qtpl:536
	obj := o.(map[string]any)
	ref := obj["status"].(map[string]any)["installPlanRef"].(map[string]any)

//line k8s.qtpl:538
	qw422016.N().S(`
k8s:InstallPlan.v1alpha1.operators.coreos.com:{"namespace":`)
//line k8s.qtpl:539
	qw422016.N().Q(ref["namespace"].(string))
//line k8s.qtpl:539
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:539
	qw422016.N().Q(ref["name"].(string))
//line k8s.qtpl:539
	qw422016.N().S(`}
`)
//line k8s.qtpl:540
}

//line k8s.qtpl:540
func WriteSubscriptionToInstallPlan(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:540
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:540
	StreamSubscriptionToInstallPlan(qw422016, o)
//line k8s.qtpl:540
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:540
}

//line k8s.qtpl:540
func SubscriptionToInstallPlan(o interface{}) string {
//line k8s.qtpl:540
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:540
	WriteSubscriptionToInstallPlan(qb422016, o)
//line k8s.qtpl:540
	qs422016 := string(qb422016.B)
//line k8s.qtpl:540
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:540
	return qs422016
//line k8s.qtpl:540
}

// # InstallPlanToCSV finds ClusterServiceVersions from an InstallPlan.
// name: InstallPlanToCSV
// start:
//   domain: k8s
//   classes: [InstallPlan.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:551
func StreamInstallPlanToCSV(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:551
	qw422016.N().S(`
`)
//line k8s.qtpl:553
	_, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	obj := o.(map[string]any)
	names := mapSlice(obj["spec"].(map[string]any), "clusterServiceVersionNames")

//line k8s.qtpl:557
	qw422016.N().S(`
`)
//line k8s.qtpl:558
	for _, n := range names {
//line k8s.qtpl:558
		qw422016.N().S(`
k8s:ClusterServiceVersion.v1alpha1.operators.coreos.com:{"namespace":`)
//line k8s.qtpl:559
		qw422016.N().Q(ns)
//line k8s.qtpl:559
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:559
		qw422016.N().Q(n.(string))
//line k8s.qtpl:559
		qw422016.N().S(`}
`)
//line k8s.qtpl:560
	}
//line k8s.qtpl:560
	qw422016.N().S(`
`)
//line k8s.qtpl:561
}

//line k8s.qtpl:561
func WriteInstallPlanToCSV(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:561
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:561
	StreamInstallPlanToCSV(qw422016, o)
//line k8s.qtpl:561
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:561
}

//line k8s.qtpl:561
func InstallPlanToCSV(o interface{}) string {
//line k8s.qtpl:561
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:561
	WriteInstallPlanToCSV(qb422016, o)
//line k8s.qtpl:561
	qs422016 := string(qb422016.B)
//line k8s.qtpl:561
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:561
	return qs422016
//line k8s.qtpl:561
}

// # SubscriptionToCatalogSource finds the CatalogSource for an OLM Subscription.
// name: SubscriptionToCatalogSource
// start:
//   domain: k8s
//   classes: [Subscription.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [CatalogSource.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:572
func StreamSubscriptionToCatalogSource(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:572
	qw422016.N().S(`
`)
//line k8s.qtpl:574
	obj := o.(map[string]any)
	spec := obj["spec"].(map[string]any)
	srcNs := Require(spec["sourceNamespace"].(string))
	src := Require(spec["source"].(string))

//line k8s.qtpl:578
	qw422016.N().S(`
k8s:CatalogSource.v1alpha1.operators.coreos.com:{"namespace":`)
//line k8s.qtpl:579
	qw422016.N().Q(srcNs)
//line k8s.qtpl:579
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:579
	qw422016.N().Q(src)
//line k8s.qtpl:579
	qw422016.N().S(`}
`)
//line k8s.qtpl:580
}

//line k8s.qtpl:580
func WriteSubscriptionToCatalogSource(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:580
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:580
	StreamSubscriptionToCatalogSource(qw422016, o)
//line k8s.qtpl:580
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:580
}

//line k8s.qtpl:580
func SubscriptionToCatalogSource(o interface{}) string {
//line k8s.qtpl:580
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:580
	WriteSubscriptionToCatalogSource(qb422016, o)
//line k8s.qtpl:580
	qs422016 := string(qb422016.B)
//line k8s.qtpl:580
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:580
	return qs422016
//line k8s.qtpl:580
}

// # OperatorToCRD finds CRDs referenced by an OLM Operator.
// name: OperatorToCRD
// start:
//   domain: k8s
//   classes: [Operator.v1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [CustomResourceDefinition.apiextensions.k8s.io]
//

//line k8s.qtpl:591
func StreamOperatorToCRD(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:591
	qw422016.N().S(`
`)
//line k8s.qtpl:593
	obj := o.(map[string]any)
	refs := mapSlice(obj["status"].(map[string]any)["components"].(map[string]any), "refs")

//line k8s.qtpl:595
	qw422016.N().S(`
`)
//line k8s.qtpl:596
	for _, r := range refs {
//line k8s.qtpl:596
		qw422016.N().S(`
`)
//line k8s.qtpl:597
		ref := r.(map[string]any)

//line k8s.qtpl:597
		qw422016.N().S(`
`)
//line k8s.qtpl:598
		if ref["kind"].(string) == "CustomResourceDefinition" {
//line k8s.qtpl:598
			qw422016.N().S(`
k8s:CustomResourceDefinition.apiextensions.k8s.io:{"name":`)
//line k8s.qtpl:599
			qw422016.N().Q(ref["name"].(string))
//line k8s.qtpl:599
			qw422016.N().S(`}
`)
//line k8s.qtpl:600
		}
//line k8s.qtpl:600
		qw422016.N().S(`
`)
//line k8s.qtpl:601
	}
//line k8s.qtpl:601
	qw422016.N().S(`
`)
//line k8s.qtpl:602
}

//line k8s.qtpl:602
func WriteOperatorToCRD(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:602
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:602
	StreamOperatorToCRD(qw422016, o)
//line k8s.qtpl:602
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:602
}

//line k8s.qtpl:602
func OperatorToCRD(o interface{}) string {
//line k8s.qtpl:602
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:602
	WriteOperatorToCRD(qb422016, o)
//line k8s.qtpl:602
	qs422016 := string(qb422016.B)
//line k8s.qtpl:602
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:602
	return qs422016
//line k8s.qtpl:602
}

// # OperatorToCSV finds ClusterServiceVersions referenced by an OLM Operator.
// name: OperatorToCSV
// start:
//   domain: k8s
//   classes: [Operator.v1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:613
func StreamOperatorToCSV(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:613
	qw422016.N().S(`
`)
//line k8s.qtpl:615
	obj := o.(map[string]any)
	refs := mapSlice(obj["status"].(map[string]any)["components"].(map[string]any), "refs")

//line k8s.qtpl:617
	qw422016.N().S(`
`)
//line k8s.qtpl:618
	for _, r := range refs {
//line k8s.qtpl:618
		qw422016.N().S(`
`)
//line k8s.qtpl:619
		ref := r.(map[string]any)

//line k8s.qtpl:619
		qw422016.N().S(`
`)
//line k8s.qtpl:620
		if ref["kind"].(string) == "ClusterServiceVersion" {
//line k8s.qtpl:620
			qw422016.N().S(`
k8s:ClusterServiceVersion.v1alpha1.operators.coreos.com:{"namespace":`)
//line k8s.qtpl:621
			qw422016.N().Q(ref["namespace"].(string))
//line k8s.qtpl:621
			qw422016.N().S(`,"name":`)
//line k8s.qtpl:621
			qw422016.N().Q(ref["name"].(string))
//line k8s.qtpl:621
			qw422016.N().S(`}
`)
//line k8s.qtpl:622
		}
//line k8s.qtpl:622
		qw422016.N().S(`
`)
//line k8s.qtpl:623
	}
//line k8s.qtpl:623
	qw422016.N().S(`
`)
//line k8s.qtpl:624
}

//line k8s.qtpl:624
func WriteOperatorToCSV(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:624
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:624
	StreamOperatorToCSV(qw422016, o)
//line k8s.qtpl:624
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:624
}

//line k8s.qtpl:624
func OperatorToCSV(o interface{}) string {
//line k8s.qtpl:624
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:624
	WriteOperatorToCSV(qb422016, o)
//line k8s.qtpl:624
	qs422016 := string(qb422016.B)
//line k8s.qtpl:624
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:624
	return qs422016
//line k8s.qtpl:624
}

// # OperatorToSubscription finds Subscriptions referenced by an OLM Operator.
// name: OperatorToSubscription
// start:
//   domain: k8s
//   classes: [Operator.v1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes: [Subscription.v1alpha1.operators.coreos.com]
//

//line k8s.qtpl:635
func StreamOperatorToSubscription(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:635
	qw422016.N().S(`
`)
//line k8s.qtpl:637
	obj := o.(map[string]any)
	refs := mapSlice(obj["status"].(map[string]any)["components"].(map[string]any), "refs")

//line k8s.qtpl:639
	qw422016.N().S(`
`)
//line k8s.qtpl:640
	for _, r := range refs {
//line k8s.qtpl:640
		qw422016.N().S(`
`)
//line k8s.qtpl:641
		ref := r.(map[string]any)

//line k8s.qtpl:641
		qw422016.N().S(`
`)
//line k8s.qtpl:642
		if ref["kind"].(string) == "Subscription" {
//line k8s.qtpl:642
			qw422016.N().S(`
k8s:Subscription.v1alpha1.operators.coreos.com:{"namespace":`)
//line k8s.qtpl:643
			qw422016.N().Q(ref["namespace"].(string))
//line k8s.qtpl:643
			qw422016.N().S(`,"name":`)
//line k8s.qtpl:643
			qw422016.N().Q(ref["name"].(string))
//line k8s.qtpl:643
			qw422016.N().S(`}
`)
//line k8s.qtpl:644
		}
//line k8s.qtpl:644
		qw422016.N().S(`
`)
//line k8s.qtpl:645
	}
//line k8s.qtpl:645
	qw422016.N().S(`
`)
//line k8s.qtpl:646
}

//line k8s.qtpl:646
func WriteOperatorToSubscription(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:646
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:646
	StreamOperatorToSubscription(qw422016, o)
//line k8s.qtpl:646
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:646
}

//line k8s.qtpl:646
func OperatorToSubscription(o interface{}) string {
//line k8s.qtpl:646
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:646
	WriteOperatorToSubscription(qb422016, o)
//line k8s.qtpl:646
	qs422016 := string(qb422016.B)
//line k8s.qtpl:646
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:646
	return qs422016
//line k8s.qtpl:646
}

// # IngressToService finds Services referenced by an Ingress.
// name: IngressToService
// start:
//   domain: k8s
//   classes: [Ingress.networking.k8s.io]
// goal:
//   domain: k8s
//   classes: [Service]
//

//line k8s.qtpl:657
func StreamIngressToService(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:657
	qw422016.N().S(`
`)
//line k8s.qtpl:659
	_, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	svcNames := ingressServiceNames(o.(map[string]any))

//line k8s.qtpl:662
	qw422016.N().S(`
`)
//line k8s.qtpl:663
	for _, name := range svcNames {
//line k8s.qtpl:663
		qw422016.N().S(`
k8s:Service:{"namespace":`)
//line k8s.qtpl:664
		qw422016.N().Q(ns)
//line k8s.qtpl:664
		qw422016.N().S(`,"name":`)
//line k8s.qtpl:664
		qw422016.N().Q(name)
//line k8s.qtpl:664
		qw422016.N().S(`}
`)
//line k8s.qtpl:665
	}
//line k8s.qtpl:665
	qw422016.N().S(`
`)
//line k8s.qtpl:666
}

//line k8s.qtpl:666
func WriteIngressToService(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:666
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:666
	StreamIngressToService(qw422016, o)
//line k8s.qtpl:666
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:666
}

//line k8s.qtpl:666
func IngressToService(o interface{}) string {
//line k8s.qtpl:666
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:666
	WriteIngressToService(qb422016, o)
//line k8s.qtpl:666
	qs422016 := string(qb422016.B)
//line k8s.qtpl:666
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:666
	return qs422016
//line k8s.qtpl:666
}

// # CSVToPartOf finds resources labeled app.kubernetes.io/part-of matching the CSV name (minus version).
// name: CSVToPartOf
// start:
//   domain: k8s
//   classes: [ClusterServiceVersion.v1alpha1.operators.coreos.com]
// goal:
//   domain: k8s
//   classes:
//     - Deployment.apps
//     - DaemonSet.apps
//     - StatefulSet.apps
//     - Service
//     - ConfigMap
//     - Secret
//     - ServiceAccount
//

//line k8s.qtpl:684
func StreamCSVToPartOf(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:684
	qw422016.N().S(`
`)
//line k8s.qtpl:686
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)
	partOf := Require(csvPartOfName(name))

//line k8s.qtpl:689
	qw422016.N().S(`
k8s:Deployment.apps:{"namespace":`)
//line k8s.qtpl:690
	qw422016.N().Q(ns)
//line k8s.qtpl:690
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:690
	qw422016.N().Q(partOf)
//line k8s.qtpl:690
	qw422016.N().S(`}}
k8s:DaemonSet.apps:{"namespace":`)
//line k8s.qtpl:691
	qw422016.N().Q(ns)
//line k8s.qtpl:691
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:691
	qw422016.N().Q(partOf)
//line k8s.qtpl:691
	qw422016.N().S(`}}
k8s:StatefulSet.apps:{"namespace":`)
//line k8s.qtpl:692
	qw422016.N().Q(ns)
//line k8s.qtpl:692
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:692
	qw422016.N().Q(partOf)
//line k8s.qtpl:692
	qw422016.N().S(`}}
k8s:Service:{"namespace":`)
//line k8s.qtpl:693
	qw422016.N().Q(ns)
//line k8s.qtpl:693
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:693
	qw422016.N().Q(partOf)
//line k8s.qtpl:693
	qw422016.N().S(`}}
k8s:ConfigMap:{"namespace":`)
//line k8s.qtpl:694
	qw422016.N().Q(ns)
//line k8s.qtpl:694
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:694
	qw422016.N().Q(partOf)
//line k8s.qtpl:694
	qw422016.N().S(`}}
k8s:Secret:{"namespace":`)
//line k8s.qtpl:695
	qw422016.N().Q(ns)
//line k8s.qtpl:695
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:695
	qw422016.N().Q(partOf)
//line k8s.qtpl:695
	qw422016.N().S(`}}
k8s:ServiceAccount:{"namespace":`)
//line k8s.qtpl:696
	qw422016.N().Q(ns)
//line k8s.qtpl:696
	qw422016.N().S(`,"labels":{"app.kubernetes.io/part-of":`)
//line k8s.qtpl:696
	qw422016.N().Q(partOf)
//line k8s.qtpl:696
	qw422016.N().S(`}}
`)
//line k8s.qtpl:697
}

//line k8s.qtpl:697
func WriteCSVToPartOf(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:697
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:697
	StreamCSVToPartOf(qw422016, o)
//line k8s.qtpl:697
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:697
}

//line k8s.qtpl:697
func CSVToPartOf(o interface{}) string {
//line k8s.qtpl:697
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:697
	WriteCSVToPartOf(qb422016, o)
//line k8s.qtpl:697
	qs422016 := string(qb422016.B)
//line k8s.qtpl:697
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:697
	return qs422016
//line k8s.qtpl:697
}

// # HPAToTarget finds the scale target of a HorizontalPodAutoscaler.
// name: HPAToTarget
// start:
//   domain: k8s
//   classes: [HorizontalPodAutoscaler.autoscaling]
// goal:
//   domain: k8s
//

//line k8s.qtpl:707
func StreamHPAToTarget(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:707
	qw422016.N().S(`
`)
//line k8s.qtpl:709
	_, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	obj := o.(map[string]any)
	ref := obj["spec"].(map[string]any)["scaleTargetRef"].(map[string]any)
	apiVersion, _ := ref["apiVersion"].(string)
	kind := ref["kind"].(string)
	name := ref["name"].(string)
	class := k8s.Class(schema.FromAPIVersionAndKind(apiVersion, kind))

//line k8s.qtpl:717
	qw422016.N().S(`
k8s:`)
//line k8s.qtpl:718
	qw422016.N().S(class.Name())
//line k8s.qtpl:718
	qw422016.N().S(`:{"namespace":`)
//line k8s.qtpl:718
	qw422016.N().Q(ns)
//line k8s.qtpl:718
	qw422016.N().S(`,"name":`)
//line k8s.qtpl:718
	qw422016.N().Q(name)
//line k8s.qtpl:718
	qw422016.N().S(`}
`)
//line k8s.qtpl:719
}

//line k8s.qtpl:719
func WriteHPAToTarget(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:719
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:719
	StreamHPAToTarget(qw422016, o)
//line k8s.qtpl:719
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:719
}

//line k8s.qtpl:719
func HPAToTarget(o interface{}) string {
//line k8s.qtpl:719
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:719
	WriteHPAToTarget(qb422016, o)
//line k8s.qtpl:719
	qs422016 := string(qb422016.B)
//line k8s.qtpl:719
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:719
	return qs422016
//line k8s.qtpl:719
}

// # InstanceToOperands finds namespaced operand resources whose app.kubernetes.io/instance label matches the start object's name.
// name: InstanceToOperands
// start:
//   domain: k8s
// goal:
//   domain: k8s
//   classes:
//     - Deployment.apps
//     - DaemonSet.apps
//     - StatefulSet.apps
//     - ReplicaSet.apps
//     - Service
//     - ConfigMap
//     - Secret
//     - ServiceAccount
//     - PersistentVolumeClaim
//     - Job.batch
//     - CronJob.batch
//     - Role.rbac.authorization.k8s.io
//     - RoleBinding.rbac.authorization.k8s.io
//     - Ingress.networking.k8s.io
//     - NetworkPolicy.networking.k8s.io
//     - Route.v1.route.openshift.io
//

//line k8s.qtpl:745
func StreamInstanceToOperands(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:745
	qw422016.N().S(`
`)
//line k8s.qtpl:747
	obj, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)
	if !isCustomResource(obj) {
		Fail("not a custom resource")
	}

//line k8s.qtpl:750
	qw422016.N().S(`
k8s:Deployment.apps:{"namespace":`)
//line k8s.qtpl:751
	qw422016.N().Q(ns)
//line k8s.qtpl:751
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:751
	qw422016.N().Q(name)
//line k8s.qtpl:751
	qw422016.N().S(`}}
k8s:DaemonSet.apps:{"namespace":`)
//line k8s.qtpl:752
	qw422016.N().Q(ns)
//line k8s.qtpl:752
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:752
	qw422016.N().Q(name)
//line k8s.qtpl:752
	qw422016.N().S(`}}
k8s:StatefulSet.apps:{"namespace":`)
//line k8s.qtpl:753
	qw422016.N().Q(ns)
//line k8s.qtpl:753
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:753
	qw422016.N().Q(name)
//line k8s.qtpl:753
	qw422016.N().S(`}}
k8s:ReplicaSet.apps:{"namespace":`)
//line k8s.qtpl:754
	qw422016.N().Q(ns)
//line k8s.qtpl:754
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:754
	qw422016.N().Q(name)
//line k8s.qtpl:754
	qw422016.N().S(`}}
k8s:Service:{"namespace":`)
//line k8s.qtpl:755
	qw422016.N().Q(ns)
//line k8s.qtpl:755
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:755
	qw422016.N().Q(name)
//line k8s.qtpl:755
	qw422016.N().S(`}}
k8s:ConfigMap:{"namespace":`)
//line k8s.qtpl:756
	qw422016.N().Q(ns)
//line k8s.qtpl:756
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:756
	qw422016.N().Q(name)
//line k8s.qtpl:756
	qw422016.N().S(`}}
k8s:Secret:{"namespace":`)
//line k8s.qtpl:757
	qw422016.N().Q(ns)
//line k8s.qtpl:757
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:757
	qw422016.N().Q(name)
//line k8s.qtpl:757
	qw422016.N().S(`}}
k8s:ServiceAccount:{"namespace":`)
//line k8s.qtpl:758
	qw422016.N().Q(ns)
//line k8s.qtpl:758
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:758
	qw422016.N().Q(name)
//line k8s.qtpl:758
	qw422016.N().S(`}}
k8s:PersistentVolumeClaim:{"namespace":`)
//line k8s.qtpl:759
	qw422016.N().Q(ns)
//line k8s.qtpl:759
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:759
	qw422016.N().Q(name)
//line k8s.qtpl:759
	qw422016.N().S(`}}
k8s:Job.batch:{"namespace":`)
//line k8s.qtpl:760
	qw422016.N().Q(ns)
//line k8s.qtpl:760
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:760
	qw422016.N().Q(name)
//line k8s.qtpl:760
	qw422016.N().S(`}}
k8s:CronJob.batch:{"namespace":`)
//line k8s.qtpl:761
	qw422016.N().Q(ns)
//line k8s.qtpl:761
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:761
	qw422016.N().Q(name)
//line k8s.qtpl:761
	qw422016.N().S(`}}
k8s:Role.rbac.authorization.k8s.io:{"namespace":`)
//line k8s.qtpl:762
	qw422016.N().Q(ns)
//line k8s.qtpl:762
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:762
	qw422016.N().Q(name)
//line k8s.qtpl:762
	qw422016.N().S(`}}
k8s:RoleBinding.rbac.authorization.k8s.io:{"namespace":`)
//line k8s.qtpl:763
	qw422016.N().Q(ns)
//line k8s.qtpl:763
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:763
	qw422016.N().Q(name)
//line k8s.qtpl:763
	qw422016.N().S(`}}
k8s:Ingress.networking.k8s.io:{"namespace":`)
//line k8s.qtpl:764
	qw422016.N().Q(ns)
//line k8s.qtpl:764
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:764
	qw422016.N().Q(name)
//line k8s.qtpl:764
	qw422016.N().S(`}}
k8s:NetworkPolicy.networking.k8s.io:{"namespace":`)
//line k8s.qtpl:765
	qw422016.N().Q(ns)
//line k8s.qtpl:765
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:765
	qw422016.N().Q(name)
//line k8s.qtpl:765
	qw422016.N().S(`}}
k8s:Route.v1.route.openshift.io:{"namespace":`)
//line k8s.qtpl:766
	qw422016.N().Q(ns)
//line k8s.qtpl:766
	qw422016.N().S(`,"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:766
	qw422016.N().Q(name)
//line k8s.qtpl:766
	qw422016.N().S(`}}
`)
//line k8s.qtpl:767
}

//line k8s.qtpl:767
func WriteInstanceToOperands(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:767
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:767
	StreamInstanceToOperands(qw422016, o)
//line k8s.qtpl:767
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:767
}

//line k8s.qtpl:767
func InstanceToOperands(o interface{}) string {
//line k8s.qtpl:767
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:767
	WriteInstanceToOperands(qb422016, o)
//line k8s.qtpl:767
	qs422016 := string(qb422016.B)
//line k8s.qtpl:767
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:767
	return qs422016
//line k8s.qtpl:767
}

// # ClusterInstanceToOperands finds operands of cluster-scoped instances whose app.kubernetes.io/instance label matches the start object's name.
// name: ClusterInstanceToOperands
// start:
//   domain: k8s
// goal:
//   domain: k8s
//   classes:
//     - ClusterRole.rbac.authorization.k8s.io
//     - ClusterRoleBinding.rbac.authorization.k8s.io
//     - Deployment.apps
//     - DaemonSet.apps
//     - StatefulSet.apps
//     - ReplicaSet.apps
//     - Service
//     - ConfigMap
//     - Secret
//     - ServiceAccount
//     - PersistentVolumeClaim
//     - Job.batch
//     - CronJob.batch
//     - Role.rbac.authorization.k8s.io
//     - RoleBinding.rbac.authorization.k8s.io
//     - Ingress.networking.k8s.io
//     - NetworkPolicy.networking.k8s.io
//     - Route.v1.route.openshift.io
//

//line k8s.qtpl:795
func StreamClusterInstanceToOperands(qw422016 *qt422016.Writer, o interface{}) {
//line k8s.qtpl:795
	qw422016.N().S(`
`)
//line k8s.qtpl:797
	obj, _, ns, name, _ := k8sMetadata(o)
	if ns != "" {
		Fail("namespaced object")
	}
	RequireAll(name)
	if !isCustomResource(obj) {
		Fail("not a custom resource")
	}

//line k8s.qtpl:801
	qw422016.N().S(`
k8s:ClusterRole.rbac.authorization.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:802
	qw422016.N().Q(name)
//line k8s.qtpl:802
	qw422016.N().S(`}}
k8s:ClusterRoleBinding.rbac.authorization.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:803
	qw422016.N().Q(name)
//line k8s.qtpl:803
	qw422016.N().S(`}}
k8s:Deployment.apps:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:804
	qw422016.N().Q(name)
//line k8s.qtpl:804
	qw422016.N().S(`}}
k8s:DaemonSet.apps:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:805
	qw422016.N().Q(name)
//line k8s.qtpl:805
	qw422016.N().S(`}}
k8s:StatefulSet.apps:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:806
	qw422016.N().Q(name)
//line k8s.qtpl:806
	qw422016.N().S(`}}
k8s:ReplicaSet.apps:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:807
	qw422016.N().Q(name)
//line k8s.qtpl:807
	qw422016.N().S(`}}
k8s:Service:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:808
	qw422016.N().Q(name)
//line k8s.qtpl:808
	qw422016.N().S(`}}
k8s:ConfigMap:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:809
	qw422016.N().Q(name)
//line k8s.qtpl:809
	qw422016.N().S(`}}
k8s:Secret:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:810
	qw422016.N().Q(name)
//line k8s.qtpl:810
	qw422016.N().S(`}}
k8s:ServiceAccount:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:811
	qw422016.N().Q(name)
//line k8s.qtpl:811
	qw422016.N().S(`}}
k8s:PersistentVolumeClaim:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:812
	qw422016.N().Q(name)
//line k8s.qtpl:812
	qw422016.N().S(`}}
k8s:Job.batch:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:813
	qw422016.N().Q(name)
//line k8s.qtpl:813
	qw422016.N().S(`}}
k8s:CronJob.batch:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:814
	qw422016.N().Q(name)
//line k8s.qtpl:814
	qw422016.N().S(`}}
k8s:Role.rbac.authorization.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:815
	qw422016.N().Q(name)
//line k8s.qtpl:815
	qw422016.N().S(`}}
k8s:RoleBinding.rbac.authorization.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:816
	qw422016.N().Q(name)
//line k8s.qtpl:816
	qw422016.N().S(`}}
k8s:Ingress.networking.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:817
	qw422016.N().Q(name)
//line k8s.qtpl:817
	qw422016.N().S(`}}
k8s:NetworkPolicy.networking.k8s.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:818
	qw422016.N().Q(name)
//line k8s.qtpl:818
	qw422016.N().S(`}}
k8s:Route.v1.route.openshift.io:{"labels":{"app.kubernetes.io/instance":`)
//line k8s.qtpl:819
	qw422016.N().Q(name)
//line k8s.qtpl:819
	qw422016.N().S(`}}
`)
//line k8s.qtpl:820
}

//line k8s.qtpl:820
func WriteClusterInstanceToOperands(qq422016 qtio422016.Writer, o interface{}) {
//line k8s.qtpl:820
	qw422016 := qt422016.AcquireWriter(qq422016)
//line k8s.qtpl:820
	StreamClusterInstanceToOperands(qw422016, o)
//line k8s.qtpl:820
	qt422016.ReleaseWriter(qw422016)
//line k8s.qtpl:820
}

//line k8s.qtpl:820
func ClusterInstanceToOperands(o interface{}) string {
//line k8s.qtpl:820
	qb422016 := qt422016.AcquireByteBuffer()
//line k8s.qtpl:820
	WriteClusterInstanceToOperands(qb422016, o)
//line k8s.qtpl:820
	qs422016 := string(qb422016.B)
//line k8s.qtpl:820
	qt422016.ReleaseByteBuffer(qb422016)
//line k8s.qtpl:820
	return qs422016
//line k8s.qtpl:820
}
