// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "kubevirt.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line kubevirt.qtpl:1
package quickrules

//line kubevirt.qtpl:3
import "strings"

// # VmToVmi finds the VirtualMachineInstance for a VirtualMachine.
// name: VmToVmi
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
//

//line kubevirt.qtpl:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line kubevirt.qtpl:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line kubevirt.qtpl:14
func StreamVmToVmi(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:14
	qw422016.N().S(`
`)
//line kubevirt.qtpl:15
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:15
	qw422016.N().S(`
k8s:VirtualMachineInstance.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:16
	qw422016.N().Q(ns)
//line kubevirt.qtpl:16
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:16
	qw422016.N().Q(name)
//line kubevirt.qtpl:16
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:17
}

//line kubevirt.qtpl:17
func WriteVmToVmi(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:17
	StreamVmToVmi(qw422016, o)
//line kubevirt.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:17
}

//line kubevirt.qtpl:17
func VmToVmi(o interface{}) string {
//line kubevirt.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:17
	WriteVmToVmi(qb422016, o)
//line kubevirt.qtpl:17
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:17
	return qs422016
//line kubevirt.qtpl:17
}

// # VmiToPod finds the virt-launcher Pod for a VirtualMachineInstance.
// name: VmiToPod
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line kubevirt.qtpl:28
func StreamVmiToPod(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:28
	qw422016.N().S(`
`)
//line kubevirt.qtpl:29
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:29
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line kubevirt.qtpl:30
	qw422016.N().Q(ns)
//line kubevirt.qtpl:30
	qw422016.N().S(`,"labels":{"kubevirt.io":"virt-launcher","vm.kubevirt.io/name":`)
//line kubevirt.qtpl:30
	qw422016.N().Q(name)
//line kubevirt.qtpl:30
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:31
}

//line kubevirt.qtpl:31
func WriteVmiToPod(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:31
	StreamVmiToPod(qw422016, o)
//line kubevirt.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:31
}

//line kubevirt.qtpl:31
func VmiToPod(o interface{}) string {
//line kubevirt.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:31
	WriteVmiToPod(qb422016, o)
//line kubevirt.qtpl:31
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:31
	return qs422016
//line kubevirt.qtpl:31
}

// # VmiToNode finds the Node a VirtualMachineInstance is scheduled on.
// name: VmiToNode
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [Node]
//

//line kubevirt.qtpl:42
func StreamVmiToNode(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:42
	qw422016.N().S(`
`)
//line kubevirt.qtpl:44
	obj := o.(map[string]any)
	nodeName := Require(obj["status"].(map[string]any)["nodeName"].(string))

//line kubevirt.qtpl:46
	qw422016.N().S(`
k8s:Node:{"name":`)
//line kubevirt.qtpl:47
	qw422016.N().Q(nodeName)
//line kubevirt.qtpl:47
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:48
}

//line kubevirt.qtpl:48
func WriteVmiToNode(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:48
	StreamVmiToNode(qw422016, o)
//line kubevirt.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:48
}

//line kubevirt.qtpl:48
func VmiToNode(o interface{}) string {
//line kubevirt.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:48
	WriteVmiToNode(qb422016, o)
//line kubevirt.qtpl:48
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:48
	return qs422016
//line kubevirt.qtpl:48
}

// # VmToPVC finds PersistentVolumeClaims referenced by a VirtualMachine.
// name: VmToPVC
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line kubevirt.qtpl:59
func StreamVmToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:59
	qw422016.N().S(`
`)
//line kubevirt.qtpl:61
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	spec := obj["spec"].(map[string]any)
	dvTemplates := mapSlice(spec, "dataVolumeTemplates")
	tmplSpec := spec["template"].(map[string]any)["spec"].(map[string]any)
	volumes := mapSlice(tmplSpec, "volumes")

//line kubevirt.qtpl:67
	qw422016.N().S(`
`)
//line kubevirt.qtpl:68
	for _, t := range dvTemplates {
//line kubevirt.qtpl:68
		qw422016.N().S(`
`)
//line kubevirt.qtpl:69
		dvName := t.(map[string]any)["metadata"].(map[string]any)["name"].(string)

//line kubevirt.qtpl:69
		qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:70
		qw422016.N().Q(ns)
//line kubevirt.qtpl:70
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:70
		qw422016.N().Q(dvName)
//line kubevirt.qtpl:70
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:71
	}
//line kubevirt.qtpl:71
	qw422016.N().S(`
`)
//line kubevirt.qtpl:72
	for _, v := range volumes {
//line kubevirt.qtpl:72
		qw422016.N().S(`
`)
//line kubevirt.qtpl:73
		vol := v.(map[string]any)

//line kubevirt.qtpl:73
		qw422016.N().S(`
`)
//line kubevirt.qtpl:74
		if pvc, ok := vol["persistentVolumeClaim"].(map[string]any); ok {
//line kubevirt.qtpl:74
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:75
			qw422016.N().Q(ns)
//line kubevirt.qtpl:75
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:75
			qw422016.N().Q(pvc["claimName"].(string))
//line kubevirt.qtpl:75
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:76
		}
//line kubevirt.qtpl:76
		qw422016.N().S(`
`)
//line kubevirt.qtpl:77
		if dv, ok := vol["dataVolume"].(map[string]any); ok {
//line kubevirt.qtpl:77
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:78
			qw422016.N().Q(ns)
//line kubevirt.qtpl:78
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:78
			qw422016.N().Q(dv["name"].(string))
//line kubevirt.qtpl:78
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:79
		}
//line kubevirt.qtpl:79
		qw422016.N().S(`
`)
//line kubevirt.qtpl:80
		if eph, ok := vol["ephemeral"].(map[string]any); ok {
//line kubevirt.qtpl:80
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:81
			qw422016.N().Q(ns)
//line kubevirt.qtpl:81
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:81
			qw422016.N().Q(eph["persistentVolumeClaim"].(map[string]any)["claimName"].(string))
//line kubevirt.qtpl:81
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:82
		}
//line kubevirt.qtpl:82
		qw422016.N().S(`
`)
//line kubevirt.qtpl:83
		if md, ok := vol["memoryDump"].(map[string]any); ok {
//line kubevirt.qtpl:83
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:84
			qw422016.N().Q(ns)
//line kubevirt.qtpl:84
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:84
			qw422016.N().Q(md["claimName"].(string))
//line kubevirt.qtpl:84
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:85
		}
//line kubevirt.qtpl:85
		qw422016.N().S(`
`)
//line kubevirt.qtpl:86
	}
//line kubevirt.qtpl:86
	qw422016.N().S(`
`)
//line kubevirt.qtpl:87
}

//line kubevirt.qtpl:87
func WriteVmToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:87
	StreamVmToPVC(qw422016, o)
//line kubevirt.qtpl:87
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:87
}

//line kubevirt.qtpl:87
func VmToPVC(o interface{}) string {
//line kubevirt.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:87
	WriteVmToPVC(qb422016, o)
//line kubevirt.qtpl:87
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:87
	return qs422016
//line kubevirt.qtpl:87
}

// # VmToAlert finds alerts related to a VirtualMachine.
// name: VmToAlert
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: alert
//

//line kubevirt.qtpl:97
func StreamVmToAlert(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:97
	qw422016.N().S(`
`)
//line kubevirt.qtpl:98
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:98
	qw422016.N().S(`
alert:alert:{"namespace":`)
//line kubevirt.qtpl:99
	qw422016.N().Q(ns)
//line kubevirt.qtpl:99
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:99
	qw422016.N().Q(name)
//line kubevirt.qtpl:99
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:100
}

//line kubevirt.qtpl:100
func WriteVmToAlert(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:100
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:100
	StreamVmToAlert(qw422016, o)
//line kubevirt.qtpl:100
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:100
}

//line kubevirt.qtpl:100
func VmToAlert(o interface{}) string {
//line kubevirt.qtpl:100
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:100
	WriteVmToAlert(qb422016, o)
//line kubevirt.qtpl:100
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:100
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:100
	return qs422016
//line kubevirt.qtpl:100
}

// # VmiToAlert finds alerts related to a VirtualMachineInstance.
// name: VmiToAlert
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: alert
//

//line kubevirt.qtpl:110
func StreamVmiToAlert(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:110
	qw422016.N().S(`
`)
//line kubevirt.qtpl:111
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:111
	qw422016.N().S(`
alert:alert:{"namespace":`)
//line kubevirt.qtpl:112
	qw422016.N().Q(ns)
//line kubevirt.qtpl:112
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:112
	qw422016.N().Q(name)
//line kubevirt.qtpl:112
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:113
}

//line kubevirt.qtpl:113
func WriteVmiToAlert(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:113
	StreamVmiToAlert(qw422016, o)
//line kubevirt.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:113
}

//line kubevirt.qtpl:113
func VmiToAlert(o interface{}) string {
//line kubevirt.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:113
	WriteVmiToAlert(qb422016, o)
//line kubevirt.qtpl:113
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:113
	return qs422016
//line kubevirt.qtpl:113
}

// # VmimToAlert finds alerts related to a VirtualMachineInstanceMigration.
// name: VmimToAlert
// start:
//   domain: k8s
//   classes: [VirtualMachineInstanceMigration.kubevirt.io]
// goal:
//   domain: alert
//

//line kubevirt.qtpl:123
func StreamVmimToAlert(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:123
	qw422016.N().S(`
`)
//line kubevirt.qtpl:124
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:124
	qw422016.N().S(`
alert:alert:{"namespace":`)
//line kubevirt.qtpl:125
	qw422016.N().Q(ns)
//line kubevirt.qtpl:125
	qw422016.N().S(`,"vmim":`)
//line kubevirt.qtpl:125
	qw422016.N().Q(name)
//line kubevirt.qtpl:125
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:126
}

//line kubevirt.qtpl:126
func WriteVmimToAlert(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:126
	StreamVmimToAlert(qw422016, o)
//line kubevirt.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:126
}

//line kubevirt.qtpl:126
func VmimToAlert(o interface{}) string {
//line kubevirt.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:126
	WriteVmimToAlert(qb422016, o)
//line kubevirt.qtpl:126
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:126
	return qs422016
//line kubevirt.qtpl:126
}

// # VmToMetric finds metrics related to a VirtualMachine.
// name: VmToMetric
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: metric
//

//line kubevirt.qtpl:136
func StreamVmToMetric(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:136
	qw422016.N().S(`
`)
//line kubevirt.qtpl:137
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:137
	qw422016.N().S(`
metric:metric:{namespace=`)
//line kubevirt.qtpl:138
	qw422016.N().Q(ns)
//line kubevirt.qtpl:138
	qw422016.N().S(`,name=`)
//line kubevirt.qtpl:138
	qw422016.N().Q(name)
//line kubevirt.qtpl:138
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:139
}

//line kubevirt.qtpl:139
func WriteVmToMetric(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:139
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:139
	StreamVmToMetric(qw422016, o)
//line kubevirt.qtpl:139
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:139
}

//line kubevirt.qtpl:139
func VmToMetric(o interface{}) string {
//line kubevirt.qtpl:139
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:139
	WriteVmToMetric(qb422016, o)
//line kubevirt.qtpl:139
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:139
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:139
	return qs422016
//line kubevirt.qtpl:139
}

// # VmiToMetric finds metrics related to a VirtualMachineInstance.
// name: VmiToMetric
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: metric
//

//line kubevirt.qtpl:149
func StreamVmiToMetric(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:149
	qw422016.N().S(`
`)
//line kubevirt.qtpl:150
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:150
	qw422016.N().S(`
metric:metric:{namespace=`)
//line kubevirt.qtpl:151
	qw422016.N().Q(ns)
//line kubevirt.qtpl:151
	qw422016.N().S(`,name=`)
//line kubevirt.qtpl:151
	qw422016.N().Q(name)
//line kubevirt.qtpl:151
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:152
}

//line kubevirt.qtpl:152
func WriteVmiToMetric(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:152
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:152
	StreamVmiToMetric(qw422016, o)
//line kubevirt.qtpl:152
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:152
}

//line kubevirt.qtpl:152
func VmiToMetric(o interface{}) string {
//line kubevirt.qtpl:152
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:152
	WriteVmiToMetric(qb422016, o)
//line kubevirt.qtpl:152
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:152
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:152
	return qs422016
//line kubevirt.qtpl:152
}

// # VmiToLogs finds virt-launcher pod logs for a VirtualMachineInstance.
// name: VmiToLogs
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: log
//

//line kubevirt.qtpl:162
func StreamVmiToLogs(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:162
	qw422016.N().S(`
`)
//line kubevirt.qtpl:163
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:163
	qw422016.N().S(`
log:`)
//line kubevirt.qtpl:164
	qw422016.N().S(logTypeForNamespace(ns))
//line kubevirt.qtpl:164
	qw422016.N().S(`:{"namespace":`)
//line kubevirt.qtpl:164
	qw422016.N().Q(ns)
//line kubevirt.qtpl:164
	qw422016.N().S(`,"labels":{"kubevirt.io":"virt-launcher","vm.kubevirt.io/name":`)
//line kubevirt.qtpl:164
	qw422016.N().Q(name)
//line kubevirt.qtpl:164
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:165
}

//line kubevirt.qtpl:165
func WriteVmiToLogs(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:165
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:165
	StreamVmiToLogs(qw422016, o)
//line kubevirt.qtpl:165
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:165
}

//line kubevirt.qtpl:165
func VmiToLogs(o interface{}) string {
//line kubevirt.qtpl:165
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:165
	WriteVmiToLogs(qb422016, o)
//line kubevirt.qtpl:165
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:165
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:165
	return qs422016
//line kubevirt.qtpl:165
}

// # VmimToVmi finds the VirtualMachineInstance for a migration.
// name: VmimToVmi
// start:
//   domain: k8s
//   classes: [VirtualMachineInstanceMigration.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
//

//line kubevirt.qtpl:176
func StreamVmimToVmi(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:176
	qw422016.N().S(`
`)
//line kubevirt.qtpl:178
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	vmiName := Require(obj["spec"].(map[string]any)["vmiName"].(string))

//line kubevirt.qtpl:181
	qw422016.N().S(`
k8s:VirtualMachineInstance.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:182
	qw422016.N().Q(ns)
//line kubevirt.qtpl:182
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:182
	qw422016.N().Q(vmiName)
//line kubevirt.qtpl:182
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:183
}

//line kubevirt.qtpl:183
func WriteVmimToVmi(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:183
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:183
	StreamVmimToVmi(qw422016, o)
//line kubevirt.qtpl:183
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:183
}

//line kubevirt.qtpl:183
func VmimToVmi(o interface{}) string {
//line kubevirt.qtpl:183
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:183
	WriteVmimToVmi(qb422016, o)
//line kubevirt.qtpl:183
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:183
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:183
	return qs422016
//line kubevirt.qtpl:183
}

// # VmiToVmim finds migrations for a VirtualMachineInstance.
// name: VmiToVmim
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineInstanceMigration.kubevirt.io]
//

//line kubevirt.qtpl:194
func StreamVmiToVmim(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:194
	qw422016.N().S(`
`)
//line kubevirt.qtpl:195
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:195
	qw422016.N().S(`
k8s:VirtualMachineInstanceMigration.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:196
	qw422016.N().Q(ns)
//line kubevirt.qtpl:196
	qw422016.N().S(`,"labels":{"kubevirt.io/vmi-name":`)
//line kubevirt.qtpl:196
	qw422016.N().Q(name)
//line kubevirt.qtpl:196
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:197
}

//line kubevirt.qtpl:197
func WriteVmiToVmim(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:197
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:197
	StreamVmiToVmim(qw422016, o)
//line kubevirt.qtpl:197
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:197
}

//line kubevirt.qtpl:197
func VmiToVmim(o interface{}) string {
//line kubevirt.qtpl:197
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:197
	WriteVmiToVmim(qb422016, o)
//line kubevirt.qtpl:197
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:197
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:197
	return qs422016
//line kubevirt.qtpl:197
}

// # DataVolumeToPVC finds the PVC for a DataVolume (they share namespace/name).
// name: DataVolumeToPVC
// start:
//   domain: k8s
//   classes: [DataVolume.cdi.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line kubevirt.qtpl:208
func StreamDataVolumeToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:208
	qw422016.N().S(`
`)
//line kubevirt.qtpl:209
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:209
	qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:210
	qw422016.N().Q(ns)
//line kubevirt.qtpl:210
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:210
	qw422016.N().Q(name)
//line kubevirt.qtpl:210
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:211
}

//line kubevirt.qtpl:211
func WriteDataVolumeToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:211
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:211
	StreamDataVolumeToPVC(qw422016, o)
//line kubevirt.qtpl:211
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:211
}

//line kubevirt.qtpl:211
func DataVolumeToPVC(o interface{}) string {
//line kubevirt.qtpl:211
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:211
	WriteDataVolumeToPVC(qb422016, o)
//line kubevirt.qtpl:211
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:211
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:211
	return qs422016
//line kubevirt.qtpl:211
}

// # VmToDataVolume finds DataVolumes referenced by a VirtualMachine.
// name: VmToDataVolume
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [DataVolume.cdi.kubevirt.io]
//

//line kubevirt.qtpl:222
func StreamVmToDataVolume(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:222
	qw422016.N().S(`
`)
//line kubevirt.qtpl:224
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	spec := obj["spec"].(map[string]any)
	dvTemplates := mapSlice(spec, "dataVolumeTemplates")
	tmplSpec := spec["template"].(map[string]any)["spec"].(map[string]any)
	volumes := mapSlice(tmplSpec, "volumes")

//line kubevirt.qtpl:230
	qw422016.N().S(`
`)
//line kubevirt.qtpl:231
	for _, t := range dvTemplates {
//line kubevirt.qtpl:231
		qw422016.N().S(`
`)
//line kubevirt.qtpl:232
		dvName := t.(map[string]any)["metadata"].(map[string]any)["name"].(string)

//line kubevirt.qtpl:232
		qw422016.N().S(`
k8s:DataVolume.cdi.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:233
		qw422016.N().Q(ns)
//line kubevirt.qtpl:233
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:233
		qw422016.N().Q(dvName)
//line kubevirt.qtpl:233
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:234
	}
//line kubevirt.qtpl:234
	qw422016.N().S(`
`)
//line kubevirt.qtpl:235
	for _, v := range volumes {
//line kubevirt.qtpl:235
		qw422016.N().S(`
`)
//line kubevirt.qtpl:236
		vol := v.(map[string]any)

//line kubevirt.qtpl:236
		qw422016.N().S(`
`)
//line kubevirt.qtpl:237
		if dv, ok := vol["dataVolume"].(map[string]any); ok {
//line kubevirt.qtpl:237
			qw422016.N().S(`
k8s:DataVolume.cdi.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:238
			qw422016.N().Q(ns)
//line kubevirt.qtpl:238
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:238
			qw422016.N().Q(dv["name"].(string))
//line kubevirt.qtpl:238
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:239
		}
//line kubevirt.qtpl:239
		qw422016.N().S(`
`)
//line kubevirt.qtpl:240
	}
//line kubevirt.qtpl:240
	qw422016.N().S(`
`)
//line kubevirt.qtpl:241
}

//line kubevirt.qtpl:241
func WriteVmToDataVolume(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:241
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:241
	StreamVmToDataVolume(qw422016, o)
//line kubevirt.qtpl:241
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:241
}

//line kubevirt.qtpl:241
func VmToDataVolume(o interface{}) string {
//line kubevirt.qtpl:241
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:241
	WriteVmToDataVolume(qb422016, o)
//line kubevirt.qtpl:241
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:241
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:241
	return qs422016
//line kubevirt.qtpl:241
}

// # VmiToPVC finds PersistentVolumeClaims referenced by a VirtualMachineInstance.
// name: VmiToPVC
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line kubevirt.qtpl:252
func StreamVmiToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:252
	qw422016.N().S(`
`)
//line kubevirt.qtpl:254
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line kubevirt.qtpl:257
	qw422016.N().S(`
`)
//line kubevirt.qtpl:258
	for _, v := range volumes {
//line kubevirt.qtpl:258
		qw422016.N().S(`
`)
//line kubevirt.qtpl:259
		vol := v.(map[string]any)

//line kubevirt.qtpl:259
		qw422016.N().S(`
`)
//line kubevirt.qtpl:260
		if pvc, ok := vol["persistentVolumeClaim"].(map[string]any); ok {
//line kubevirt.qtpl:260
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:261
			qw422016.N().Q(ns)
//line kubevirt.qtpl:261
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:261
			qw422016.N().Q(pvc["claimName"].(string))
//line kubevirt.qtpl:261
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:262
		}
//line kubevirt.qtpl:262
		qw422016.N().S(`
`)
//line kubevirt.qtpl:263
		if dv, ok := vol["dataVolume"].(map[string]any); ok {
//line kubevirt.qtpl:263
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:264
			qw422016.N().Q(ns)
//line kubevirt.qtpl:264
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:264
			qw422016.N().Q(dv["name"].(string))
//line kubevirt.qtpl:264
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:265
		}
//line kubevirt.qtpl:265
		qw422016.N().S(`
`)
//line kubevirt.qtpl:266
		if eph, ok := vol["ephemeral"].(map[string]any); ok {
//line kubevirt.qtpl:266
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:267
			qw422016.N().Q(ns)
//line kubevirt.qtpl:267
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:267
			qw422016.N().Q(eph["persistentVolumeClaim"].(map[string]any)["claimName"].(string))
//line kubevirt.qtpl:267
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:268
		}
//line kubevirt.qtpl:268
		qw422016.N().S(`
`)
//line kubevirt.qtpl:269
		if md, ok := vol["memoryDump"].(map[string]any); ok {
//line kubevirt.qtpl:269
			qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:270
			qw422016.N().Q(ns)
//line kubevirt.qtpl:270
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:270
			qw422016.N().Q(md["claimName"].(string))
//line kubevirt.qtpl:270
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:271
		}
//line kubevirt.qtpl:271
		qw422016.N().S(`
`)
//line kubevirt.qtpl:272
	}
//line kubevirt.qtpl:272
	qw422016.N().S(`
`)
//line kubevirt.qtpl:273
}

//line kubevirt.qtpl:273
func WriteVmiToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:273
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:273
	StreamVmiToPVC(qw422016, o)
//line kubevirt.qtpl:273
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:273
}

//line kubevirt.qtpl:273
func VmiToPVC(o interface{}) string {
//line kubevirt.qtpl:273
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:273
	WriteVmiToPVC(qb422016, o)
//line kubevirt.qtpl:273
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:273
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:273
	return qs422016
//line kubevirt.qtpl:273
}

// # VmiToDataVolume finds DataVolumes referenced by a VirtualMachineInstance.
// name: VmiToDataVolume
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [DataVolume.cdi.kubevirt.io]
//

//line kubevirt.qtpl:284
func StreamVmiToDataVolume(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:284
	qw422016.N().S(`
`)
//line kubevirt.qtpl:286
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line kubevirt.qtpl:289
	qw422016.N().S(`
`)
//line kubevirt.qtpl:290
	for _, v := range volumes {
//line kubevirt.qtpl:290
		qw422016.N().S(`
`)
//line kubevirt.qtpl:291
		vol := v.(map[string]any)

//line kubevirt.qtpl:291
		qw422016.N().S(`
`)
//line kubevirt.qtpl:292
		if dv, ok := vol["dataVolume"].(map[string]any); ok {
//line kubevirt.qtpl:292
			qw422016.N().S(`
k8s:DataVolume.cdi.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:293
			qw422016.N().Q(ns)
//line kubevirt.qtpl:293
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:293
			qw422016.N().Q(dv["name"].(string))
//line kubevirt.qtpl:293
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:294
		}
//line kubevirt.qtpl:294
		qw422016.N().S(`
`)
//line kubevirt.qtpl:295
	}
//line kubevirt.qtpl:295
	qw422016.N().S(`
`)
//line kubevirt.qtpl:296
}

//line kubevirt.qtpl:296
func WriteVmiToDataVolume(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:296
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:296
	StreamVmiToDataVolume(qw422016, o)
//line kubevirt.qtpl:296
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:296
}

//line kubevirt.qtpl:296
func VmiToDataVolume(o interface{}) string {
//line kubevirt.qtpl:296
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:296
	WriteVmiToDataVolume(qb422016, o)
//line kubevirt.qtpl:296
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:296
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:296
	return qs422016
//line kubevirt.qtpl:296
}

// # VmSnapshotToVm finds the source VirtualMachine of a snapshot.
// name: VmSnapshotToVm
// start:
//   domain: k8s
//   classes: [VirtualMachineSnapshot.snapshot.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
//

//line kubevirt.qtpl:307
func StreamVmSnapshotToVm(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:307
	qw422016.N().S(`
`)
//line kubevirt.qtpl:309
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	srcName := Require(obj["spec"].(map[string]any)["source"].(map[string]any)["name"].(string))

//line kubevirt.qtpl:312
	qw422016.N().S(`
k8s:VirtualMachine.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:313
	qw422016.N().Q(ns)
//line kubevirt.qtpl:313
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:313
	qw422016.N().Q(srcName)
//line kubevirt.qtpl:313
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:314
}

//line kubevirt.qtpl:314
func WriteVmSnapshotToVm(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:314
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:314
	StreamVmSnapshotToVm(qw422016, o)
//line kubevirt.qtpl:314
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:314
}

//line kubevirt.qtpl:314
func VmSnapshotToVm(o interface{}) string {
//line kubevirt.qtpl:314
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:314
	WriteVmSnapshotToVm(qb422016, o)
//line kubevirt.qtpl:314
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:314
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:314
	return qs422016
//line kubevirt.qtpl:314
}

// # VmToVmSnapshot finds snapshots of a VirtualMachine.
// name: VmToVmSnapshot
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineSnapshot.snapshot.kubevirt.io]
//

//line kubevirt.qtpl:325
func StreamVmToVmSnapshot(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:325
	qw422016.N().S(`
`)
//line kubevirt.qtpl:326
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:326
	qw422016.N().S(`
k8s:VirtualMachineSnapshot.snapshot.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:327
	qw422016.N().Q(ns)
//line kubevirt.qtpl:327
	qw422016.N().S(`,"labels":{"vm.kubevirt.io/name":`)
//line kubevirt.qtpl:327
	qw422016.N().Q(name)
//line kubevirt.qtpl:327
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:328
}

//line kubevirt.qtpl:328
func WriteVmToVmSnapshot(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:328
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:328
	StreamVmToVmSnapshot(qw422016, o)
//line kubevirt.qtpl:328
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:328
}

//line kubevirt.qtpl:328
func VmToVmSnapshot(o interface{}) string {
//line kubevirt.qtpl:328
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:328
	WriteVmToVmSnapshot(qb422016, o)
//line kubevirt.qtpl:328
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:328
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:328
	return qs422016
//line kubevirt.qtpl:328
}

// # VmRestoreToVm finds the target VirtualMachine of a restore.
// name: VmRestoreToVm
// start:
//   domain: k8s
//   classes: [VirtualMachineRestore.snapshot.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
//

//line kubevirt.qtpl:339
func StreamVmRestoreToVm(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:339
	qw422016.N().S(`
`)
//line kubevirt.qtpl:341
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	targetName := Require(obj["spec"].(map[string]any)["target"].(map[string]any)["name"].(string))

//line kubevirt.qtpl:344
	qw422016.N().S(`
k8s:VirtualMachine.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:345
	qw422016.N().Q(ns)
//line kubevirt.qtpl:345
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:345
	qw422016.N().Q(targetName)
//line kubevirt.qtpl:345
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:346
}

//line kubevirt.qtpl:346
func WriteVmRestoreToVm(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:346
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:346
	StreamVmRestoreToVm(qw422016, o)
//line kubevirt.qtpl:346
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:346
}

//line kubevirt.qtpl:346
func VmRestoreToVm(o interface{}) string {
//line kubevirt.qtpl:346
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:346
	WriteVmRestoreToVm(qb422016, o)
//line kubevirt.qtpl:346
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:346
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:346
	return qs422016
//line kubevirt.qtpl:346
}

// # VmToVmRestore finds restores targeting a VirtualMachine.
// name: VmToVmRestore
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineRestore.snapshot.kubevirt.io]
//

//line kubevirt.qtpl:357
func StreamVmToVmRestore(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:357
	qw422016.N().S(`
`)
//line kubevirt.qtpl:358
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:358
	qw422016.N().S(`
k8s:VirtualMachineRestore.snapshot.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:359
	qw422016.N().Q(ns)
//line kubevirt.qtpl:359
	qw422016.N().S(`,"labels":{"vm.kubevirt.io/name":`)
//line kubevirt.qtpl:359
	qw422016.N().Q(name)
//line kubevirt.qtpl:359
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:360
}

//line kubevirt.qtpl:360
func WriteVmToVmRestore(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:360
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:360
	StreamVmToVmRestore(qw422016, o)
//line kubevirt.qtpl:360
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:360
}

//line kubevirt.qtpl:360
func VmToVmRestore(o interface{}) string {
//line kubevirt.qtpl:360
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:360
	WriteVmToVmRestore(qb422016, o)
//line kubevirt.qtpl:360
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:360
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:360
	return qs422016
//line kubevirt.qtpl:360
}

// # VmRestoreToVmSnapshot finds the source snapshot of a restore.
// name: VmRestoreToVmSnapshot
// start:
//   domain: k8s
//   classes: [VirtualMachineRestore.snapshot.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineSnapshot.snapshot.kubevirt.io]
//

//line kubevirt.qtpl:371
func StreamVmRestoreToVmSnapshot(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:371
	qw422016.N().S(`
`)
//line kubevirt.qtpl:373
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	snapName := Require(obj["spec"].(map[string]any)["virtualMachineSnapshotName"].(string))

//line kubevirt.qtpl:376
	qw422016.N().S(`
k8s:VirtualMachineSnapshot.snapshot.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:377
	qw422016.N().Q(ns)
//line kubevirt.qtpl:377
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:377
	qw422016.N().Q(snapName)
//line kubevirt.qtpl:377
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:378
}

//line kubevirt.qtpl:378
func WriteVmRestoreToVmSnapshot(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:378
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:378
	StreamVmRestoreToVmSnapshot(qw422016, o)
//line kubevirt.qtpl:378
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:378
}

//line kubevirt.qtpl:378
func VmRestoreToVmSnapshot(o interface{}) string {
//line kubevirt.qtpl:378
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:378
	WriteVmRestoreToVmSnapshot(qb422016, o)
//line kubevirt.qtpl:378
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:378
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:378
	return qs422016
//line kubevirt.qtpl:378
}

// # VmExportToVm finds the source VirtualMachine of an export.
// name: VmExportToVm
// start:
//   domain: k8s
//   classes: [VirtualMachineExport.export.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
//

//line kubevirt.qtpl:389
func StreamVmExportToVm(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:389
	qw422016.N().S(`
`)
//line kubevirt.qtpl:391
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	src := obj["spec"].(map[string]any)["source"].(map[string]any)
	if src["kind"].(string) != "VirtualMachine" {
		Fail("not a VirtualMachine export")
	}

//line kubevirt.qtpl:395
	qw422016.N().S(`
k8s:VirtualMachine.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:396
	qw422016.N().Q(ns)
//line kubevirt.qtpl:396
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:396
	qw422016.N().Q(src["name"].(string))
//line kubevirt.qtpl:396
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:397
}

//line kubevirt.qtpl:397
func WriteVmExportToVm(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:397
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:397
	StreamVmExportToVm(qw422016, o)
//line kubevirt.qtpl:397
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:397
}

//line kubevirt.qtpl:397
func VmExportToVm(o interface{}) string {
//line kubevirt.qtpl:397
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:397
	WriteVmExportToVm(qb422016, o)
//line kubevirt.qtpl:397
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:397
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:397
	return qs422016
//line kubevirt.qtpl:397
}

// # VmExportToVmSnapshot finds the source VirtualMachineSnapshot of an export.
// name: VmExportToVmSnapshot
// start:
//   domain: k8s
//   classes: [VirtualMachineExport.export.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [VirtualMachineSnapshot.snapshot.kubevirt.io]
//

//line kubevirt.qtpl:408
func StreamVmExportToVmSnapshot(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:408
	qw422016.N().S(`
`)
//line kubevirt.qtpl:410
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	src := obj["spec"].(map[string]any)["source"].(map[string]any)
	if src["kind"].(string) != "VirtualMachineSnapshot" {
		Fail("not a VirtualMachineSnapshot export")
	}

//line kubevirt.qtpl:414
	qw422016.N().S(`
k8s:VirtualMachineSnapshot.snapshot.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:415
	qw422016.N().Q(ns)
//line kubevirt.qtpl:415
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:415
	qw422016.N().Q(src["name"].(string))
//line kubevirt.qtpl:415
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:416
}

//line kubevirt.qtpl:416
func WriteVmExportToVmSnapshot(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:416
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:416
	StreamVmExportToVmSnapshot(qw422016, o)
//line kubevirt.qtpl:416
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:416
}

//line kubevirt.qtpl:416
func VmExportToVmSnapshot(o interface{}) string {
//line kubevirt.qtpl:416
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:416
	WriteVmExportToVmSnapshot(qb422016, o)
//line kubevirt.qtpl:416
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:416
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:416
	return qs422016
//line kubevirt.qtpl:416
}

// # VmExportToPVC finds the source PVC of an export.
// name: VmExportToPVC
// start:
//   domain: k8s
//   classes: [VirtualMachineExport.export.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [PersistentVolumeClaim]
//

//line kubevirt.qtpl:427
func StreamVmExportToPVC(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:427
	qw422016.N().S(`
`)
//line kubevirt.qtpl:429
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	src := obj["spec"].(map[string]any)["source"].(map[string]any)
	if src["kind"].(string) != "PersistentVolumeClaim" {
		Fail("not a PersistentVolumeClaim export")
	}

//line kubevirt.qtpl:433
	qw422016.N().S(`
k8s:PersistentVolumeClaim:{"namespace":`)
//line kubevirt.qtpl:434
	qw422016.N().Q(ns)
//line kubevirt.qtpl:434
	qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:434
	qw422016.N().Q(src["name"].(string))
//line kubevirt.qtpl:434
	qw422016.N().S(`}
`)
//line kubevirt.qtpl:435
}

//line kubevirt.qtpl:435
func WriteVmExportToPVC(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:435
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:435
	StreamVmExportToPVC(qw422016, o)
//line kubevirt.qtpl:435
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:435
}

//line kubevirt.qtpl:435
func VmExportToPVC(o interface{}) string {
//line kubevirt.qtpl:435
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:435
	WriteVmExportToPVC(qb422016, o)
//line kubevirt.qtpl:435
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:435
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:435
	return qs422016
//line kubevirt.qtpl:435
}

// # NodeToVmi finds VirtualMachineInstances running on a Node.
// name: NodeToVmi
// start:
//   domain: k8s
//   classes: [Node]
// goal:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
//

//line kubevirt.qtpl:446
func StreamNodeToVmi(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:446
	qw422016.N().S(`
`)
//line kubevirt.qtpl:447
	_, _, _, name, _ := k8sMetadata(o)
	RequireAll(name)

//line kubevirt.qtpl:447
	qw422016.N().S(`
k8s:VirtualMachineInstance.kubevirt.io:{"labels":{"kubevirt.io/nodeName":`)
//line kubevirt.qtpl:448
	qw422016.N().Q(name)
//line kubevirt.qtpl:448
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:449
}

//line kubevirt.qtpl:449
func WriteNodeToVmi(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:449
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:449
	StreamNodeToVmi(qw422016, o)
//line kubevirt.qtpl:449
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:449
}

//line kubevirt.qtpl:449
func NodeToVmi(o interface{}) string {
//line kubevirt.qtpl:449
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:449
	WriteNodeToVmi(qb422016, o)
//line kubevirt.qtpl:449
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:449
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:449
	return qs422016
//line kubevirt.qtpl:449
}

// # DataVolumeToImporterPod finds the CDI importer Pod for a DataVolume.
// name: DataVolumeToImporterPod
// start:
//   domain: k8s
//   classes: [DataVolume.cdi.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line kubevirt.qtpl:460
func StreamDataVolumeToImporterPod(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:460
	qw422016.N().S(`
`)
//line kubevirt.qtpl:461
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line kubevirt.qtpl:461
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line kubevirt.qtpl:462
	qw422016.N().Q(ns)
//line kubevirt.qtpl:462
	qw422016.N().S(`,"labels":{"cdi.kubevirt.io/storage.import.importPvcName":`)
//line kubevirt.qtpl:462
	qw422016.N().Q(name)
//line kubevirt.qtpl:462
	qw422016.N().S(`}}
`)
//line kubevirt.qtpl:463
}

//line kubevirt.qtpl:463
func WriteDataVolumeToImporterPod(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:463
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:463
	StreamDataVolumeToImporterPod(qw422016, o)
//line kubevirt.qtpl:463
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:463
}

//line kubevirt.qtpl:463
func DataVolumeToImporterPod(o interface{}) string {
//line kubevirt.qtpl:463
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:463
	WriteDataVolumeToImporterPod(qb422016, o)
//line kubevirt.qtpl:463
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:463
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:463
	return qs422016
//line kubevirt.qtpl:463
}

// # VmToNetAttachDef finds NetworkAttachmentDefinitions referenced by a VirtualMachine.
// name: VmToNetAttachDef
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [NetworkAttachmentDefinition.k8s.cni.cncf.io]
//

//line kubevirt.qtpl:474
func StreamVmToNetAttachDef(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:474
	qw422016.N().S(`
`)
//line kubevirt.qtpl:476
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	networks := mapSlice(obj["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any), "networks")

//line kubevirt.qtpl:479
	qw422016.N().S(`
`)
//line kubevirt.qtpl:480
	for _, n := range networks {
//line kubevirt.qtpl:480
		qw422016.N().S(`
`)
//line kubevirt.qtpl:481
		net := n.(map[string]any)

//line kubevirt.qtpl:481
		qw422016.N().S(`
`)
//line kubevirt.qtpl:482
		if m, ok := net["multus"].(map[string]any); ok {
//line kubevirt.qtpl:482
			qw422016.N().S(`
`)
//line kubevirt.qtpl:483
			netName := m["networkName"].(string)

//line kubevirt.qtpl:483
			qw422016.N().S(`
`)
//line kubevirt.qtpl:484
			if !strings.Contains(netName, "/") {
//line kubevirt.qtpl:484
				qw422016.N().S(`
k8s:NetworkAttachmentDefinition.k8s.cni.cncf.io:{"namespace":`)
//line kubevirt.qtpl:485
				qw422016.N().Q(ns)
//line kubevirt.qtpl:485
				qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:485
				qw422016.N().Q(netName)
//line kubevirt.qtpl:485
				qw422016.N().S(`}
`)
//line kubevirt.qtpl:486
			}
//line kubevirt.qtpl:486
			qw422016.N().S(`
`)
//line kubevirt.qtpl:487
		}
//line kubevirt.qtpl:487
		qw422016.N().S(`
`)
//line kubevirt.qtpl:488
	}
//line kubevirt.qtpl:488
	qw422016.N().S(`
`)
//line kubevirt.qtpl:489
}

//line kubevirt.qtpl:489
func WriteVmToNetAttachDef(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:489
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:489
	StreamVmToNetAttachDef(qw422016, o)
//line kubevirt.qtpl:489
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:489
}

//line kubevirt.qtpl:489
func VmToNetAttachDef(o interface{}) string {
//line kubevirt.qtpl:489
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:489
	WriteVmToNetAttachDef(qb422016, o)
//line kubevirt.qtpl:489
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:489
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:489
	return qs422016
//line kubevirt.qtpl:489
}

// # VmiToNetAttachDef finds NetworkAttachmentDefinitions referenced by a VirtualMachineInstance.
// name: VmiToNetAttachDef
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [NetworkAttachmentDefinition.k8s.cni.cncf.io]
//

//line kubevirt.qtpl:500
func StreamVmiToNetAttachDef(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:500
	qw422016.N().S(`
`)
//line kubevirt.qtpl:502
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	networks := mapSlice(obj["spec"].(map[string]any), "networks")

//line kubevirt.qtpl:505
	qw422016.N().S(`
`)
//line kubevirt.qtpl:506
	for _, n := range networks {
//line kubevirt.qtpl:506
		qw422016.N().S(`
`)
//line kubevirt.qtpl:507
		net := n.(map[string]any)

//line kubevirt.qtpl:507
		qw422016.N().S(`
`)
//line kubevirt.qtpl:508
		if m, ok := net["multus"].(map[string]any); ok {
//line kubevirt.qtpl:508
			qw422016.N().S(`
`)
//line kubevirt.qtpl:509
			netName := m["networkName"].(string)

//line kubevirt.qtpl:509
			qw422016.N().S(`
`)
//line kubevirt.qtpl:510
			if !strings.Contains(netName, "/") {
//line kubevirt.qtpl:510
				qw422016.N().S(`
k8s:NetworkAttachmentDefinition.k8s.cni.cncf.io:{"namespace":`)
//line kubevirt.qtpl:511
				qw422016.N().Q(ns)
//line kubevirt.qtpl:511
				qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:511
				qw422016.N().Q(netName)
//line kubevirt.qtpl:511
				qw422016.N().S(`}
`)
//line kubevirt.qtpl:512
			}
//line kubevirt.qtpl:512
			qw422016.N().S(`
`)
//line kubevirt.qtpl:513
		}
//line kubevirt.qtpl:513
		qw422016.N().S(`
`)
//line kubevirt.qtpl:514
	}
//line kubevirt.qtpl:514
	qw422016.N().S(`
`)
//line kubevirt.qtpl:515
}

//line kubevirt.qtpl:515
func WriteVmiToNetAttachDef(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:515
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:515
	StreamVmiToNetAttachDef(qw422016, o)
//line kubevirt.qtpl:515
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:515
}

//line kubevirt.qtpl:515
func VmiToNetAttachDef(o interface{}) string {
//line kubevirt.qtpl:515
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:515
	WriteVmiToNetAttachDef(qb422016, o)
//line kubevirt.qtpl:515
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:515
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:515
	return qs422016
//line kubevirt.qtpl:515
}

// # VmToSecret finds Secrets referenced by a VirtualMachine's volumes and accessCredentials.
// name: VmToSecret
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [Secret]
//

//line kubevirt.qtpl:526
func StreamVmToSecret(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:526
	qw422016.N().S(`
`)
//line kubevirt.qtpl:528
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	tmplSpec := obj["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any)
	volumes := mapSlice(tmplSpec, "volumes")
	creds := mapSlice(tmplSpec, "accessCredentials")
	names := kvSecretNames(volumes, creds)
	RequireAll(names)

//line kubevirt.qtpl:535
	qw422016.N().S(`
`)
//line kubevirt.qtpl:536
	for _, n := range names {
//line kubevirt.qtpl:536
		qw422016.N().S(`
k8s:Secret:{"namespace":`)
//line kubevirt.qtpl:537
		qw422016.N().Q(ns)
//line kubevirt.qtpl:537
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:537
		qw422016.N().Q(n)
//line kubevirt.qtpl:537
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:538
	}
//line kubevirt.qtpl:538
	qw422016.N().S(`
`)
//line kubevirt.qtpl:539
}

//line kubevirt.qtpl:539
func WriteVmToSecret(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:539
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:539
	StreamVmToSecret(qw422016, o)
//line kubevirt.qtpl:539
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:539
}

//line kubevirt.qtpl:539
func VmToSecret(o interface{}) string {
//line kubevirt.qtpl:539
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:539
	WriteVmToSecret(qb422016, o)
//line kubevirt.qtpl:539
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:539
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:539
	return qs422016
//line kubevirt.qtpl:539
}

// # VmiToSecret finds Secrets referenced by a VirtualMachineInstance's volumes.
// name: VmiToSecret
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [Secret]
//

//line kubevirt.qtpl:550
func StreamVmiToSecret(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:550
	qw422016.N().S(`
`)
//line kubevirt.qtpl:552
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")
	creds := mapSlice(obj["spec"].(map[string]any), "accessCredentials")
	names := kvSecretNames(volumes, creds)
	RequireAll(names)

//line kubevirt.qtpl:558
	qw422016.N().S(`
`)
//line kubevirt.qtpl:559
	for _, n := range names {
//line kubevirt.qtpl:559
		qw422016.N().S(`
k8s:Secret:{"namespace":`)
//line kubevirt.qtpl:560
		qw422016.N().Q(ns)
//line kubevirt.qtpl:560
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:560
		qw422016.N().Q(n)
//line kubevirt.qtpl:560
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:561
	}
//line kubevirt.qtpl:561
	qw422016.N().S(`
`)
//line kubevirt.qtpl:562
}

//line kubevirt.qtpl:562
func WriteVmiToSecret(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:562
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:562
	StreamVmiToSecret(qw422016, o)
//line kubevirt.qtpl:562
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:562
}

//line kubevirt.qtpl:562
func VmiToSecret(o interface{}) string {
//line kubevirt.qtpl:562
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:562
	WriteVmiToSecret(qb422016, o)
//line kubevirt.qtpl:562
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:562
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:562
	return qs422016
//line kubevirt.qtpl:562
}

// # VmToConfigMap finds ConfigMaps referenced by a VirtualMachine's volumes.
// name: VmToConfigMap
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [ConfigMap]
//

//line kubevirt.qtpl:573
func StreamVmToConfigMap(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:573
	qw422016.N().S(`
`)
//line kubevirt.qtpl:575
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any), "volumes")
	names := kvConfigMapNames(volumes)
	RequireAll(names)

//line kubevirt.qtpl:580
	qw422016.N().S(`
`)
//line kubevirt.qtpl:581
	for _, n := range names {
//line kubevirt.qtpl:581
		qw422016.N().S(`
k8s:ConfigMap:{"namespace":`)
//line kubevirt.qtpl:582
		qw422016.N().Q(ns)
//line kubevirt.qtpl:582
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:582
		qw422016.N().Q(n)
//line kubevirt.qtpl:582
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:583
	}
//line kubevirt.qtpl:583
	qw422016.N().S(`
`)
//line kubevirt.qtpl:584
}

//line kubevirt.qtpl:584
func WriteVmToConfigMap(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:584
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:584
	StreamVmToConfigMap(qw422016, o)
//line kubevirt.qtpl:584
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:584
}

//line kubevirt.qtpl:584
func VmToConfigMap(o interface{}) string {
//line kubevirt.qtpl:584
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:584
	WriteVmToConfigMap(qb422016, o)
//line kubevirt.qtpl:584
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:584
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:584
	return qs422016
//line kubevirt.qtpl:584
}

// # VmiToConfigMap finds ConfigMaps referenced by a VirtualMachineInstance's volumes.
// name: VmiToConfigMap
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [ConfigMap]
//

//line kubevirt.qtpl:595
func StreamVmiToConfigMap(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:595
	qw422016.N().S(`
`)
//line kubevirt.qtpl:597
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")
	names := kvConfigMapNames(volumes)
	RequireAll(names)

//line kubevirt.qtpl:602
	qw422016.N().S(`
`)
//line kubevirt.qtpl:603
	for _, n := range names {
//line kubevirt.qtpl:603
		qw422016.N().S(`
k8s:ConfigMap:{"namespace":`)
//line kubevirt.qtpl:604
		qw422016.N().Q(ns)
//line kubevirt.qtpl:604
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:604
		qw422016.N().Q(n)
//line kubevirt.qtpl:604
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:605
	}
//line kubevirt.qtpl:605
	qw422016.N().S(`
`)
//line kubevirt.qtpl:606
}

//line kubevirt.qtpl:606
func WriteVmiToConfigMap(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:606
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:606
	StreamVmiToConfigMap(qw422016, o)
//line kubevirt.qtpl:606
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:606
}

//line kubevirt.qtpl:606
func VmiToConfigMap(o interface{}) string {
//line kubevirt.qtpl:606
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:606
	WriteVmiToConfigMap(qb422016, o)
//line kubevirt.qtpl:606
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:606
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:606
	return qs422016
//line kubevirt.qtpl:606
}

// # VmToServiceAccount finds ServiceAccounts referenced by a VirtualMachine's volumes.
// name: VmToServiceAccount
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [ServiceAccount]
//

//line kubevirt.qtpl:617
func StreamVmToServiceAccount(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:617
	qw422016.N().S(`
`)
//line kubevirt.qtpl:619
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any), "volumes")

//line kubevirt.qtpl:622
	qw422016.N().S(`
`)
//line kubevirt.qtpl:623
	for _, v := range volumes {
//line kubevirt.qtpl:623
		qw422016.N().S(`
`)
//line kubevirt.qtpl:624
		vol := v.(map[string]any)

//line kubevirt.qtpl:624
		qw422016.N().S(`
`)
//line kubevirt.qtpl:625
		if sa, ok := vol["serviceAccount"].(map[string]any); ok {
//line kubevirt.qtpl:625
			qw422016.N().S(`
k8s:ServiceAccount:{"namespace":`)
//line kubevirt.qtpl:626
			qw422016.N().Q(ns)
//line kubevirt.qtpl:626
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:626
			qw422016.N().Q(sa["serviceAccountName"].(string))
//line kubevirt.qtpl:626
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:627
		}
//line kubevirt.qtpl:627
		qw422016.N().S(`
`)
//line kubevirt.qtpl:628
	}
//line kubevirt.qtpl:628
	qw422016.N().S(`
`)
//line kubevirt.qtpl:629
}

//line kubevirt.qtpl:629
func WriteVmToServiceAccount(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:629
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:629
	StreamVmToServiceAccount(qw422016, o)
//line kubevirt.qtpl:629
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:629
}

//line kubevirt.qtpl:629
func VmToServiceAccount(o interface{}) string {
//line kubevirt.qtpl:629
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:629
	WriteVmToServiceAccount(qb422016, o)
//line kubevirt.qtpl:629
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:629
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:629
	return qs422016
//line kubevirt.qtpl:629
}

// # VmiToServiceAccount finds ServiceAccounts referenced by a VirtualMachineInstance's volumes.
// name: VmiToServiceAccount
// start:
//   domain: k8s
//   classes: [VirtualMachineInstance.kubevirt.io]
// goal:
//   domain: k8s
//   classes: [ServiceAccount]
//

//line kubevirt.qtpl:640
func StreamVmiToServiceAccount(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:640
	qw422016.N().S(`
`)
//line kubevirt.qtpl:642
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	volumes := mapSlice(obj["spec"].(map[string]any), "volumes")

//line kubevirt.qtpl:645
	qw422016.N().S(`
`)
//line kubevirt.qtpl:646
	for _, v := range volumes {
//line kubevirt.qtpl:646
		qw422016.N().S(`
`)
//line kubevirt.qtpl:647
		vol := v.(map[string]any)

//line kubevirt.qtpl:647
		qw422016.N().S(`
`)
//line kubevirt.qtpl:648
		if sa, ok := vol["serviceAccount"].(map[string]any); ok {
//line kubevirt.qtpl:648
			qw422016.N().S(`
k8s:ServiceAccount:{"namespace":`)
//line kubevirt.qtpl:649
			qw422016.N().Q(ns)
//line kubevirt.qtpl:649
			qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:649
			qw422016.N().Q(sa["serviceAccountName"].(string))
//line kubevirt.qtpl:649
			qw422016.N().S(`}
`)
//line kubevirt.qtpl:650
		}
//line kubevirt.qtpl:650
		qw422016.N().S(`
`)
//line kubevirt.qtpl:651
	}
//line kubevirt.qtpl:651
	qw422016.N().S(`
`)
//line kubevirt.qtpl:652
}

//line kubevirt.qtpl:652
func WriteVmiToServiceAccount(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:652
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:652
	StreamVmiToServiceAccount(qw422016, o)
//line kubevirt.qtpl:652
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:652
}

//line kubevirt.qtpl:652
func VmiToServiceAccount(o interface{}) string {
//line kubevirt.qtpl:652
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:652
	WriteVmiToServiceAccount(qb422016, o)
//line kubevirt.qtpl:652
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:652
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:652
	return qs422016
//line kubevirt.qtpl:652
}

// # VmToInstancetype finds the instancetype or cluster instancetype for a VirtualMachine.
// name: VmToInstancetype
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//

//line kubevirt.qtpl:662
func StreamVmToInstancetype(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:662
	qw422016.N().S(`
`)
//line kubevirt.qtpl:664
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	it := obj["spec"].(map[string]any)["instancetype"].(map[string]any)
	name := Require(it["name"].(string))
	kind, _ := it["kind"].(string)

//line kubevirt.qtpl:669
	qw422016.N().S(`
`)
//line kubevirt.qtpl:670
	if kind == "VirtualMachineInstancetype" {
//line kubevirt.qtpl:670
		qw422016.N().S(`
k8s:VirtualMachineInstancetype.instancetype.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:671
		qw422016.N().Q(ns)
//line kubevirt.qtpl:671
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:671
		qw422016.N().Q(name)
//line kubevirt.qtpl:671
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:672
	} else {
//line kubevirt.qtpl:672
		qw422016.N().S(`
k8s:VirtualMachineClusterInstancetype.instancetype.kubevirt.io:{"name":`)
//line kubevirt.qtpl:673
		qw422016.N().Q(name)
//line kubevirt.qtpl:673
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:674
	}
//line kubevirt.qtpl:674
	qw422016.N().S(`
`)
//line kubevirt.qtpl:675
}

//line kubevirt.qtpl:675
func WriteVmToInstancetype(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:675
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:675
	StreamVmToInstancetype(qw422016, o)
//line kubevirt.qtpl:675
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:675
}

//line kubevirt.qtpl:675
func VmToInstancetype(o interface{}) string {
//line kubevirt.qtpl:675
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:675
	WriteVmToInstancetype(qb422016, o)
//line kubevirt.qtpl:675
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:675
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:675
	return qs422016
//line kubevirt.qtpl:675
}

// # VmToPreference finds the preference or cluster preference for a VirtualMachine.
// name: VmToPreference
// start:
//   domain: k8s
//   classes: [VirtualMachine.kubevirt.io]
// goal:
//   domain: k8s
//

//line kubevirt.qtpl:685
func StreamVmToPreference(qw422016 *qt422016.Writer, o interface{}) {
//line kubevirt.qtpl:685
	qw422016.N().S(`
`)
//line kubevirt.qtpl:687
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	pref := obj["spec"].(map[string]any)["preference"].(map[string]any)
	name := Require(pref["name"].(string))
	kind, _ := pref["kind"].(string)

//line kubevirt.qtpl:692
	qw422016.N().S(`
`)
//line kubevirt.qtpl:693
	if kind == "VirtualMachinePreference" {
//line kubevirt.qtpl:693
		qw422016.N().S(`
k8s:VirtualMachinePreference.instancetype.kubevirt.io:{"namespace":`)
//line kubevirt.qtpl:694
		qw422016.N().Q(ns)
//line kubevirt.qtpl:694
		qw422016.N().S(`,"name":`)
//line kubevirt.qtpl:694
		qw422016.N().Q(name)
//line kubevirt.qtpl:694
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:695
	} else {
//line kubevirt.qtpl:695
		qw422016.N().S(`
k8s:VirtualMachineClusterPreference.instancetype.kubevirt.io:{"name":`)
//line kubevirt.qtpl:696
		qw422016.N().Q(name)
//line kubevirt.qtpl:696
		qw422016.N().S(`}
`)
//line kubevirt.qtpl:697
	}
//line kubevirt.qtpl:697
	qw422016.N().S(`
`)
//line kubevirt.qtpl:698
}

//line kubevirt.qtpl:698
func WriteVmToPreference(qq422016 qtio422016.Writer, o interface{}) {
//line kubevirt.qtpl:698
	qw422016 := qt422016.AcquireWriter(qq422016)
//line kubevirt.qtpl:698
	StreamVmToPreference(qw422016, o)
//line kubevirt.qtpl:698
	qt422016.ReleaseWriter(qw422016)
//line kubevirt.qtpl:698
}

//line kubevirt.qtpl:698
func VmToPreference(o interface{}) string {
//line kubevirt.qtpl:698
	qb422016 := qt422016.AcquireByteBuffer()
//line kubevirt.qtpl:698
	WriteVmToPreference(qb422016, o)
//line kubevirt.qtpl:698
	qs422016 := string(qb422016.B)
//line kubevirt.qtpl:698
	qt422016.ReleaseByteBuffer(qb422016)
//line kubevirt.qtpl:698
	return qs422016
//line kubevirt.qtpl:698
}
