// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "log.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// # Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE
// #
//

//line log.qtpl:4
package quickrules

//line log.qtpl:6
import "github.com/korrel8r/korrel8r/pkg/domains/log"

// # LogToPod creates a k8s Pod query from the pod attributes of a log entry.
// name: LogToPod
// start:
//   domain: log
//   classes: [application, infrastructure, audit]
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line log.qtpl:17
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line log.qtpl:17
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line log.qtpl:17
func StreamLogToPod(qw422016 *qt422016.Writer, o interface{}) {
//line log.qtpl:17
	qw422016.N().S(`
`)
//line log.qtpl:19
	l := o.(log.Object)
	ns := Default(l["kubernetes_namespace_name"], l["k8s_namespace_name"])
	name := Default(l["kubernetes_pod_name"], l["k8s_pod_name"])
	RequireAll(ns, name)

//line log.qtpl:23
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line log.qtpl:24
	qw422016.N().Q(ns)
//line log.qtpl:24
	qw422016.N().S(`,"name":`)
//line log.qtpl:24
	qw422016.N().Q(name)
//line log.qtpl:24
	qw422016.N().S(`}
`)
//line log.qtpl:25
}

//line log.qtpl:25
func WriteLogToPod(qq422016 qtio422016.Writer, o interface{}) {
//line log.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line log.qtpl:25
	StreamLogToPod(qw422016, o)
//line log.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line log.qtpl:25
}

//line log.qtpl:25
func LogToPod(o interface{}) string {
//line log.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line log.qtpl:25
	WriteLogToPod(qb422016, o)
//line log.qtpl:25
	qs422016 := string(qb422016.B)
//line log.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line log.qtpl:25
	return qs422016
//line log.qtpl:25
}

// # PodToLogs finds logs for a pod.
// name: PodToLogs
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: log
//

//line log.qtpl:35
func StreamPodToLogs(qw422016 *qt422016.Writer, o interface{}) {
//line log.qtpl:35
	qw422016.N().S(`
`)
//line log.qtpl:36
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line log.qtpl:36
	qw422016.N().S(`
log:`)
//line log.qtpl:37
	qw422016.N().S(logTypeForNamespace(ns))
//line log.qtpl:37
	qw422016.N().S(`:{"namespace":`)
//line log.qtpl:37
	qw422016.N().Q(ns)
//line log.qtpl:37
	qw422016.N().S(`,"name":`)
//line log.qtpl:37
	qw422016.N().Q(name)
//line log.qtpl:37
	qw422016.N().S(`}
`)
//line log.qtpl:38
}

//line log.qtpl:38
func WritePodToLogs(qq422016 qtio422016.Writer, o interface{}) {
//line log.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line log.qtpl:38
	StreamPodToLogs(qw422016, o)
//line log.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line log.qtpl:38
}

//line log.qtpl:38
func PodToLogs(o interface{}) string {
//line log.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line log.qtpl:38
	WritePodToLogs(qb422016, o)
//line log.qtpl:38
	qs422016 := string(qb422016.B)
//line log.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line log.qtpl:38
	return qs422016
//line log.qtpl:38
}

// # ServiceToLogs finds logs for pods selected by a service.
// name: ServiceToLogs
// start:
//   domain: k8s
//   classes: [Service]
// goal:
//   domain: log
//

//line log.qtpl:48
func StreamServiceToLogs(qw422016 *qt422016.Writer, o interface{}) {
//line log.qtpl:48
	qw422016.N().S(`
`)
//line log.qtpl:50
	obj, _, ns, _, _ := k8sMetadata(o)
	RequireAll(ns)
	selector := obj["spec"].(map[string]any)["selector"]
	RequireAll(selector)

//line log.qtpl:54
	qw422016.N().S(`
log:`)
//line log.qtpl:55
	qw422016.N().S(logTypeForNamespace(ns))
//line log.qtpl:55
	qw422016.N().S(`:{"namespace":`)
//line log.qtpl:55
	qw422016.N().Q(ns)
//line log.qtpl:55
	qw422016.N().S(`,"labels":`)
//line log.qtpl:55
	qw422016.N().S(ToJSON(selector))
//line log.qtpl:55
	qw422016.N().S(`}
`)
//line log.qtpl:56
}

//line log.qtpl:56
func WriteServiceToLogs(qq422016 qtio422016.Writer, o interface{}) {
//line log.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line log.qtpl:56
	StreamServiceToLogs(qw422016, o)
//line log.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line log.qtpl:56
}

//line log.qtpl:56
func ServiceToLogs(o interface{}) string {
//line log.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line log.qtpl:56
	WriteServiceToLogs(qb422016, o)
//line log.qtpl:56
	qs422016 := string(qb422016.B)
//line log.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line log.qtpl:56
	return qs422016
//line log.qtpl:56
}
