// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "metric.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line metric.qtpl:1
package quickrules

//line metric.qtpl:3
import "github.com/korrel8r/korrel8r/pkg/domains/metric"

// # MetricToPod creates a k8s Pod query from the pod labels of a metric.
// name: MetricToPod
// start:
//   domain: metric
//   classes: [metric]
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line metric.qtpl:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line metric.qtpl:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line metric.qtpl:14
func StreamMetricToPod(qw422016 *qt422016.Writer, o interface{}) {
//line metric.qtpl:14
	qw422016.N().S(`
`)
//line metric.qtpl:16
	m := o.(metric.Object)
	ns := Default(m.Labels["namespace"], m.Labels["k8s_namespace_name"])
	name := Default(m.Labels["pod"], m.Labels["k8s_pod_name"])
	RequireAll(ns, name)

//line metric.qtpl:20
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line metric.qtpl:21
	qw422016.N().Q(ns)
//line metric.qtpl:21
	qw422016.N().S(`,"name":`)
//line metric.qtpl:21
	qw422016.N().Q(name)
//line metric.qtpl:21
	qw422016.N().S(`}
`)
//line metric.qtpl:22
}

//line metric.qtpl:22
func WriteMetricToPod(qq422016 qtio422016.Writer, o interface{}) {
//line metric.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line metric.qtpl:22
	StreamMetricToPod(qw422016, o)
//line metric.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line metric.qtpl:22
}

//line metric.qtpl:22
func MetricToPod(o interface{}) string {
//line metric.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line metric.qtpl:22
	WriteMetricToPod(qb422016, o)
//line metric.qtpl:22
	qs422016 := string(qb422016.B)
//line metric.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line metric.qtpl:22
	return qs422016
//line metric.qtpl:22
}

// # MetricToDeployment creates a k8s Deployment query from the deployment labels of a metric.
// name: MetricToDeployment
// start:
//   domain: metric
//   classes: [metric]
// goal:
//   domain: k8s
//   classes: [Deployment.apps]
//

//line metric.qtpl:33
func StreamMetricToDeployment(qw422016 *qt422016.Writer, o interface{}) {
//line metric.qtpl:33
	qw422016.N().S(`
`)
//line metric.qtpl:35
	m := o.(metric.Object)
	ns := Default(m.Labels["namespace"], m.Labels["k8s_namespace_name"])
	name := Default(m.Labels["deployment"], m.Labels["k8s_deployment_name"])
	RequireAll(ns, name)

//line metric.qtpl:39
	qw422016.N().S(`
k8s:Deployment.apps:{"namespace":`)
//line metric.qtpl:40
	qw422016.N().Q(ns)
//line metric.qtpl:40
	qw422016.N().S(`,"name":`)
//line metric.qtpl:40
	qw422016.N().Q(name)
//line metric.qtpl:40
	qw422016.N().S(`}
`)
//line metric.qtpl:41
}

//line metric.qtpl:41
func WriteMetricToDeployment(qq422016 qtio422016.Writer, o interface{}) {
//line metric.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line metric.qtpl:41
	StreamMetricToDeployment(qw422016, o)
//line metric.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line metric.qtpl:41
}

//line metric.qtpl:41
func MetricToDeployment(o interface{}) string {
//line metric.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line metric.qtpl:41
	WriteMetricToDeployment(qb422016, o)
//line metric.qtpl:41
	qs422016 := string(qb422016.B)
//line metric.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line metric.qtpl:41
	return qs422016
//line metric.qtpl:41
}

// # MetricToDaemonSet creates a k8s DaemonSet query from the daemonset labels of a metric.
// name: MetricToDaemonSet
// start:
//   domain: metric
//   classes: [metric]
// goal:
//   domain: k8s
//   classes: [DaemonSet.apps]
//

//line metric.qtpl:52
func StreamMetricToDaemonSet(qw422016 *qt422016.Writer, o interface{}) {
//line metric.qtpl:52
	qw422016.N().S(`
`)
//line metric.qtpl:54
	m := o.(metric.Object)
	ns := Default(m.Labels["namespace"], m.Labels["k8s_namespace_name"])
	name := Default(m.Labels["daemonset"], m.Labels["k8s_daemonset_name"])
	RequireAll(ns, name)

//line metric.qtpl:58
	qw422016.N().S(`
k8s:DaemonSet.apps:{"namespace":`)
//line metric.qtpl:59
	qw422016.N().Q(ns)
//line metric.qtpl:59
	qw422016.N().S(`,"name":`)
//line metric.qtpl:59
	qw422016.N().Q(name)
//line metric.qtpl:59
	qw422016.N().S(`}
`)
//line metric.qtpl:60
}

//line metric.qtpl:60
func WriteMetricToDaemonSet(qq422016 qtio422016.Writer, o interface{}) {
//line metric.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line metric.qtpl:60
	StreamMetricToDaemonSet(qw422016, o)
//line metric.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line metric.qtpl:60
}

//line metric.qtpl:60
func MetricToDaemonSet(o interface{}) string {
//line metric.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line metric.qtpl:60
	WriteMetricToDaemonSet(qb422016, o)
//line metric.qtpl:60
	qs422016 := string(qb422016.B)
//line metric.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line metric.qtpl:60
	return qs422016
//line metric.qtpl:60
}

// # MetricToStatefulSet creates a k8s StatefulSet query from the statefulset labels of a metric.
// name: MetricToStatefulSet
// start:
//   domain: metric
//   classes: [metric]
// goal:
//   domain: k8s
//   classes: [StatefulSet.apps]
//

//line metric.qtpl:71
func StreamMetricToStatefulSet(qw422016 *qt422016.Writer, o interface{}) {
//line metric.qtpl:71
	qw422016.N().S(`
`)
//line metric.qtpl:73
	m := o.(metric.Object)
	ns := Default(m.Labels["namespace"], m.Labels["k8s_namespace_name"])
	name := Default(m.Labels["statefulset"], m.Labels["k8s_statefulset_name"])
	RequireAll(ns, name)

//line metric.qtpl:77
	qw422016.N().S(`
k8s:StatefulSet.apps:{"namespace":`)
//line metric.qtpl:78
	qw422016.N().Q(ns)
//line metric.qtpl:78
	qw422016.N().S(`,"name":`)
//line metric.qtpl:78
	qw422016.N().Q(name)
//line metric.qtpl:78
	qw422016.N().S(`}
`)
//line metric.qtpl:79
}

//line metric.qtpl:79
func WriteMetricToStatefulSet(qq422016 qtio422016.Writer, o interface{}) {
//line metric.qtpl:79
	qw422016 := qt422016.AcquireWriter(qq422016)
//line metric.qtpl:79
	StreamMetricToStatefulSet(qw422016, o)
//line metric.qtpl:79
	qt422016.ReleaseWriter(qw422016)
//line metric.qtpl:79
}

//line metric.qtpl:79
func MetricToStatefulSet(o interface{}) string {
//line metric.qtpl:79
	qb422016 := qt422016.AcquireByteBuffer()
//line metric.qtpl:79
	WriteMetricToStatefulSet(qb422016, o)
//line metric.qtpl:79
	qs422016 := string(qb422016.B)
//line metric.qtpl:79
	qt422016.ReleaseByteBuffer(qb422016)
//line metric.qtpl:79
	return qs422016
//line metric.qtpl:79
}

// # MetricToNode creates a k8s Node query from the node labels of a metric.
// name: MetricToNode
// start:
//   domain: metric
//   classes: [metric]
// goal:
//   domain: k8s
//   classes: [Node]
//

//line metric.qtpl:90
func StreamMetricToNode(qw422016 *qt422016.Writer, o interface{}) {
//line metric.qtpl:90
	qw422016.N().S(`
`)
//line metric.qtpl:92
	m := o.(metric.Object)
	name := Default(m.Labels["node"], m.Labels["k8s_node_name"])
	RequireAll(name)

//line metric.qtpl:95
	qw422016.N().S(`
k8s:Node:{"name":`)
//line metric.qtpl:96
	qw422016.N().Q(name)
//line metric.qtpl:96
	qw422016.N().S(`}
`)
//line metric.qtpl:97
}

//line metric.qtpl:97
func WriteMetricToNode(qq422016 qtio422016.Writer, o interface{}) {
//line metric.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line metric.qtpl:97
	StreamMetricToNode(qw422016, o)
//line metric.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line metric.qtpl:97
}

//line metric.qtpl:97
func MetricToNode(o interface{}) string {
//line metric.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line metric.qtpl:97
	WriteMetricToNode(qb422016, o)
//line metric.qtpl:97
	qs422016 := string(qb422016.B)
//line metric.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line metric.qtpl:97
	return qs422016
//line metric.qtpl:97
}
