// Copyright: This file is part of korrel8r, released under https://github.com/korrel8r/korrel8r/blob/main/LICENSE

// Code generated by qtc from "trace.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line trace.qtpl:1
package quickrules

//line trace.qtpl:3
import "github.com/korrel8r/korrel8r/pkg/domains/trace"

// # TraceToPod finds the k8s Pod associated with a trace span.
// name: TraceToPod
// start:
//   domain: trace
// goal:
//   domain: k8s
//   classes: [Pod]
//

//line trace.qtpl:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line trace.qtpl:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line trace.qtpl:13
func StreamTraceToPod(qw422016 *qt422016.Writer, o interface{}) {
//line trace.qtpl:13
	qw422016.N().S(`
`)
//line trace.qtpl:15
	a := o.(*trace.Span).Attributes
	ns := Require(a["k8s.namespace.name"].(string))
	name := Require(a["k8s.pod.name"].(string))

//line trace.qtpl:18
	qw422016.N().S(`
k8s:Pod:{"namespace":`)
//line trace.qtpl:19
	qw422016.N().Q(ns)
//line trace.qtpl:19
	qw422016.N().S(`,"name":`)
//line trace.qtpl:19
	qw422016.N().Q(name)
//line trace.qtpl:19
	qw422016.N().S(`}
`)
//line trace.qtpl:20
}

//line trace.qtpl:20
func WriteTraceToPod(qq422016 qtio422016.Writer, o interface{}) {
//line trace.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line trace.qtpl:20
	StreamTraceToPod(qw422016, o)
//line trace.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line trace.qtpl:20
}

//line trace.qtpl:20
func TraceToPod(o interface{}) string {
//line trace.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line trace.qtpl:20
	WriteTraceToPod(qb422016, o)
//line trace.qtpl:20
	qs422016 := string(qb422016.B)
//line trace.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line trace.qtpl:20
	return qs422016
//line trace.qtpl:20
}

// # PodToTrace finds trace spans for a k8s Pod.
// name: PodToTrace
// start:
//   domain: k8s
//   classes: [Pod]
// goal:
//   domain: trace
//

//line trace.qtpl:30
func StreamPodToTrace(qw422016 *qt422016.Writer, o interface{}) {
//line trace.qtpl:30
	qw422016.N().S(`
`)
//line trace.qtpl:31
	_, _, ns, name, _ := k8sMetadata(o)
	RequireAll(ns, name)

//line trace.qtpl:31
	qw422016.N().S(`
trace:span:{resource.k8s.namespace.name=`)
//line trace.qtpl:32
	qw422016.N().Q(ns)
//line trace.qtpl:32
	qw422016.N().S(`&&resource.k8s.pod.name=`)
//line trace.qtpl:32
	qw422016.N().Q(name)
//line trace.qtpl:32
	qw422016.N().S(`}
`)
//line trace.qtpl:33
}

//line trace.qtpl:33
func WritePodToTrace(qq422016 qtio422016.Writer, o interface{}) {
//line trace.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line trace.qtpl:33
	StreamPodToTrace(qw422016, o)
//line trace.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line trace.qtpl:33
}

//line trace.qtpl:33
func PodToTrace(o interface{}) string {
//line trace.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line trace.qtpl:33
	WritePodToTrace(qb422016, o)
//line trace.qtpl:33
	qs422016 := string(qb422016.B)
//line trace.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line trace.qtpl:33
	return qs422016
//line trace.qtpl:33
}
